AMF-Placer: src/lib/HiFPlacer/placement/packing/ParallelCLBPacker_PackingCLBSite.cc File Reference
ParallelCLBPacker_PackingCLBSite.cc File Reference
This implementation file contains APIs' implementation related to the CLBSite-level processes in the ParallelCLBPacker which finally packs LUT/FF/MUX/CARRY elements into legal CLB sites in a parallel approach.
#include "ParallelCLBPacker.h"
Functions
bool isLUT6 (DesignInfo::DesignCell *cell)
Detailed Description
This implementation file contains APIs' implementation related to the CLBSite-level processes in the ParallelCLBPacker which finally packs LUT/FF/MUX/CARRY elements into legal CLB sites in a parallel approach.
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition in file ParallelCLBPacker_PackingCLBSite.cc.
Function Documentation
isLUT6()
bool isLUT6 (DesignInfo::DesignCell * cell)
Definition at line 536 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::maxCardinalityMatching().