AMF-Placer: src/lib/HiFPlacer/placement/packing/ParallelCLBPacker.cc File Reference
ParallelCLBPacker.cc File Reference
This implementation file contains APIs' implementation of the ParallelCLBPacker which finally packs LUT/FF/MUX/CARRY elements into legal CLB sites in a parallel approach.
#include "ParallelCLBPacker.h"
Macros
#define TIMINGDP
Functions
float getAngle (float v1x, float v1y, float v2x, float v2y)
bool hasLUT62 (ParallelCLBPacker::PackingCLBSite::SiteBELMapping &slots)
bool containLUTRAMCells (PlacementInfo::PlacementUnit *curPU)
Detailed Description
This implementation file contains APIs' implementation of the ParallelCLBPacker which finally packs LUT/FF/MUX/CARRY elements into legal CLB sites in a parallel approach.
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Definition in file ParallelCLBPacker.cc.
Macro Definition Documentation
TIMINGDP
#define TIMINGDP
Definition at line 16 of file ParallelCLBPacker.cc.
Function Documentation
containLUTRAMCells()
bool containLUTRAMCells (PlacementInfo::PlacementUnit * curPU)
Definition at line 2971 of file ParallelCLBPacker.cc.
Referenced by ParallelCLBPacker::dumpCLBPlacementTcl().
getAngle()
float getAngle (float v1x, float v1y, float v2x, float v2y) inline
Definition at line 513 of file ParallelCLBPacker.cc.
Referenced by ParallelCLBPacker::findNeiborSitesFromBinGrid(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), and ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath().
hasLUT62()
bool hasLUT62 (ParallelCLBPacker::PackingCLBSite::SiteBELMapping & slots)
Definition at line 2710 of file ParallelCLBPacker.cc.
Referenced by ParallelCLBPacker::dumpCLBPlacementTcl().