AMF-Placer: src/lib/HiFPlacer/problemSolvers/SAPlacer.cc File Reference
SAPlacer.cc File Reference
#include "SAPlacer.h"
#include <algorithm>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <iostream>
Functions
void swapVectors (std::vector< int > &a, std::vector< int > &b)
void shuffleVectors (std::vector< std::vector< int > > &a, boost::mt19937 &rng)
Detailed Description
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Definition in file SAPlacer.cc.
Function Documentation
shuffleVectors()
void shuffleVectors (std::vector< std::vector< int > > & a, boost::mt19937 & rng)
Definition at line 153 of file SAPlacer.cc.
Referenced by SAPlacer::randomShuffleRowColumn(), and SAPlacer::randomSwapInWideRange().
swapVectors()
void swapVectors (std::vector< int > & a, std::vector< int > & b)
Definition at line 146 of file SAPlacer.cc.
Referenced by shuffleVectors().