AMF-Placer: PlacementTimingInfo Class Reference
PlacementTimingInfo Class Reference
PlacementTimingInfo is the container which record the timing information related to placement.
#include <PlacementTimingInfo.h>
Classes
class TimingGraph
a directed graph for timing analysis
Public Member Functions
PlacementTimingInfo (DesignInfo *designInfo, DeviceInfo *deviceInfo, std::map< std::string, std::string > &JSONCfg)
Construct a new Placement Timing Info object based on the information of design and device.
~PlacementTimingInfo ()
void buildSimpleTimingGraph ()
build a simple timing graph, where the inner delay between pin paris for an element will be identical
std::vector< TimingGraph< DesignInfo::DesignCell >::TimingNode * > & getSimplePlacementTimingInfo ()
Get the Simple Timing Info object which regard design cells as timing nodes.
std::vector< TimingGraph< DesignInfo::DesignCell >::TimingNode * > & getSimplePlacementTimingInfo_PathLenSorted ()
TimingGraph< DesignInfo::DesignCell > * getSimplePlacementTimingGraph ()
Get the Simple Placement Timing Graph object.
int getLongPathThresholdLevel ()
int getMediumPathThresholdLevel ()
DeviceInfo * getDeviceInfo ()
void setDSPInnerDelay ()
Private Attributes
DesignInfo * designInfo
DeviceInfo * deviceInfo
std::map< std::string, std::string > & JSONCfg
TimingGraph< DesignInfo::DesignCell > * simpleTimingGraph = nullptr
bool verbose = false
float clockPeriod = 10.0
bool DSPCritical = false
std::map< DesignInfo::DesignNet *, float > clockNet2Period
std::map< int, float > cellId2Period
Detailed Description
PlacementTimingInfo is the container which record the timing information related to placement.
Definition at line 48 of file PlacementTimingInfo.h.
Constructor & Destructor Documentation
PlacementTimingInfo()
PlacementTimingInfo::PlacementTimingInfo (DesignInfo * designInfo, DeviceInfo * deviceInfo, std::map< std::string, std::string > & JSONCfg)
Construct a new Placement Timing Info object based on the information of design and device.
Parameters
designInfo pointer of design information
deviceInfo pointer of device information
JSONCfg the user-defined placement configuration
Definition at line 35 of file PlacementTimingInfo.cc.
~PlacementTimingInfo()
PlacementTimingInfo::~PlacementTimingInfo () inline
Definition at line 59 of file PlacementTimingInfo.h.
Member Function Documentation
buildSimpleTimingGraph()
void PlacementTimingInfo::buildSimpleTimingGraph ()
build a simple timing graph, where the inner delay between pin paris for an element will be identical
Definition at line 92 of file PlacementTimingInfo.cc.
Referenced by PlacementInfo::buildSimpleTimingGraph().
getDeviceInfo()
DeviceInfo* PlacementTimingInfo::getDeviceInfo () inline
Definition at line 865 of file PlacementTimingInfo.h.
getLongPathThresholdLevel()
int PlacementTimingInfo::getLongPathThresholdLevel () inline
Definition at line 855 of file PlacementTimingInfo.h.
Referenced by PlacementInfo::buildSimpleTimingGraph().
getMediumPathThresholdLevel()
int PlacementTimingInfo::getMediumPathThresholdLevel () inline
Definition at line 860 of file PlacementTimingInfo.h.
Referenced by PlacementInfo::buildSimpleTimingGraph().
getSimplePlacementTimingGraph()
TimingGraph<DesignInfo::DesignCell>* PlacementTimingInfo::getSimplePlacementTimingGraph () inline
Get the Simple Placement Timing Graph object.
Returns
TimingGraph<DesignInfo::DesignCell>*
Definition at line 850 of file PlacementTimingInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementTimingOptimizer::conductStaticTimingAnalysis(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), PlacementTimingOptimizer::findCriticalPath(), PlacementTimingOptimizer::findCriticalPaths(), PlacementTimingOptimizer::getSortedTimingNodes(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), PlacementTimingOptimizer::incrementalStaticTimingAnalysis_forPUWithLocation(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), PlacementInfo::reloadNets(), and PlacementInfo::transferPaintData().
getSimplePlacementTimingInfo()
std::vector<TimingGraph<DesignInfo::DesignCell>::TimingNode *>& PlacementTimingInfo::getSimplePlacementTimingInfo () inline
Get the Simple Timing Info object which regard design cells as timing nodes.
Returns
std::vector<TimingGraph<DesignInfo::DesignCell>::TimingNode *>&
Definition at line 835 of file PlacementTimingInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack(), PlacementTimingOptimizer::conductStaticTimingAnalysis(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), ClusterPlacer::getPlacementUnitMaxPathLen(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathLen(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathNegativeSlack(), PlacementTimingOptimizer::getPUId2Slack(), PlacementTimingOptimizer::getSlackThr(), PlacementTimingOptimizer::getWorstSlackOfCell(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), and WirelengthOptimizer::LUTLUTPairing_TimingDriven().
getSimplePlacementTimingInfo_PathLenSorted()
std::vector<TimingGraph<DesignInfo::DesignCell>::TimingNode *>& PlacementTimingInfo::getSimplePlacementTimingInfo_PathLenSorted () inline
Definition at line 840 of file PlacementTimingInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), and ClusterPlacer::createLongPathClusterUnits().
setDSPInnerDelay()
void PlacementTimingInfo::setDSPInnerDelay ()
Definition at line 74 of file PlacementTimingInfo.cc.
Referenced by AMFPlacer::run().
Member Data Documentation
cellId2Period
std::map<int, float> PlacementTimingInfo::cellId2Period private
Definition at line 886 of file PlacementTimingInfo.h.
Referenced by buildSimpleTimingGraph(), and PlacementTimingInfo().
clockNet2Period
std::map<DesignInfo::DesignNet *, float> PlacementTimingInfo::clockNet2Period private
Definition at line 885 of file PlacementTimingInfo.h.
Referenced by PlacementTimingInfo().
clockPeriod
float PlacementTimingInfo::clockPeriod = 10.0 private
Definition at line 882 of file PlacementTimingInfo.h.
Referenced by buildSimpleTimingGraph(), and PlacementTimingInfo().
designInfo
DesignInfo* PlacementTimingInfo::designInfo private
Definition at line 873 of file PlacementTimingInfo.h.
Referenced by buildSimpleTimingGraph(), PlacementTimingInfo(), and setDSPInnerDelay().
deviceInfo
DeviceInfo* PlacementTimingInfo::deviceInfo private
Definition at line 874 of file PlacementTimingInfo.h.
Referenced by getDeviceInfo().
DSPCritical
bool PlacementTimingInfo::DSPCritical = false private
Definition at line 883 of file PlacementTimingInfo.h.
Referenced by buildSimpleTimingGraph(), PlacementTimingInfo(), and setDSPInnerDelay().
JSONCfg
std::map<std::string, std::string>& PlacementTimingInfo::JSONCfg private
Definition at line 877 of file PlacementTimingInfo.h.
Referenced by PlacementTimingInfo().
simpleTimingGraph
TimingGraph<DesignInfo::DesignCell>* PlacementTimingInfo::simpleTimingGraph = nullptr private
Definition at line 879 of file PlacementTimingInfo.h.
Referenced by buildSimpleTimingGraph(), getLongPathThresholdLevel(), getMediumPathThresholdLevel(), getSimplePlacementTimingGraph(), getSimplePlacementTimingInfo(), getSimplePlacementTimingInfo_PathLenSorted(), setDSPInnerDelay(), and ~PlacementTimingInfo().
verbose
bool PlacementTimingInfo::verbose = false private
Definition at line 880 of file PlacementTimingInfo.h.
Referenced by PlacementTimingInfo().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/placementTiming/PlacementTimingInfo.h
src/lib/HiFPlacer/placement/placementTiming/PlacementTimingInfo.cc