AMF-Placer: PlacementTimingOptimizer Class Reference
PlacementTimingOptimizer Class Reference
#include <PlacementTimingOptimizer.h>
Public Member Functions
PlacementTimingOptimizer (PlacementInfo *placementInfo, std::map< std::string, std::string > &JSONCfg)
~PlacementTimingOptimizer ()
void propogateArrivalTime ()
std::vector< int > findCriticalPath ()
std::vector< std::vector< int > > findCriticalPaths (float criticalRatio, bool checkOverlap=true, int pathNumThr=1000, int converThr=30)
std::vector< std::vector< int > > findCriticalPaths (float criticalRatio, std::vector< bool > &FFDirectlyDrivenButNotInOneSlot)
float getWorstSlackOfCell (DesignInfo::DesignCell *srcCell)
float conductStaticTimingAnalysis (bool enforeOptimisticTiming=false)
void incrementalStaticTimingAnalysis_forPUWithLocation (PlacementInfo::PlacementUnit *curPU, float targetX, float targetY)
void setPinsLocation ()
void clusterLongPathInOneClockRegion (int pathLenThr, float clusterThrRatio)
void dumpClockRegionClusters ()
void stretchClockRegionColumns ()
void initPois ()
float getPois (int v)
float getEffectFactor ()
void setEffectFactor (float _effectFactor)
float getDelayByModel (PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::TimingNode *node1, PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::TimingNode *node2, float X1, float Y1, float X2, float Y2)
float getDelayByModel (float X1, float Y1, float X2, float Y2)
float getDelayByModel_conservative (float X1, float Y1, float X2, float Y2)
void pauseCounter ()
float getSlackThr ()
std::map< PlacementInfo::PlacementNet *, int > & getNetActualSlackPinNum ()
std::vector< float > & getPUId2Slack (bool update=false)
std::vector< PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::TimingNode * > & getSortedTimingNodes ()
Public Attributes
const float timingC0 [10] = {95.05263521, -26.50563359, 77.42394117, 106.29195883, -14.975527}
const float timingC1 [10] = {123.05017047, -169.25614191, -117.28028144, 208.53573639, 174.2573465}
const float timingC2 [10] = {234.7694101, -433.99467294, -64.96319998, 373.78606257, 139.45226658}
Private Member Functions
float getDis (float x1, float y1, float x2, float y2)
Private Attributes
PlacementInfo * placementInfo = nullptr
PlacementTimingInfo * timingInfo = nullptr
DesignInfo * designInfo
DeviceInfo * deviceInfo
std::map< std::string, std::string > & JSONCfg
bool verbose = false
float y2xRatio = 1
bool DSPCritical = false
float xDelayUnit = 0.13
float yDelayUnit = 0.10
int poisN = 1000
float lambdaPois = 100
int STA_Cnt = 0
float effectFactor = 0
bool clockRegionClusterTooLarge = false
std::vector< float > pois
std::vector< std::vector< int > > clockRegionclusters
std::map< PlacementInfo::PlacementNet *, int > netActualSlackPinNum
std::vector< float > PUId2Slack
bool increaseLowDelayVal = false
bool enableCounter = true
Detailed Description
Definition at line 33 of file PlacementTimingOptimizer.h.
Constructor & Destructor Documentation
PlacementTimingOptimizer()
PlacementTimingOptimizer::PlacementTimingOptimizer (PlacementInfo * placementInfo, std::map< std::string, std::string > & JSONCfg)
Definition at line 18 of file PlacementTimingOptimizer.cc.
~PlacementTimingOptimizer()
PlacementTimingOptimizer::~PlacementTimingOptimizer () inline
Definition at line 37 of file PlacementTimingOptimizer.h.
Member Function Documentation
clusterLongPathInOneClockRegion()
void PlacementTimingOptimizer::clusterLongPathInOneClockRegion (int pathLenThr, float clusterThrRatio)
Definition at line 523 of file PlacementTimingOptimizer.cc.
Referenced by AMFPlacer::run(), and ~PlacementTimingOptimizer().
conductStaticTimingAnalysis()
float PlacementTimingOptimizer::conductStaticTimingAnalysis (bool enforeOptimisticTiming = false)
Definition at line 206 of file PlacementTimingOptimizer.cc.
Referenced by clusterLongPathInOneClockRegion(), ParallelCLBPacker::exceptionHandling(), GlobalPlacer::GlobalPlacement_CLBElements(), ParallelCLBPacker::packCLBs(), AMFPlacer::run(), and ~PlacementTimingOptimizer().
dumpClockRegionClusters()
void PlacementTimingOptimizer::dumpClockRegionClusters ()
Definition at line 845 of file PlacementTimingOptimizer.cc.
Referenced by clusterLongPathInOneClockRegion(), and ~PlacementTimingOptimizer().
findCriticalPath()
std::vector< int > PlacementTimingOptimizer::findCriticalPath ()
Definition at line 85 of file PlacementTimingOptimizer.cc.
Referenced by ~PlacementTimingOptimizer().
findCriticalPaths() [1/2]
std::vector< std::vector< int > > PlacementTimingOptimizer::findCriticalPaths (float criticalRatio, bool checkOverlap = true, int pathNumThr = 1000, int converThr = 30)
Definition at line 107 of file PlacementTimingOptimizer.cc.
Referenced by ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ~PlacementTimingOptimizer().
findCriticalPaths() [2/2]
std::vector< std::vector< int > > PlacementTimingOptimizer::findCriticalPaths (float criticalRatio, std::vector< bool > & FFDirectlyDrivenButNotInOneSlot)
Definition at line 160 of file PlacementTimingOptimizer.cc.
getDelayByModel() [1/2]
float PlacementTimingOptimizer::getDelayByModel (PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::TimingNode * node1, PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::TimingNode * node2, float X1, float Y1, float X2, float Y2) inline
Definition at line 91 of file PlacementTimingOptimizer.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), conductStaticTimingAnalysis(), getPUId2Slack(), getSlackThr(), getWorstSlackOfCell(), incrementalStaticTimingAnalysis_forPUWithLocation(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), and ParallelCLBPacker::timingDrivenDetailedPlacement_swap().
getDelayByModel() [2/2]
float PlacementTimingOptimizer::getDelayByModel (float X1, float Y1, float X2, float Y2) inline
Definition at line 102 of file PlacementTimingOptimizer.h.
getDelayByModel_conservative()
float PlacementTimingOptimizer::getDelayByModel_conservative (float X1, float Y1, float X2, float Y2) inline
Definition at line 111 of file PlacementTimingOptimizer.h.
Referenced by getDelayByModel().
getDis()
float PlacementTimingOptimizer::getDis (float x1, float y1, float x2, float y2) inline private
Definition at line 196 of file PlacementTimingOptimizer.h.
getEffectFactor()
float PlacementTimingOptimizer::getEffectFactor () inline
Definition at line 81 of file PlacementTimingOptimizer.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), GlobalPlacer::GlobalPlacement_CLBElements(), WirelengthOptimizer::GlobalPlacementQPSolve(), and WirelengthOptimizer::updateB2BNetWeight().
getNetActualSlackPinNum()
std::map<PlacementInfo::PlacementNet *, int>& PlacementTimingOptimizer::getNetActualSlackPinNum () inline
Definition at line 168 of file PlacementTimingOptimizer.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased().
getPois()
float PlacementTimingOptimizer::getPois (int v) inline
Definition at line 69 of file PlacementTimingOptimizer.h.
getPUId2Slack()
std::vector< float > & PlacementTimingOptimizer::getPUId2Slack (bool update = false)
Definition at line 889 of file PlacementTimingOptimizer.cc.
Referenced by ParallelCLBPacker::exceptionHandling(), getNetActualSlackPinNum(), and ParallelCLBPacker::ripUpAndLegalizae().
getSlackThr()
float PlacementTimingOptimizer::getSlackThr ()
Definition at line 367 of file PlacementTimingOptimizer.cc.
Referenced by WirelengthOptimizer::GlobalPlacementQPSolve(), and pauseCounter().
getSortedTimingNodes()
std::vector<PlacementTimingInfo::TimingGraph<DesignInfo::DesignCell>::TimingNode *>& PlacementTimingOptimizer::getSortedTimingNodes () inline
Definition at line 175 of file PlacementTimingOptimizer.h.
getWorstSlackOfCell()
float PlacementTimingOptimizer::getWorstSlackOfCell (DesignInfo::DesignCell * srcCell)
Definition at line 54 of file PlacementTimingOptimizer.cc.
Referenced by ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ~PlacementTimingOptimizer().
incrementalStaticTimingAnalysis_forPUWithLocation()
void PlacementTimingOptimizer::incrementalStaticTimingAnalysis_forPUWithLocation (PlacementInfo::PlacementUnit * curPU, float targetX, float targetY)
Definition at line 471 of file PlacementTimingOptimizer.cc.
Referenced by ~PlacementTimingOptimizer().
initPois()
void PlacementTimingOptimizer::initPois () inline
Definition at line 56 of file PlacementTimingOptimizer.h.
Referenced by PlacementTimingOptimizer().
pauseCounter()
void PlacementTimingOptimizer::pauseCounter () inline
Definition at line 162 of file PlacementTimingOptimizer.h.
Referenced by ParallelCLBPacker::packCLBs().
propogateArrivalTime()
void PlacementTimingOptimizer::propogateArrivalTime ()
Definition at line 883 of file PlacementTimingOptimizer.cc.
Referenced by ~PlacementTimingOptimizer().
setEffectFactor()
void PlacementTimingOptimizer::setEffectFactor (float _effectFactor) inline
Definition at line 86 of file PlacementTimingOptimizer.h.
setPinsLocation()
void PlacementTimingOptimizer::setPinsLocation ()
Definition at line 34 of file PlacementTimingOptimizer.cc.
Referenced by conductStaticTimingAnalysis(), incrementalStaticTimingAnalysis_forPUWithLocation(), and ~PlacementTimingOptimizer().
stretchClockRegionColumns()
void PlacementTimingOptimizer::stretchClockRegionColumns ()
Definition at line 730 of file PlacementTimingOptimizer.cc.
Referenced by clusterLongPathInOneClockRegion(), and ~PlacementTimingOptimizer().
Member Data Documentation
clockRegionclusters
std::vector<std::vector<int> > PlacementTimingOptimizer::clockRegionclusters private
Definition at line 210 of file PlacementTimingOptimizer.h.
Referenced by clusterLongPathInOneClockRegion(), and dumpClockRegionClusters().
clockRegionClusterTooLarge
bool PlacementTimingOptimizer::clockRegionClusterTooLarge = false private
Definition at line 208 of file PlacementTimingOptimizer.h.
Referenced by clusterLongPathInOneClockRegion().
designInfo
DesignInfo* PlacementTimingOptimizer::designInfo private
Definition at line 186 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis(), incrementalStaticTimingAnalysis_forPUWithLocation(), PlacementTimingOptimizer(), and setPinsLocation().
deviceInfo
DeviceInfo* PlacementTimingOptimizer::deviceInfo private
Definition at line 187 of file PlacementTimingOptimizer.h.
Referenced by clusterLongPathInOneClockRegion(), getDelayByModel_conservative(), PlacementTimingOptimizer(), and stretchClockRegionColumns().
DSPCritical
bool PlacementTimingOptimizer::DSPCritical = false private
Definition at line 194 of file PlacementTimingOptimizer.h.
Referenced by PlacementTimingOptimizer().
effectFactor
float PlacementTimingOptimizer::effectFactor = 0 private
Definition at line 207 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis(), getEffectFactor(), and setEffectFactor().
enableCounter
bool PlacementTimingOptimizer::enableCounter = true private
Definition at line 214 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis(), and pauseCounter().
increaseLowDelayVal
bool PlacementTimingOptimizer::increaseLowDelayVal = false private
Definition at line 213 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis().
JSONCfg
std::map<std::string, std::string>& PlacementTimingOptimizer::JSONCfg private
Definition at line 190 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis(), and dumpClockRegionClusters().
lambdaPois
float PlacementTimingOptimizer::lambdaPois = 100 private
Definition at line 205 of file PlacementTimingOptimizer.h.
Referenced by initPois().
netActualSlackPinNum
std::map<PlacementInfo::PlacementNet *, int> PlacementTimingOptimizer::netActualSlackPinNum private
Definition at line 211 of file PlacementTimingOptimizer.h.
Referenced by getNetActualSlackPinNum(), and getSlackThr().
placementInfo
PlacementInfo* PlacementTimingOptimizer::placementInfo = nullptr private
Definition at line 184 of file PlacementTimingOptimizer.h.
Referenced by clusterLongPathInOneClockRegion(), conductStaticTimingAnalysis(), dumpClockRegionClusters(), findCriticalPaths(), getPUId2Slack(), getSlackThr(), getWorstSlackOfCell(), incrementalStaticTimingAnalysis_forPUWithLocation(), setPinsLocation(), and stretchClockRegionColumns().
pois
std::vector<float> PlacementTimingOptimizer::pois private
Definition at line 209 of file PlacementTimingOptimizer.h.
Referenced by getPois(), and initPois().
poisN
int PlacementTimingOptimizer::poisN = 1000 private
Definition at line 204 of file PlacementTimingOptimizer.h.
Referenced by initPois().
PUId2Slack
std::vector<float> PlacementTimingOptimizer::PUId2Slack private
Definition at line 212 of file PlacementTimingOptimizer.h.
Referenced by getPUId2Slack().
STA_Cnt
int PlacementTimingOptimizer::STA_Cnt = 0 private
Definition at line 206 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis().
timingC0
const float PlacementTimingOptimizer::timingC0[10] = {95.05263521, -26.50563359, 77.42394117, 106.29195883, -14.975527}
Definition at line 107 of file PlacementTimingOptimizer.h.
timingC1
const float PlacementTimingOptimizer::timingC1[10] = {123.05017047, -169.25614191, -117.28028144, 208.53573639, 174.2573465}
Definition at line 108 of file PlacementTimingOptimizer.h.
timingC2
const float PlacementTimingOptimizer::timingC2[10] = {234.7694101, -433.99467294, -64.96319998, 373.78606257, 139.45226658}
Definition at line 109 of file PlacementTimingOptimizer.h.
timingInfo
PlacementTimingInfo* PlacementTimingOptimizer::timingInfo = nullptr private
Definition at line 185 of file PlacementTimingOptimizer.h.
Referenced by conductStaticTimingAnalysis(), findCriticalPath(), findCriticalPaths(), getSortedTimingNodes(), incrementalStaticTimingAnalysis_forPUWithLocation(), and propogateArrivalTime().
verbose
bool PlacementTimingOptimizer::verbose = false private
Definition at line 192 of file PlacementTimingOptimizer.h.
Referenced by PlacementTimingOptimizer().
xDelayUnit
float PlacementTimingOptimizer::xDelayUnit = 0.13 private
Definition at line 201 of file PlacementTimingOptimizer.h.
y2xRatio
float PlacementTimingOptimizer::y2xRatio = 1 private
Definition at line 193 of file PlacementTimingOptimizer.h.
Referenced by PlacementTimingOptimizer().
yDelayUnit
float PlacementTimingOptimizer::yDelayUnit = 0.10 private
Definition at line 202 of file PlacementTimingOptimizer.h.
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/placementTiming/PlacementTimingOptimizer.h
src/lib/HiFPlacer/placement/placementTiming/PlacementTimingOptimizer.cc