AMF-Placer: ParallelCLBPacker::PackingCLBSite::PackingCLBCluster Class Reference
ParallelCLBPacker::PackingCLBSite::PackingCLBCluster Class Reference
PackingCLBCluster is a container of cells/PlacementUnits which can be packed in the corresponding CLB site.
#include <ParallelCLBPacker.h>
Public Member Functions
PackingCLBCluster ()
Construct a new Packing CLB Cluster object (it should not be called.)
PackingCLBCluster (PackingCLBSite *parentPackingCLB)
~PackingCLBCluster ()
PackingCLBCluster (PackingCLBCluster *anotherPackingCLBCluster)
int getId () const
Get the Id of the PackingCLBCluster (just for debug information don't use it in algorithm)
void refreshId ()
refresh the Id of the PackingCLBCluster so we can know it is changed.
unsigned int getPairPinNum (DesignInfo::DesignCell *LUTA, DesignInfo::DesignCell *LUTB)
check how many input pins will be needed if the two LUTs are packed.
void maxCardinalityMatching (bool verbose=false)
conduct maximun cardinality matching algorithm to pair LUTs
int getInternalPinsNum (PlacementInfo::PlacementNet *curNet)
Get the number of pins within this site for a given net (more pins are located in ont site will reduce the demand of routing resource)
bool compatibleInOneHalfCLB (DesignInfo::ControlSetInfo *CSPtr, int anotherHalfCLB)
check whether a control set can be placed in a given half CLB
bool compatibleInOneHalfCLB (int halfCLB, int anotherHalfCLB)
check whether a given half CLB can be placed with another given half CLB
bool addLUT (DesignInfo::DesignCell *curLUT)
try to add a given LUT into this cluster
bool addToFFSet (DesignInfo::DesignCell *curFF, int halfCLB)
try to add a given FF into a specific half CLB in this cluster
bool addToFFSet (std::vector< DesignInfo::DesignCell * > curFFs, int halfCLB)
try to add a given list of FFs into a specific half CLB in this cluster
bool addFF (DesignInfo::DesignCell *curFF, int enforceHalfCLB=-1, bool enforceMainFFSlot=false)
try to add a given FF into this cluster
bool addFFGroup (std::vector< DesignInfo::DesignCell * > curFFs, int enforceHalfCLB, bool enforceMainFFSlot, bool isMuxMacro)
try to add a given list of FFs into this cluster
bool isMuxMacro (DesignInfo::DesignCell *cell)
bool isCarryMacro (DesignInfo::DesignCell *cell)
void evictFFsFromMuxHalfCLB ()
try to move FFs in Mux slot to other controlSet
void moveFFFromCS1ToCS0 (DesignInfo::DesignCell *targetFF, int CSGroupId1, int CSGroupId0)
bool evictFFsFromCarryHalfCLB (unsigned int FFSetId)
try to move FFs in Mux slot to other controlSet
void removeLUT (DesignInfo::DesignCell *curLUT)
remove a specific LUT from this candidate cluster
void removeFF (DesignInfo::DesignCell *curFF)
remove a specific FF from this candidate cluster
void removePUToConstructDetCluster (PlacementInfo::PlacementUnit *tmpPU)
remove some PlacementInfo::PlacementUnit from the cluster for later determined cluster construction of this site
bool isPUTypeCompatibleWithSiteType (PlacementInfo::PlacementUnit *tmpPU)
check whether the type of the given PlacementUnit is compatible with the site type
bool addPU (PlacementInfo::PlacementUnit *tmpPU, bool allowOverlap=false)
try to add a given PlacementUnit into this cluster
bool tryAddPU (PlacementInfo::PlacementUnit *tmpPU)
without modifying the original cluster container, try to add a given PlacementUnit into this cluster
bool checkAddPU (PlacementInfo::PlacementUnit *tmpPU)
void addPUFailReason (PlacementInfo::PlacementUnit *tmpPU)
find/print the reason why the PlacementUnit fails to be added into this cluster
bool contains (PlacementInfo::PlacementUnit *tmpPU)
check whether the cluster contains a specific PlacementUnit
const std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > & getPUs () const
std::set< DesignInfo::DesignCell * > getCellSet ()
const std::vector< PackedControlSet > & getFFControlSets () const
const std::set< DesignInfo::DesignCell * > & getSingleLUTs () const
Get the set of single LUTs in this cluster (some other LUTs have been paired for packing)
std::vector< DesignInfo::DesignCell * > getSortedSingleLUTs ()
Get the sorted list of single LUTs in this cluster (some other LUTs have been paired for packing)
void removeSingleLUT (DesignInfo::DesignCell *tmpLUT)
remove a single LUT from the set of single LUTs in this cluster
bool tryRemoveSingleLUT (DesignInfo::DesignCell *tmpLUT)
try to remove a single LUT from the single LUT set
bool tryRemoveSingleLUTFromPairs (DesignInfo::DesignCell *tmpLUT)
try to remove a LUT from the set of paired LUTs
bool tryRemoveLUTPairFromPairs (DesignInfo::DesignCell *tmpLUTA, DesignInfo::DesignCell *tmpLUTB)
try to remove a pair of LUTs from the set of paired LUTs
const std::set< std::pair< DesignInfo::DesignCell *, DesignInfo::DesignCell * > > & getPairedLUTs () const
Get the set of the paired LUTs.
std::vector< std::pair< DesignInfo::DesignCell *, DesignInfo::DesignCell * > > getSortedPairedLUTs ()
Get the sorted list of the paired LUTs.
bool areAllPUsValidForThisSite (const std::vector< PackingCLBSite * > &PUId2PackingCLBSite, PackingCLBSite *parentPackingCLBSite)
check whether all the PlacementUnit in this cluster are valid (not bound to other sites) for this site
float getScoreInSite () const
Get the score if this cluster is mapped the site.
void updateScoreInSite ()
update the score of this cluster by considering HPWL, interconnection density, timing and etc
void incrementalUpdateScoreInSite (PlacementInfo::PlacementUnit *tmpPU)
incrementally update the score of this cluster by considering that only a given PlacementUnit will be added into this cluster
PackingCLBSite * getParentPackingCLB () const
Get the Parent Packing CLB site of this cluster (this can be used to get more device information)
void clusterHash ()
we use a hash function to encode the cluster to easily check duplicated clusters in the candidates
int clusterHashWithAdditionalPU (PlacementInfo::PlacementUnit *tmpPU)
incrementally update the hash function with an additional PlacementUnit. This hash will be used to encode the cluster to easily check duplicated clusters in the candidates
int getHash ()
Get the hash code for this cluster.
int getHashConst () const
Get the hash code of this cluster without changing the class variables of this cluster.
float getHPWLChangeForPU (PlacementInfo::PlacementUnit *tmpPU)
get the HPWL change if a given PlacementUnit is moved to this site
float getTotalConnectivityScore () const
Get the connectivity term in the cluster score object.
float getHPWLChange () const
Get the HWPL change term in the cluster score object.
int getTotalNetNum () const
Get the total number of cells in this cluster.
int getTotalCellNum () const
Get the total number of cells in this cluster.
int getNumMuxes () const
Get the total number of MUX cells in this cluster.
int getTotalLen () const
Get the maximum length of the paths which involve this cluster.
float getTotalCellWeight () const
Get the total weights of cells in the cluster (each cell will have different weight in the placement)
bool containFF (DesignInfo::DesignCell *curFF)
check whether the cluster contains a specific FF cell
void printMyself ()
a API to print the information of cluster
bool checkCellCorrectness (PlacementInfo::PlacementUnit *tmpPU, bool isAddPU)
a verification function to check whether the cells in this cluster are REALLY LEGAL.
bool checkNumMuxCompatibleInFFSet (int i, int addNum)
check whether a specific number of Muxes can be compatible with a specific FFset for packing
int getPlacementUnitMaxPathLen (PlacementInfo::PlacementUnit *curPU)
Get the max length of paths involving a given PlacementUnit.
float getPlacementUnitMaxPathNegativeSlack (PlacementInfo::PlacementUnit *curPU)
Get the max length of paths involving a given PlacementUnit.
void recoverFFControlSets ()
Private Attributes
const unsigned int MaxNum_ControlSet = 4
const unsigned int MaxNum_FFinControlSet = 4
const unsigned int MaxNum_LUTSite = 8
int numMuxes = 0
PackingCLBSite * parentPackingCLB = nullptr
the paraent CLB site for this cluster
PlacementInfo * placementInfo = nullptr
the paraent CLB site for this cluster
float scoreInSite = -100000000
the evaluation score of packing for this cluster
int hashId = -3654
a hash id to record the elements in this cluster
bool hashed = false
int id = -1
the unique id for each cluster
std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > PUs
float totalConnectivityScore = 0
the connectivity score for this cluster
float HPWLChange = 0
the HPWL term for the wirelength optimization
int totalNetNum = 0
the cell number term in the cluster score
int totalCellNum = 0
int totalLen = 0
the term of timing (paths) in the packing score
float HPWLWeight = 0.01
the configurable weight for the wirelength in the cluster score
std::vector< PackedControlSet > FFControlSets
the control set information for this cluster
std::vector< PackedControlSet > FFControlSets_backup
std::set< DesignInfo::DesignCell * > singleLUTs
the set of LUTs have not been paired with other LUTs in the clutser
std::set< std::pair< DesignInfo::DesignCell *, DesignInfo::DesignCell * > > pairedLUTs
the paired LUTs in the cluster
Detailed Description
PackingCLBCluster is a container of cells/PlacementUnits which can be packed in the corresponding CLB site.
Definition at line 440 of file ParallelCLBPacker.h.
Constructor & Destructor Documentation
PackingCLBCluster() [1/3]
ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::PackingCLBCluster () inline
Construct a new Packing CLB Cluster object (it should not be called.)
Definition at line 447 of file ParallelCLBPacker.h.
Referenced by checkAddPU(), and tryAddPU().
PackingCLBCluster() [2/3]
ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::PackingCLBCluster (PackingCLBSite * parentPackingCLB) inline
Definition at line 452 of file ParallelCLBPacker.h.
~PackingCLBCluster()
ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::~PackingCLBCluster () inline
Definition at line 463 of file ParallelCLBPacker.h.
PackingCLBCluster() [3/3]
ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::PackingCLBCluster (PackingCLBCluster * anotherPackingCLBCluster) inline
Definition at line 465 of file ParallelCLBPacker.h.
Member Function Documentation
addFF()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addFF (DesignInfo::DesignCell * curFF, int enforceHalfCLB = -1, bool enforceMainFFSlot = false)
try to add a given FF into this cluster
Parameters
curFF a given FF
enforceHalfCLB (default -1/no limit) limit the candidate half CLB id for this FF
enforceMainFFSlot (default false) constaint that the FF can be only placed in the main half CLB (the one connected to LUT6 output pins in the CLB site). There are two types of half CLBs, we call those connected to LUT6 output pins "main half CLB slots" and those connected to LUT5 output pins "secondary half CLB slots". Some FFs (especially the virtual ones) should be mapped to the "main" ones.
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 248 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), evictFFsFromCarryHalfCLB(), and evictFFsFromMuxHalfCLB().
addFFGroup()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addFFGroup (std::vector< DesignInfo::DesignCell * > curFFs, int enforceHalfCLB, bool enforceMainFFSlot, bool isMuxMacro)
try to add a given list of FFs into this cluster
Parameters
curFFs a given list of FFs
enforceHalfCLB (default -1/no limit) limit the candidate half CLB id for this FF
enforceMainFFSlot (default false) constaint that the FF can be only placed in the main half CLB (the one connected to LUT6 output pins in the CLB site). There are two types of half CLBs, we call those connected to LUT6 output pins "main half CLB slots" and those connected to LUT5 output pins "secondary half CLB slots". Some FFs (especially the virtual ones) should be mapped to the "main" ones.
isMuxMacro
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 303 of file ParallelCLBPacker_PackingCLBCluster.cc.
addLUT()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT (DesignInfo::DesignCell * curLUT)
try to add a given LUT into this cluster
Parameters
curLUT a given LUT
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 101 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry().
addPU()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU (PlacementInfo::PlacementUnit * tmpPU, bool allowOverlap = false)
try to add a given PlacementUnit into this cluster
the addPU implemented is based on the following paper's Algorithm 1: G. Chen et al., RippleFPGA: Routability-Driven Simultaneous Packing and Placement for Modern FPGAs, IEEE Trans. Comput.-Aided Des. Integr. Circuits Syst., vol. 37, no. 10, pp. 20222035, Oct. 2018, doi: 10.1109/TCAD.2017.2778058.
Parameters
tmpPU a given PlacementUnit
allowOverlap whether it is successful if there is
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 609 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by checkAddPU(), ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs(), ParallelCLBPacker::PackingCLBSite::removeInvalidPUsFromNeighborPUs(), ParallelCLBPacker::ripUpAndLegalizae(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), and tryAddPU().
addPUFailReason()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPUFailReason (PlacementInfo::PlacementUnit * tmpPU)
find/print the reason why the PlacementUnit fails to be added into this cluster
Parameters
tmpPU a given PlacementUnit
Definition at line 384 of file ParallelCLBPacker_PackingCLBCluster.cc.
addToFFSet() [1/2]
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet (DesignInfo::DesignCell * curFF, int halfCLB)
try to add a given FF into a specific half CLB in this cluster
Parameters
curFF a given FF
halfCLB the target half CLB id in this cluster
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 161 of file ParallelCLBPacker_PackingCLBCluster.cc.
addToFFSet() [2/2]
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet (std::vector< DesignInfo::DesignCell * > curFFs, int halfCLB)
try to add a given list of FFs into a specific half CLB in this cluster
Parameters
curFFs a given list of FFs
halfCLB the target half CLB id in this cluster
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 236 of file ParallelCLBPacker_PackingCLBCluster.cc.
areAllPUsValidForThisSite()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::areAllPUsValidForThisSite (const std::vector< PackingCLBSite * > & PUId2PackingCLBSite, PackingCLBSite * parentPackingCLBSite) inline
check whether all the PlacementUnit in this cluster are valid (not bound to other sites) for this site
Parameters
PUId2PackingCLBSite the mapping from PUs to sites
parentPackingCLBSite the site for this cluster
Returns
true if all the PUs can be mapped to this site
false if some of the PUs CANNOT be mapped to this site
Definition at line 1281 of file ParallelCLBPacker.h.
checkAddPU()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkAddPU (PlacementInfo::PlacementUnit * tmpPU) inline
Definition at line 986 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), and ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath().
checkCellCorrectness()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkCellCorrectness (PlacementInfo::PlacementUnit * tmpPU, bool isAddPU)
a verification function to check whether the cells in this cluster are REALLY LEGAL.
Parameters
tmpPU
isAddPU
Returns
true
false
Definition at line 758 of file ParallelCLBPacker_PackingCLBCluster.cc.
checkNumMuxCompatibleInFFSet()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkNumMuxCompatibleInFFSet (int i, int addNum)
check whether a specific number of Muxes can be compatible with a specific FFset for packing
Since Mux will use some register input wires for the select signal, we have to check whether the packing is possible for this situation
Parameters
i the id for the FF set
addNum the number of Muxes we want to add into the CLB
Returns
true if the given number of Muxes can be added.
false if the given number of Muxes CANNOT be added.
Definition at line 279 of file ParallelCLBPacker_PackingCLBCluster.cc.
clusterHash()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::clusterHash () inline
we use a hash function to encode the cluster to easily check duplicated clusters in the candidates
Definition at line 1339 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), ParallelCLBPacker::PackingCLBSite::addLUTRAMMacro(), ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs(), and getHash().
clusterHashWithAdditionalPU()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::clusterHashWithAdditionalPU (PlacementInfo::PlacementUnit * tmpPU) inline
incrementally update the hash function with an additional PlacementUnit. This hash will be used to encode the cluster to easily check duplicated clusters in the candidates
Parameters
tmpPU
Returns
int
Definition at line 1384 of file ParallelCLBPacker.h.
compatibleInOneHalfCLB() [1/2]
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::compatibleInOneHalfCLB (DesignInfo::ControlSetInfo * CSPtr, int anotherHalfCLB)
check whether a control set can be placed in a given half CLB
Since in current architecture, FFs are packed in half CLBs in the site. The control sets of half CLB pairs should be compatible.
Parameters
CSPtr a given control set pointer
anotherHalfCLB the other one half CLB id in this half CLB pair
Returns
true if the control set can be placed in the given half CLB
false if the control set CANNOT be placed in the given half CLB
Definition at line 197 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by evictFFsFromCarryHalfCLB(), and evictFFsFromMuxHalfCLB().
compatibleInOneHalfCLB() [2/2]
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::compatibleInOneHalfCLB (int halfCLB, int anotherHalfCLB)
check whether a given half CLB can be placed with another given half CLB
Since in current architecture, FFs are packed in half CLBs in the site. The control sets of half CLB pairs should be compatible.
Parameters
halfCLB a given half CLB
anotherHalfCLB the other one half CLB id in this half CLB pair
Returns
true if the given half CLB can be placed with another given half CLB
false if the given half CLB CANNOT be placed with another given half CLB
Definition at line 220 of file ParallelCLBPacker_PackingCLBCluster.cc.
containFF()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::containFF (DesignInfo::DesignCell * curFF) inline
check whether the cluster contains a specific FF cell
Parameters
curFF a given FF cell
Returns
true if the cluster contains a specific FF cell
false if the cluster DOES NOT contain a specific FF cell
Definition at line 1559 of file ParallelCLBPacker.h.
contains()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::contains (PlacementInfo::PlacementUnit * tmpPU) inline
check whether the cluster contains a specific PlacementUnit
Parameters
tmpPU a given PlacementUnit
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 1015 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::updateConsistentPUsInTop().
evictFFsFromCarryHalfCLB()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::evictFFsFromCarryHalfCLB (unsigned int FFSetId) inline
try to move FFs in Mux slot to other controlSet
Definition at line 760 of file ParallelCLBPacker.h.
evictFFsFromMuxHalfCLB()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::evictFFsFromMuxHalfCLB () inline
try to move FFs in Mux slot to other controlSet
Definition at line 683 of file ParallelCLBPacker.h.
getCellSet()
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getCellSet () inline
Definition at line 1025 of file ParallelCLBPacker.h.
getFFControlSets()
const std::vector<PackedControlSet>& ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getFFControlSets () const inline
Definition at line 1123 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), ParallelCLBPacker::PackingCLBSite::compatibleInOneHalfCLB(), evictFFsFromCarryHalfCLB(), evictFFsFromMuxHalfCLB(), operator<<(), PackingCLBCluster(), and tryAddPU().
getHash()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getHash () inline
Get the hash code for this cluster.
Returns
int
Definition at line 1414 of file ParallelCLBPacker.h.
Referenced by clusterHashWithAdditionalPU(), ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs(), and ParallelCLBPacker::ripUpAndLegalizae().
getHashConst()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getHashConst () const inline
Get the hash code of this cluster without changing the class variables of this cluster.
Returns
int
Definition at line 1426 of file ParallelCLBPacker.h.
Referenced by operator<<().
getHPWLChange()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getHPWLChange () const inline
Get the HWPL change term in the cluster score object.
Returns
float
Definition at line 1475 of file ParallelCLBPacker.h.
Referenced by PackingCLBCluster().
getHPWLChangeForPU()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getHPWLChangeForPU (PlacementInfo::PlacementUnit * tmpPU) inline
get the HPWL change if a given PlacementUnit is moved to this site
Parameters
tmpPU a given PlacementUnit
Returns
float
Definition at line 1455 of file ParallelCLBPacker.h.
getId()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getId () const inline
Get the Id of the PackingCLBCluster (just for debug information don't use it in algorithm)
Returns
int
Definition at line 489 of file ParallelCLBPacker.h.
Referenced by operator<<(), and PackingCLBCluster().
getInternalPinsNum()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getInternalPinsNum (PlacementInfo::PlacementNet * curNet)
Get the number of pins within this site for a given net (more pins are located in ont site will reduce the demand of routing resource)
Parameters
curNet a given net
Returns
int
Definition at line 479 of file ParallelCLBPacker_PackingCLBCluster.cc.
getNumMuxes()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getNumMuxes () const inline
Get the total number of MUX cells in this cluster.
Returns
int
Definition at line 1505 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::checkIsMuxSite(), and PackingCLBCluster().
getPairedLUTs()
const std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *> >& ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPairedLUTs () const inline
Get the set of the paired LUTs.
Returns
const std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *>>&
Definition at line 1246 of file ParallelCLBPacker.h.
Referenced by operator<<(), PackingCLBCluster(), and tryAddPU().
getPairPinNum()
unsigned int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPairPinNum (DesignInfo::DesignCell * LUTA, DesignInfo::DesignCell * LUTB) inline
check how many input pins will be needed if the two LUTs are packed.
Parameters
LUTA
LUTB
Returns
unsigned int
Definition at line 510 of file ParallelCLBPacker.h.
Referenced by maxCardinalityMatching().
getParentPackingCLB()
PackingCLBSite* ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getParentPackingCLB () const inline
Get the Parent Packing CLB site of this cluster (this can be used to get more device information)
Returns
PackingCLBSite*
Definition at line 1330 of file ParallelCLBPacker.h.
Referenced by operator<<(), PackingCLBCluster(), and ParallelCLBPacker::ripUpAndLegalizae().
getPlacementUnitMaxPathLen()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathLen (PlacementInfo::PlacementUnit * curPU) inline
Get the max length of paths involving a given PlacementUnit.
(unused currently) during packing, we should consider timing factors and the critical path should be assigned top priority.
Parameters
curPU a given PlacementUnit
Returns
int
Definition at line 1607 of file ParallelCLBPacker.h.
getPlacementUnitMaxPathNegativeSlack()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathNegativeSlack (PlacementInfo::PlacementUnit * curPU) inline
Get the max length of paths involving a given PlacementUnit.
(unused currently) during packing, we should consider timing factors and the critical path should be assigned top priority.
Parameters
curPU a given PlacementUnit
Returns
float
Definition at line 1643 of file ParallelCLBPacker.h.
getPUs()
const std::set<PlacementInfo::PlacementUnit *, Packing_PUcompare>& ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPUs () const inline
Definition at line 1020 of file ParallelCLBPacker.h.
Referenced by operator<<(), ParallelCLBPacker::packCLBsIteration(), PackingCLBCluster(), ParallelCLBPacker::ripUpAndLegalizae(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ParallelCLBPacker::PackingCLBSite::updateConsistentPUsInTop().
getScoreInSite()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getScoreInSite () const inline
Get the score if this cluster is mapped the site.
Returns
float
Definition at line 1306 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::exceptionPULegalize(), operator<<(), PackingCLBCluster(), and ParallelCLBPacker::ripUpAndLegalizae().
getSingleLUTs()
const std::set<DesignInfo::DesignCell *>& ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getSingleLUTs () const inline
Get the set of single LUTs in this cluster (some other LUTs have been paired for packing)
Returns
const std::set<DesignInfo::DesignCell *>&
Definition at line 1133 of file ParallelCLBPacker.h.
Referenced by operator<<(), PackingCLBCluster(), and tryAddPU().
getSortedPairedLUTs()
std::vector<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *> > ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getSortedPairedLUTs () inline
Get the sorted list of the paired LUTs.
Returns
std::vector<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *>>&
Definition at line 1256 of file ParallelCLBPacker.h.
getSortedSingleLUTs()
std::vector<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getSortedSingleLUTs () inline
Get the sorted list of single LUTs in this cluster (some other LUTs have been paired for packing)
Returns
std::vector<DesignInfo::DesignCell *>&
Definition at line 1143 of file ParallelCLBPacker.h.
getTotalCellNum()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalCellNum () const inline
Get the total number of cells in this cluster.
Returns
int
Definition at line 1495 of file ParallelCLBPacker.h.
Referenced by PackingCLBCluster().
getTotalCellWeight()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalCellWeight () const inline
Get the total weights of cells in the cluster (each cell will have different weight in the placement)
Returns
float
Definition at line 1526 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::exceptionPULegalize().
getTotalConnectivityScore()
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalConnectivityScore () const inline
Get the connectivity term in the cluster score object.
Returns
float
Definition at line 1465 of file ParallelCLBPacker.h.
Referenced by PackingCLBCluster().
getTotalLen()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalLen () const inline
Get the maximum length of the paths which involve this cluster.
Returns
int
Definition at line 1515 of file ParallelCLBPacker.h.
Referenced by PackingCLBCluster().
getTotalNetNum()
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalNetNum () const inline
Get the total number of cells in this cluster.
Returns
int
Definition at line 1485 of file ParallelCLBPacker.h.
Referenced by PackingCLBCluster().
incrementalUpdateScoreInSite()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::incrementalUpdateScoreInSite (PlacementInfo::PlacementUnit * tmpPU)
incrementally update the score of this cluster by considering that only a given PlacementUnit will be added into this cluster
Parameters
tmpPU a given PlacementUnit
Definition at line 556 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs(), and ParallelCLBPacker::ripUpAndLegalizae().
isCarryMacro()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::isCarryMacro (DesignInfo::DesignCell * cell) inline
Definition at line 667 of file ParallelCLBPacker.h.
Referenced by evictFFsFromCarryHalfCLB().
isMuxMacro()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::isMuxMacro (DesignInfo::DesignCell * cell) inline
Definition at line 654 of file ParallelCLBPacker.h.
Referenced by evictFFsFromMuxHalfCLB().
isPUTypeCompatibleWithSiteType()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::isPUTypeCompatibleWithSiteType (PlacementInfo::PlacementUnit * tmpPU) inline
check whether the type of the given PlacementUnit is compatible with the site type
Parameters
tmpPU a given PlacementUnit
Returns
true the PU is compatible with the siet
false the PU is NOT compatible with the siet
Definition at line 931 of file ParallelCLBPacker.h.
maxCardinalityMatching()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::maxCardinalityMatching (bool verbose = false)
conduct maximun cardinality matching algorithm to pair LUTs
Parameters
verbose
Definition at line 16 of file ParallelCLBPacker_PackingCLBCluster.cc.
moveFFFromCS1ToCS0()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::moveFFFromCS1ToCS0 (DesignInfo::DesignCell * targetFF, int CSGroupId1, int CSGroupId0) inline
Definition at line 744 of file ParallelCLBPacker.h.
printMyself()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself ()
a API to print the information of cluster
Definition at line 1006 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry().
recoverFFControlSets()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::recoverFFControlSets () inline
Definition at line 1676 of file ParallelCLBPacker.h.
refreshId()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::refreshId () inline
refresh the Id of the PackingCLBCluster so we can know it is changed.
Definition at line 498 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs().
removeFF()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::removeFF (DesignInfo::DesignCell * curFF) inline
remove a specific FF from this candidate cluster
Parameters
curFF a given FF
Definition at line 856 of file ParallelCLBPacker.h.
Referenced by removePUToConstructDetCluster().
removeLUT()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::removeLUT (DesignInfo::DesignCell * curLUT) inline
remove a specific LUT from this candidate cluster
Parameters
curLUT a given LUT
Definition at line 826 of file ParallelCLBPacker.h.
Referenced by removePUToConstructDetCluster().
removePUToConstructDetCluster()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::removePUToConstructDetCluster (PlacementInfo::PlacementUnit * tmpPU) inline
remove some PlacementInfo::PlacementUnit from the cluster for later determined cluster construction of this site
Parameters
tmpPU a given PlacementInfo::PlacementUnit to be removed
Definition at line 881 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), and ParallelCLBPacker::timingDrivenDetailedPlacement_swap().
removeSingleLUT()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::removeSingleLUT (DesignInfo::DesignCell * tmpLUT) inline
remove a single LUT from the set of single LUTs in this cluster
Parameters
tmpLUT a given single LUT
Definition at line 1160 of file ParallelCLBPacker.h.
tryAddPU()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::tryAddPU (PlacementInfo::PlacementUnit * tmpPU) inline
without modifying the original cluster container, try to add a given PlacementUnit into this cluster
Parameters
tmpPU a given PlacementUnit
Returns
true if this attempt is successful
false if this attempt FAILED.
Definition at line 967 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::ripUpAndLegalizae().
tryRemoveLUTPairFromPairs()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::tryRemoveLUTPairFromPairs (DesignInfo::DesignCell * tmpLUTA, DesignInfo::DesignCell * tmpLUTB) inline
try to remove a pair of LUTs from the set of paired LUTs
Parameters
tmpLUTA a LUT in the pair
tmpLUTB another LUT in the pair
Returns
true if the given LUTs are found in the set of paired LUTs and can be removed
false if the given LUTs are NOT found in the set of paired LUTs
Definition at line 1221 of file ParallelCLBPacker.h.
tryRemoveSingleLUT()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::tryRemoveSingleLUT (DesignInfo::DesignCell * tmpLUT) inline
try to remove a single LUT from the single LUT set
Parameters
tmpLUT a given LUT
Returns
true if the given LUT is found in the cluster set and can be removed
false if the given LUT is NOT found in the cluster set
Definition at line 1173 of file ParallelCLBPacker.h.
tryRemoveSingleLUTFromPairs()
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::tryRemoveSingleLUTFromPairs (DesignInfo::DesignCell * tmpLUT) inline
try to remove a LUT from the set of paired LUTs
Parameters
tmpLUT a given LUT
Returns
true if the given LUT is found in the set of paired LUTs and can be removed
false if the given LUT is NOT found in the set of paired LUTs
Definition at line 1193 of file ParallelCLBPacker.h.
updateScoreInSite()
void ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::updateScoreInSite ()
update the score of this cluster by considering HPWL, interconnection density, timing and etc
Definition at line 503 of file ParallelCLBPacker_PackingCLBCluster.cc.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), ParallelCLBPacker::PackingCLBSite::addLUTRAMMacro(), ParallelCLBPacker::exceptionPULegalize(), and ParallelCLBPacker::ripUpAndLegalizae().
Member Data Documentation
FFControlSets
std::vector<PackedControlSet> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::FFControlSets private
the control set information for this cluster
please note that some of these LUT/FFs are belong to CARRY chain, which is not shown in PUs
Definition at line 1774 of file ParallelCLBPacker.h.
Referenced by containFF(), evictFFsFromCarryHalfCLB(), evictFFsFromMuxHalfCLB(), getCellSet(), getFFControlSets(), getTotalCellWeight(), moveFFFromCS1ToCS0(), PackingCLBCluster(), recoverFFControlSets(), removeFF(), and tryAddPU().
FFControlSets_backup
std::vector<PackedControlSet> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::FFControlSets_backup private
Definition at line 1775 of file ParallelCLBPacker.h.
Referenced by evictFFsFromCarryHalfCLB(), and recoverFFControlSets().
hashed
bool ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::hashed = false private
Definition at line 1713 of file ParallelCLBPacker.h.
Referenced by clusterHash(), getHash(), and removePUToConstructDetCluster().
hashId
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::hashId = -3654 private
a hash id to record the elements in this cluster
Some clusters have the same elements (hashid) but they might have different index due to the combination (packing) order. We can use this hash id to remove duplicate candidates.
Definition at line 1712 of file ParallelCLBPacker.h.
Referenced by clusterHash(), getHash(), and getHashConst().
HPWLChange
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::HPWLChange = 0 private
the HPWL term for the wirelength optimization
We want the packing will not significantly increase the HPWL
Definition at line 1737 of file ParallelCLBPacker.h.
Referenced by getHPWLChange(), and PackingCLBCluster().
HPWLWeight
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::HPWLWeight = 0.01 private
the configurable weight for the wirelength in the cluster score
Definition at line 1761 of file ParallelCLBPacker.h.
id
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::id = -1 private
the unique id for each cluster
Definition at line 1719 of file ParallelCLBPacker.h.
Referenced by getId().
MaxNum_ControlSet
const unsigned int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::MaxNum_ControlSet = 4 private
Definition at line 1682 of file ParallelCLBPacker.h.
MaxNum_FFinControlSet
const unsigned int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::MaxNum_FFinControlSet = 4 private
Definition at line 1683 of file ParallelCLBPacker.h.
MaxNum_LUTSite
const unsigned int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::MaxNum_LUTSite = 8 private
Definition at line 1684 of file ParallelCLBPacker.h.
numMuxes
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::numMuxes = 0 private
Definition at line 1685 of file ParallelCLBPacker.h.
Referenced by getNumMuxes(), PackingCLBCluster(), and removePUToConstructDetCluster().
pairedLUTs
std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *> > ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::pairedLUTs private
the paired LUTs in the cluster
Definition at line 1787 of file ParallelCLBPacker.h.
Referenced by getCellSet(), getPairedLUTs(), getSortedPairedLUTs(), getTotalCellWeight(), maxCardinalityMatching(), PackingCLBCluster(), removeLUT(), tryAddPU(), tryRemoveLUTPairFromPairs(), and tryRemoveSingleLUTFromPairs().
parentPackingCLB
PackingCLBSite* ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::parentPackingCLB = nullptr private
the paraent CLB site for this cluster
Definition at line 1691 of file ParallelCLBPacker.h.
Referenced by areAllPUsValidForThisSite(), clusterHash(), getCellSet(), getHPWLChangeForPU(), getParentPackingCLB(), getPlacementUnitMaxPathLen(), getPlacementUnitMaxPathNegativeSlack(), getTotalCellWeight(), isPUTypeCompatibleWithSiteType(), maxCardinalityMatching(), and PackingCLBCluster().
placementInfo
PlacementInfo* ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::placementInfo = nullptr private
the paraent CLB site for this cluster
Definition at line 1697 of file ParallelCLBPacker.h.
Referenced by areAllPUsValidForThisSite(), isCarryMacro(), isMuxMacro(), and PackingCLBCluster().
PUs
std::set<PlacementInfo::PlacementUnit *, Packing_PUcompare> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::PUs private
Definition at line 1720 of file ParallelCLBPacker.h.
Referenced by areAllPUsValidForThisSite(), clusterHash(), contains(), getCellSet(), getHashConst(), getPUs(), PackingCLBCluster(), removePUToConstructDetCluster(), and tryAddPU().
scoreInSite
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::scoreInSite = -100000000 private
the evaluation score of packing for this cluster
Definition at line 1703 of file ParallelCLBPacker.h.
Referenced by getScoreInSite(), and PackingCLBCluster().
singleLUTs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::singleLUTs private
the set of LUTs have not been paired with other LUTs in the clutser
Definition at line 1781 of file ParallelCLBPacker.h.
Referenced by getCellSet(), getSingleLUTs(), getSortedSingleLUTs(), getTotalCellWeight(), maxCardinalityMatching(), PackingCLBCluster(), removeLUT(), removeSingleLUT(), tryAddPU(), tryRemoveSingleLUT(), and tryRemoveSingleLUTFromPairs().
totalCellNum
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::totalCellNum = 0 private
Definition at line 1747 of file ParallelCLBPacker.h.
Referenced by getTotalCellNum(), and PackingCLBCluster().
totalConnectivityScore
float ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::totalConnectivityScore = 0 private
the connectivity score for this cluster
We want more nets become the internal nets inside the CLB sites so the number of nets between sites can be reduced.
Definition at line 1729 of file ParallelCLBPacker.h.
Referenced by getTotalConnectivityScore(), and PackingCLBCluster().
totalLen
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::totalLen = 0 private
the term of timing (paths) in the packing score
We will accumulate the max length of paths for each elements in the cluster
Definition at line 1755 of file ParallelCLBPacker.h.
Referenced by getTotalLen(), and PackingCLBCluster().
totalNetNum
int ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::totalNetNum = 0 private
the cell number term in the cluster score
We want the large PlacementUnits can have a relatively higher priority in packing since the high displacement of these elements might lead to bad routing.
Definition at line 1746 of file ParallelCLBPacker.h.
Referenced by getTotalNetNum(), and PackingCLBCluster().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/packing/ParallelCLBPacker.h
src/lib/HiFPlacer/placement/packing/ParallelCLBPacker_PackingCLBCluster.cc