AMF-Placer: PlacementInfo::PlacementNet Class Reference
PlacementInfo::PlacementNet Class Reference
Placement net, compared to design net, includes information related to placement.
#include <PlacementInfo.h>
Classes
struct _pinOffset
Public Types
typedef struct PlacementInfo::PlacementNet::_pinOffset pinOffset
Public Member Functions
PlacementNet (DesignInfo::DesignNet *designNet, int id, std::vector< PlacementUnit *> &cellId2PlacementUnitVec, PlacementInfo *placementInfo)
Construct a new Placement Net object.
~PlacementNet ()
std::vector< PlacementUnit * > & getUnits ()
Get the reference of the vector of PlacementUnits connected to the net The placement units in the vector might be duplicated because a net might connect to multiple pins of a unit.
std::vector< PlacementUnit * > & getDriverUnits ()
Get the reference of the vector of the driver units that drive the net.
std::vector< PlacementUnit * > & getUnitsBeDriven ()
Get the reference of the vector of the PlacementUnits driven by the net.
DesignInfo::DesignNet * getDesignNet ()
Get the Design Net object.
int getId ()
Get the Id of the net in current placement procedure.
std::vector< pinOffset > & getPinOffsetsInUnit ()
Get the Pin Offsets (x,y) of the Units object.
bool updateNetBounds (bool updateX, bool updateY)
update the bounding box of the net
float getHPWL (float y2xRatio)
get current HPWL of the net
float getNewHPWLByTrying (PlacementUnit *curPU, double targetPUX, double targetPUY, float y2xRatio) const
Get the New HPWL By Trying to move a PlacementUnit object.
void updateBound2BoundNetWeight (std::vector< Eigen::Triplet< float >> &objectiveMatrixTripletList, std::vector< float > &objectiveMatrixDiag, Eigen::VectorXd &objectiveVector, float generalWeight, float y2xRatio, bool updateX, bool updateY, bool checkClockRegion=false)
update the weights of 2-pin nets between PlacementUnits in this hyperedge(PlacementNet) according to Bound2Bound net model
void addPseudoNet_enhancePin2Pin (std::vector< Eigen::Triplet< float >> &objectiveMatrixTripletList, std::vector< float > &objectiveMatrixDiag, Eigen::VectorXd &objectiveVector, float generalWeight, float y2xRatio, bool updateX, bool updateY, int PUIdA, int PUIdB, int pinIdA_net, int pinIdB_net)
void drawNet (float generalWeight=1.0)
void addB2BNet (std::vector< Eigen::Triplet< float >> &objectiveMatrixTripletList, std::vector< float > &objectiveMatrixDiag, Eigen::VectorXd &objectiveVector, int puId0, int puId1, float pos0, float pos1, float pinOffset0, float pinOffset1, bool movable0, bool movable1, float w)
set weights of the terms in the quadratic problem
std::set< PlacementUnit * > & getPUSet ()
float getLeftPinX ()
float getRightPinX ()
float getTopPinY ()
float getBottomPinY ()
int getLeftPUId ()
int getRightPUId ()
int getTopPUId ()
int getBottomPUId ()
bool isGlobalClock ()
Private Attributes
DesignInfo::DesignNet * designNet = nullptr
std::vector< PlacementUnit * > unitsOfNetPins
std::vector< PlacementUnit * > unitsOfDriverPins
std::vector< PlacementUnit * > unitsOfPinsBeDriven
std::vector< pinOffset > pinOffsetsInUnit
std::set< PlacementUnit * > PUSet
int id
PlacementInfo * placementInfo = nullptr
float leftPUX
float rightPUX
float topPUY
float bottomPUY
float leftPinX
float rightPinX
float topPinY
float bottomPinY
unsigned int leftPuId
unsigned int rightPuId
unsigned int topPuId
unsigned int bottomPuId
unsigned int leftPinId_net
unsigned int rightPinId_net
unsigned int topPinId_net
unsigned int bottomPinId_net
float eps = 1e-5
float minDist = 1
Detailed Description
Placement net, compared to design net, includes information related to placement.
Placement net, compared to design net, includes information related to placement: HPWL bounding box, interconnection between placement units (unpacked/macro), APIs to check wirelength.
Please note that PlacementNet is HyperEdge, connecting to multiple pins.
Definition at line 1864 of file PlacementInfo.h.
Member Typedef Documentation
pinOffset
typedef struct PlacementInfo::PlacementNet::_pinOffset PlacementInfo::PlacementNet::pinOffset
Constructor & Destructor Documentation
PlacementNet()
PlacementInfo::PlacementNet::PlacementNet (DesignInfo::DesignNet * designNet, int id, std::vector< PlacementUnit *> & cellId2PlacementUnitVec, PlacementInfo * placementInfo) inline
Construct a new Placement Net object.
Parameters
designNet each PlacementNet is binded to design net.
id
cellId2PlacementUnitVec
Definition at line 1874 of file PlacementInfo.h.
~PlacementNet()
PlacementInfo::PlacementNet::~PlacementNet () inline
Definition at line 1914 of file PlacementInfo.h.
Member Function Documentation
addB2BNet()
void PlacementInfo::PlacementNet::addB2BNet (std::vector< Eigen::Triplet< float >> & objectiveMatrixTripletList, std::vector< float > & objectiveMatrixDiag, Eigen::VectorXd & objectiveVector, int puId0, int puId1, float pos0, float pos1, float pinOffset0, float pinOffset1, bool movable0, bool movable1, float w) inline
set weights of the terms in the quadratic problem
min_x 0.5 * x'Px + q'x s.t. l <= Ax <= u
Parameters
objectiveMatrixTripletList The non-Diag elements in matrix Q, stored in the vector of Eigen Triplet (i,j,val)
objectiveMatrixDiag The Diag elements in matrix Q, stored in a 1-D vector
objectiveVector The elements in the vector P
puId0 PlacementUnit 0's Id (might be invaid -1)
puId1 PlacementUnit 1's Id (might be invaid -1)
pos0 PlacementUnit 0's position on one of the dimensions
pos1 PlacementUnit 1's position on one of the dimensions
pinOffset0 The pin's offset in PlacementUnit 0
pinOffset1 The pin's offset in PlacementUnit 1
movable0 whether the object 0 is movable
movable1 whether the object 0 is movable
w the weight of the net
Definition at line 2341 of file PlacementInfo.h.
addPseudoNet_enhancePin2Pin()
void PlacementInfo::PlacementNet::addPseudoNet_enhancePin2Pin (std::vector< Eigen::Triplet< float >> & objectiveMatrixTripletList, std::vector< float > & objectiveMatrixDiag, Eigen::VectorXd & objectiveVector, float generalWeight, float y2xRatio, bool updateX, bool updateY, int PUIdA, int PUIdB, int pinIdA_net, int pinIdB_net) inline
Definition at line 2291 of file PlacementInfo.h.
drawNet()
void PlacementInfo::PlacementNet::drawNet (float generalWeight = 1.0)
Definition at line 742 of file PlacementInfo.cc.
getBottomPinY()
float PlacementInfo::PlacementNet::getBottomPinY () inline
Definition at line 2415 of file PlacementInfo.h.
getBottomPUId()
int PlacementInfo::PlacementNet::getBottomPUId () inline
Definition at line 2439 of file PlacementInfo.h.
getDesignNet()
DesignInfo::DesignNet* PlacementInfo::PlacementNet::getDesignNet () inline
Get the Design Net object.
Returns
DesignInfo::DesignNet*
Definition at line 1961 of file PlacementInfo.h.
getDriverUnits()
std::vector<PlacementUnit *>& PlacementInfo::PlacementNet::getDriverUnits () inline
Get the reference of the vector of the driver units that drive the net.
Returns
std::vector<PlacementUnit *>&
Definition at line 1941 of file PlacementInfo.h.
getHPWL()
float PlacementInfo::PlacementNet::getHPWL (float y2xRatio) inline
get current HPWL of the net
Parameters
y2xRatio a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
Returns
float
Definition at line 2064 of file PlacementInfo.h.
getId()
int PlacementInfo::PlacementNet::getId () inline
Get the Id of the net in current placement procedure.
Returns
int
Definition at line 1971 of file PlacementInfo.h.
Referenced by Packing_Netcompare::operator()().
getLeftPinX()
float PlacementInfo::PlacementNet::getLeftPinX () inline
Definition at line 2397 of file PlacementInfo.h.
getLeftPUId()
int PlacementInfo::PlacementNet::getLeftPUId () inline
Definition at line 2421 of file PlacementInfo.h.
getNewHPWLByTrying()
float PlacementInfo::PlacementNet::getNewHPWLByTrying (PlacementUnit * curPU, double targetPUX, double targetPUY, float y2xRatio) const inline
Get the New HPWL By Trying to move a PlacementUnit object.
For some procedures like legalization and packing, evaluate the wirelength change if the location of a PlacementUnit is changed.
Parameters
curPU the PlacementUnit to be moved
targetPUX
targetPUY
y2xRatio
Returns
float
Definition at line 2081 of file PlacementInfo.h.
getPinOffsetsInUnit()
std::vector<pinOffset>& PlacementInfo::PlacementNet::getPinOffsetsInUnit () inline
Get the Pin Offsets (x,y) of the Units object.
Returns
std::vector<pinOffset>&
Definition at line 1981 of file PlacementInfo.h.
getPUSet()
std::set<PlacementUnit *>& PlacementInfo::PlacementNet::getPUSet () inline
Definition at line 2392 of file PlacementInfo.h.
getRightPinX()
float PlacementInfo::PlacementNet::getRightPinX () inline
Definition at line 2403 of file PlacementInfo.h.
getRightPUId()
int PlacementInfo::PlacementNet::getRightPUId () inline
Definition at line 2427 of file PlacementInfo.h.
getTopPinY()
float PlacementInfo::PlacementNet::getTopPinY () inline
Definition at line 2409 of file PlacementInfo.h.
getTopPUId()
int PlacementInfo::PlacementNet::getTopPUId () inline
Definition at line 2433 of file PlacementInfo.h.
getUnits()
std::vector<PlacementUnit *>& PlacementInfo::PlacementNet::getUnits () inline
Get the reference of the vector of PlacementUnits connected to the net The placement units in the vector might be duplicated because a net might connect to multiple pins of a unit.
Returns
std::vector<PlacementUnit *>&
Definition at line 1931 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getInternalPinsNum(), and PlacementInfo::reloadNets().
getUnitsBeDriven()
std::vector<PlacementUnit *>& PlacementInfo::PlacementNet::getUnitsBeDriven () inline
Get the reference of the vector of the PlacementUnits driven by the net.
Returns
std::vector<PlacementUnit *>&
Definition at line 1951 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getInternalPinsNum().
isGlobalClock()
bool PlacementInfo::PlacementNet::isGlobalClock () inline
Definition at line 2445 of file PlacementInfo.h.
Referenced by PlacementInfo::reloadNets().
updateBound2BoundNetWeight()
void PlacementInfo::PlacementNet::updateBound2BoundNetWeight (std::vector< Eigen::Triplet< float >> & objectiveMatrixTripletList, std::vector< float > & objectiveMatrixDiag, Eigen::VectorXd & objectiveVector, float generalWeight, float y2xRatio, bool updateX, bool updateY, bool checkClockRegion = false) inline
update the weights of 2-pin nets between PlacementUnits in this hyperedge(PlacementNet) according to Bound2Bound net model
In the quadratic placement, the wirelength(HPWL) can be modeled into a quadratic equation based on Bound2Bound net model. The equation can be represented by matrix operation (XQX^T+PX)
Parameters
objectiveMatrixTripletList The non-Diag elements in matrix Q, stored in the vector of Eigen Triplet (i,j,val)
objectiveMatrixDiag The Diag elements in matrix Q, stored in a 1-D vector
objectiveVector The elements in the vector P
generalWeight a weight given from external setting
pseudoWeight pseudo net weight to constrain the movement of PlacementUnits from their locations in last optimization iteration
y2xRatio a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
updateX update the X-coordinate term in the quadratic problem
updateY update the X-coordinate term in the quadratic problem
Definition at line 2172 of file PlacementInfo.h.
updateNetBounds()
bool PlacementInfo::PlacementNet::updateNetBounds (bool updateX, bool updateY) inline
update the bounding box of the net
Parameters
updateX if true, update the bounding box of the net in X coordinate
updateY if true, update the bounding box of the net in Y coordinate
Returns
true if the pins of the net is not at the same location
false if all pins of the net is at the same location
Definition at line 1994 of file PlacementInfo.h.
Member Data Documentation
bottomPinId_net
unsigned int PlacementInfo::PlacementNet::bottomPinId_net private
Definition at line 2464 of file PlacementInfo.h.
bottomPinY
float PlacementInfo::PlacementNet::bottomPinY private
Definition at line 2462 of file PlacementInfo.h.
bottomPuId
unsigned int PlacementInfo::PlacementNet::bottomPuId private
Definition at line 2463 of file PlacementInfo.h.
bottomPUY
float PlacementInfo::PlacementNet::bottomPUY private
Definition at line 2461 of file PlacementInfo.h.
designNet
DesignInfo::DesignNet* PlacementInfo::PlacementNet::designNet = nullptr private
Definition at line 2452 of file PlacementInfo.h.
eps
float PlacementInfo::PlacementNet::eps = 1e-5 private
Definition at line 2465 of file PlacementInfo.h.
id
int PlacementInfo::PlacementNet::id private
Definition at line 2459 of file PlacementInfo.h.
leftPinId_net
unsigned int PlacementInfo::PlacementNet::leftPinId_net private
Definition at line 2464 of file PlacementInfo.h.
leftPinX
float PlacementInfo::PlacementNet::leftPinX private
Definition at line 2462 of file PlacementInfo.h.
leftPuId
unsigned int PlacementInfo::PlacementNet::leftPuId private
Definition at line 2463 of file PlacementInfo.h.
leftPUX
float PlacementInfo::PlacementNet::leftPUX private
Definition at line 2461 of file PlacementInfo.h.
minDist
float PlacementInfo::PlacementNet::minDist = 1 private
Definition at line 2466 of file PlacementInfo.h.
pinOffsetsInUnit
std::vector<pinOffset> PlacementInfo::PlacementNet::pinOffsetsInUnit private
Definition at line 2456 of file PlacementInfo.h.
placementInfo
PlacementInfo* PlacementInfo::PlacementNet::placementInfo = nullptr private
Definition at line 2460 of file PlacementInfo.h.
PUSet
std::set<PlacementUnit *> PlacementInfo::PlacementNet::PUSet private
Definition at line 2457 of file PlacementInfo.h.
rightPinId_net
unsigned int PlacementInfo::PlacementNet::rightPinId_net private
Definition at line 2464 of file PlacementInfo.h.
rightPinX
float PlacementInfo::PlacementNet::rightPinX private
Definition at line 2462 of file PlacementInfo.h.
rightPuId
unsigned int PlacementInfo::PlacementNet::rightPuId private
Definition at line 2463 of file PlacementInfo.h.
rightPUX
float PlacementInfo::PlacementNet::rightPUX private
Definition at line 2461 of file PlacementInfo.h.
topPinId_net
unsigned int PlacementInfo::PlacementNet::topPinId_net private
Definition at line 2464 of file PlacementInfo.h.
topPinY
float PlacementInfo::PlacementNet::topPinY private
Definition at line 2462 of file PlacementInfo.h.
topPuId
unsigned int PlacementInfo::PlacementNet::topPuId private
Definition at line 2463 of file PlacementInfo.h.
topPUY
float PlacementInfo::PlacementNet::topPUY private
Definition at line 2461 of file PlacementInfo.h.
unitsOfDriverPins
std::vector<PlacementUnit *> PlacementInfo::PlacementNet::unitsOfDriverPins private
Definition at line 2454 of file PlacementInfo.h.
unitsOfNetPins
std::vector<PlacementUnit *> PlacementInfo::PlacementNet::unitsOfNetPins private
Definition at line 2453 of file PlacementInfo.h.
unitsOfPinsBeDriven
std::vector<PlacementUnit *> PlacementInfo::PlacementNet::unitsOfPinsBeDriven private
Definition at line 2455 of file PlacementInfo.h.
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.cc