AMF-Placer: GeneralSpreader::SpreadRegion::SubBox Class Reference
GeneralSpreader::SpreadRegion::SubBox Class Reference
SubBox is the exact container which is the object for bi-partitioning-based cell spreading.
#include <GeneralSpreader.h>
Public Member Functions
SubBox (PlacementInfo *placementInfo, SpreadRegion *curRegion, std::vector< std::vector< PlacementInfo::PlacementBinInfo * > > &binGrid, float capacityShrinkRatio=1.0, int level=100, bool dirIsH=true)
Construct a new Sub Box object.
SubBox (SubBox *parentBox, int topBinY, int bottomBinY, int leftBinX, int rightBinX, int cellRangeBegin, int cellRangeEnd)
Construct a new Sub Box object.
~SubBox ()
void addCellId (int cellId)
void spreadAndPartition ()
spread cells and partition the SubBox into smaller SubBoxes
int Partition (std::vector< int > &cellIds, int low, int high, bool Xsort)
the partition/sort function for quick sorting by cell location (X or Y)
int RandomPivotPartition (std::vector< int > &cellIds, int low, int high, bool Xsort)
the partition/sort function for quick sorting by cell location (X or Y)
void quick_sort (std::vector< int > &cellIds, int p, int q, bool Xsort)
recursive implementation of quick sort for cell ids by X/Y location
int getLevel ()
void spreadCellsH (SubBox **boxA, SubBox **boxB)
split horizontally the SubBox into smaller ones and assign cells to them
void spreadCellsV (SubBox **boxA, SubBox **boxB)
split vertically the SubBox into smaller ones and assign cells to them
int top ()
get the top bin coordinate Y of the SubBox in bin grid
int bottom ()
get the bottom bin coordinate Y of the SubBox in bin grid
int left ()
get the left bin coordinate X of the SubBox in bin grid
int right ()
get the right bin coordinate X of the SubBox in bin grid
Public Attributes
PlacementInfo * placementInfo
std::vector< std::vector< PlacementInfo::PlacementBinInfo * > > & binGrid
float capacityShrinkRatio = 1.0
bool dirIsH
int minExpandSize = 2
the minimum length of boundary
Private Attributes
int topBinY
int bottomBinY
int leftBinX
int rightBinX
std::vector< int > cellIds
the cells in this SubBox
int level
Detailed Description
SubBox is the exact container which is the object for bi-partitioning-based cell spreading.
Each SubBox can be splited vertically or horizontally and cells can be assigned to the partitions accoringly if it is allowed.
Definition at line 806 of file GeneralSpreader.h.
Constructor & Destructor Documentation
SubBox() [1/2]
GeneralSpreader::SpreadRegion::SubBox::SubBox (PlacementInfo * placementInfo, SpreadRegion * curRegion, std::vector< std::vector< PlacementInfo::PlacementBinInfo * > > & binGrid, float capacityShrinkRatio = 1.0, int level = 100, bool dirIsH = true) inline
Construct a new Sub Box object.
Parameters
placementInfo PlacementInfo so this object can access the corresponding placement database
curRegion the parent SpreadRegion of this SubBox which guides the boundary setting of the subox
binGrid the bin grid which record the cell density distribution
capacityShrinkRatio shrink the area supply to a specific ratio
level current recursion level
dirIsH split vertically or horizontally (it is a priority setting instead of enforcement)
Definition at line 819 of file GeneralSpreader.h.
SubBox() [2/2]
GeneralSpreader::SpreadRegion::SubBox::SubBox (SubBox * parentBox, int topBinY, int bottomBinY, int leftBinX, int rightBinX, int cellRangeBegin, int cellRangeEnd) inline
Construct a new Sub Box object.
Parameters
parentBox inheret information from a parent SubBox
topBinY the top bin index
bottomBinY the bottom bin index
leftBinX the left bin index
rightBinX the right bin index
cellRangeBegin the range begin for copying the cell ids to this child SubBox
cellRangeEnd the range end for copying the cell ids to this child SubBox
Definition at line 854 of file GeneralSpreader.h.
~SubBox()
GeneralSpreader::SpreadRegion::SubBox::~SubBox () inline
Definition at line 867 of file GeneralSpreader.h.
Member Function Documentation
addCellId()
void GeneralSpreader::SpreadRegion::SubBox::addCellId (int cellId) inline
Definition at line 875 of file GeneralSpreader.h.
bottom()
int GeneralSpreader::SpreadRegion::SubBox::bottom () inline
get the bottom bin coordinate Y of the SubBox in bin grid
Returns
int
Definition at line 1013 of file GeneralSpreader.h.
Referenced by operator<<().
getLevel()
int GeneralSpreader::SpreadRegion::SubBox::getLevel () inline
Definition at line 977 of file GeneralSpreader.h.
left()
int GeneralSpreader::SpreadRegion::SubBox::left () inline
get the left bin coordinate X of the SubBox in bin grid
Returns
int
Definition at line 1023 of file GeneralSpreader.h.
Referenced by operator<<().
Partition()
int GeneralSpreader::SpreadRegion::SubBox::Partition (std::vector< int > & cellIds, int low, int high, bool Xsort) inline
the partition/sort function for quick sorting by cell location (X or Y)
Parameters
cellIds the cell ids for location sorting
low lower bound of sorting range
high upper bound of sorting range
Xsort sort by X loction or Y location
Returns
int
Definition at line 895 of file GeneralSpreader.h.
Referenced by RandomPivotPartition().
quick_sort()
void GeneralSpreader::SpreadRegion::SubBox::quick_sort (std::vector< int > & cellIds, int p, int q, bool Xsort) inline
recursive implementation of quick sort for cell ids by X/Y location
Parameters
cellIds the cell ids for location sorting
p lower bound of sorting range
q upper bound of sorting range
Xsort sort by X loction or Y location
Definition at line 964 of file GeneralSpreader.h.
Referenced by quick_sort().
RandomPivotPartition()
int GeneralSpreader::SpreadRegion::SubBox::RandomPivotPartition (std::vector< int > & cellIds, int low, int high, bool Xsort) inline
the partition/sort function for quick sorting by cell location (X or Y)
Parameters
cellIds the cell ids for location sorting
low lower bound of sorting range
high upper bound of sorting range
Xsort sort by X loction or Y location
Returns
int
Definition at line 946 of file GeneralSpreader.h.
Referenced by quick_sort().
right()
int GeneralSpreader::SpreadRegion::SubBox::right () inline
get the right bin coordinate X of the SubBox in bin grid
Returns
int
Definition at line 1033 of file GeneralSpreader.h.
Referenced by operator<<().
spreadAndPartition()
void GeneralSpreader::SpreadRegion::SubBox::spreadAndPartition ()
spread cells and partition the SubBox into smaller SubBoxes
Definition at line 659 of file GeneralSpreader.cc.
Referenced by spreadAndPartition(), and GeneralSpreader::spreadPlacementUnits().
spreadCellsH()
void GeneralSpreader::SpreadRegion::SubBox::spreadCellsH (SubBox ** boxA, SubBox ** boxB)
split horizontally the SubBox into smaller ones and assign cells to them
Parameters
boxA the obtained pointer of new smaller SubBox
boxB another obtained pointer of new smaller SubBox
Definition at line 705 of file GeneralSpreader.cc.
spreadCellsV()
void GeneralSpreader::SpreadRegion::SubBox::spreadCellsV (SubBox ** boxA, SubBox ** boxB)
split vertically the SubBox into smaller ones and assign cells to them
Parameters
boxA the obtained pointer of new smaller SubBox
boxB another obtained pointer of new smaller SubBox
Definition at line 933 of file GeneralSpreader.cc.
top()
int GeneralSpreader::SpreadRegion::SubBox::top () inline
get the top bin coordinate Y of the SubBox in bin grid
Returns
int
Definition at line 1003 of file GeneralSpreader.h.
Referenced by operator<<().
Member Data Documentation
binGrid
std::vector<std::vector<PlacementInfo::PlacementBinInfo *> >& GeneralSpreader::SpreadRegion::SubBox::binGrid
Definition at line 872 of file GeneralSpreader.h.
bottomBinY
int GeneralSpreader::SpreadRegion::SubBox::bottomBinY private
Definition at line 1039 of file GeneralSpreader.h.
Referenced by bottom().
capacityShrinkRatio
float GeneralSpreader::SpreadRegion::SubBox::capacityShrinkRatio = 1.0
Definition at line 873 of file GeneralSpreader.h.
cellIds
std::vector<int> GeneralSpreader::SpreadRegion::SubBox::cellIds private
the cells in this SubBox
Definition at line 1045 of file GeneralSpreader.h.
Referenced by addCellId(), Partition(), quick_sort(), RandomPivotPartition(), spreadCellsH(), spreadCellsV(), and SubBox().
dirIsH
bool GeneralSpreader::SpreadRegion::SubBox::dirIsH
Definition at line 1049 of file GeneralSpreader.h.
leftBinX
int GeneralSpreader::SpreadRegion::SubBox::leftBinX private
Definition at line 1039 of file GeneralSpreader.h.
Referenced by left().
level
int GeneralSpreader::SpreadRegion::SubBox::level private
Definition at line 1046 of file GeneralSpreader.h.
Referenced by getLevel().
minExpandSize
int GeneralSpreader::SpreadRegion::SubBox::minExpandSize = 2
the minimum length of boundary
Definition at line 1055 of file GeneralSpreader.h.
placementInfo
PlacementInfo* GeneralSpreader::SpreadRegion::SubBox::placementInfo
Definition at line 871 of file GeneralSpreader.h.
Referenced by Partition().
rightBinX
int GeneralSpreader::SpreadRegion::SubBox::rightBinX private
Definition at line 1039 of file GeneralSpreader.h.
Referenced by right().
topBinY
int GeneralSpreader::SpreadRegion::SubBox::topBinY private
Definition at line 1039 of file GeneralSpreader.h.
Referenced by top().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/globalPlacement/GeneralSpreader.h
src/lib/HiFPlacer/placement/globalPlacement/GeneralSpreader.cc