AMF-Placer: DesignInfo::DesignNet Class Reference
DesignInfo::DesignNet Class Reference
a design net (hyperedge) defined in the design, connecting to pins of cells
#include <DesignInfo.h>
Public Member Functions
DesignNet (std::string &name, int id, bool virtualNet=false)
Construct a new Design Net object.
~DesignNet ()
void connectToPinName (const std::string &_pinName)
bind the net to a pin by name
void connectToPinVariable (DesignPin *_pinPtr)
bind the net to a pin's pointer
std::vector< DesignPin * > & getDriverPins ()
Get the vector reference of the driver pins of the net.
std::vector< DesignPin * > & getPinsBeDriven ()
Get the vector reference of the pins driven by the net.
std::vector< DesignPin * > & getPins ()
Get the vector reference of the pins.
bool isVirtual ()
void enhance (int pinIdInNetA, int pinIdInNetB, float ratio)
placer can customize some 2-pin interconnections to make their weights enhanced during wirelength optimization
float getPinPairEnhanceRatio (int pinIdInNetA, int pinIdInNetB)
Get the Pin Pair Enhance Ratio (placer can customize some 2-pin interconnections to make their weights enhanced during wirelength optimization)
float getOverallEnhanceRatio ()
Get the Overall Enhance Ratio (the entire net can be enhanced to a pre-defined extent.)
void setOverallNetEnhancement (float r)
Set the Overall Net Enhancement (the entire net can be enhanced to a pre-defined extent.)
void enhanceOverallNetEnhancement (float r)
increase the Overall Net Enhancement (the entire net can be enhanced to a pre-defined extent.)
void resetEnhanceRatio ()
void setGlobalClock ()
Set the attribute isGlobalClock to be true.
bool checkIsGlobalClock ()
check the attribute isGlobalClock
bool checkIsPowerNet ()
check whether the net is VCC or GND
Public Member Functions inherited from DesignInfo::DesignElement
DesignElement (const std::string &name, DesignElement *parentPtr, DesignElementType type, int id)
DesignElement (const std::string &name, DesignElementType type, int id)
DesignElement (bool isVirtual, DesignElementType type, int id)
DesignElement (bool isVirtual, const std::string &_name, DesignElementType type, int id)
virtual ~DesignElement ()
const std::string & getName () const
DesignElement * getParentPtr ()
DesignElementType getElementType ()
int getElementIdInType ()
Private Attributes
std::vector< std::string > pinNames
std::vector< DesignPin * > pinPtrs
std::vector< DesignPin * > driverPinPtrs
std::vector< DesignPin * > BeDrivenPinPtrs
std::map< std::pair< int, int >, float > pinIdPinIdInNet2EnhanceRatio
float overallEnhanceRatio = 1.0
bool virtualNet
bool isGlobalClock = false
bool isPowerNet = false
Detailed Description
a design net (hyperedge) defined in the design, connecting to pins of cells
Definition at line 488 of file DesignInfo.h.
Constructor & Destructor Documentation
DesignNet()
DesignInfo::DesignNet::DesignNet (std::string & name, int id, bool virtualNet = false) inline
Construct a new Design Net object.
the DesignNet will only initilize with name and id. Later it will bind to pins and cells.
Parameters
name the name of the net
id the Id of the net
virtualNet is it a virtual net not defined in the design?
Definition at line 500 of file DesignInfo.h.
~DesignNet()
DesignInfo::DesignNet::~DesignNet () inline
Definition at line 510 of file DesignInfo.h.
Member Function Documentation
checkIsGlobalClock()
bool DesignInfo::DesignNet::checkIsGlobalClock () inline
check the attribute isGlobalClock
Returns
true if the net is a global clock (which could CLK, SR, or CE signal)
false if the net is not a global clock
Definition at line 658 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementNet::isGlobalClock().
checkIsPowerNet()
bool DesignInfo::DesignNet::checkIsPowerNet () inline
check whether the net is VCC or GND
Returns
true if the net is VCC or GND
false if the net is NOT VCC or GND
Definition at line 669 of file DesignInfo.h.
connectToPinName()
void DesignInfo::DesignNet::connectToPinName (const std::string & _pinName)
bind the net to a pin by name
Parameters
_pinName
Definition at line 67 of file DesignInfo.cc.
Referenced by DesignInfo::addPinToNet().
connectToPinVariable()
void DesignInfo::DesignNet::connectToPinVariable (DesignPin * _pinPtr)
bind the net to a pin's pointer
be aware that the net could bind to multiple pins
Parameters
_pinPtr
Definition at line 72 of file DesignInfo.cc.
Referenced by DesignInfo::addPinToNet().
enhance()
void DesignInfo::DesignNet::enhance (int pinIdInNetA, int pinIdInNetB, float ratio) inline
placer can customize some 2-pin interconnections to make their weights enhanced during wirelength optimization
Parameters
pinIdInNetA pin A's id in the pin list of the net
pinIdInNetB pin B's id in the pin list of the net
ratio enhance the weight to what extent
Definition at line 572 of file DesignInfo.h.
enhanceOverallNetEnhancement()
void DesignInfo::DesignNet::enhanceOverallNetEnhancement (float r) inline
increase the Overall Net Enhancement (the entire net can be enhanced to a pre-defined extent.)
Parameters
r
Definition at line 631 of file DesignInfo.h.
getDriverPins()
std::vector< DesignPin * > & DesignInfo::DesignNet::getDriverPins () inline
Get the vector reference of the driver pins of the net.
Returns
std::vector<DesignPin *>&
Definition at line 534 of file DesignInfo.h.
getOverallEnhanceRatio()
float DesignInfo::DesignNet::getOverallEnhanceRatio () inline
Get the Overall Enhance Ratio (the entire net can be enhanced to a pre-defined extent.)
Returns
float
Definition at line 611 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementNet::updateBound2BoundNetWeight().
getPinPairEnhanceRatio()
float DesignInfo::DesignNet::getPinPairEnhanceRatio (int pinIdInNetA, int pinIdInNetB) inline
Get the Pin Pair Enhance Ratio (placer can customize some 2-pin interconnections to make their weights enhanced during wirelength optimization)
Parameters
pinIdInNetA pin A's id in the pin list of the net
pinIdInNetB pin B's id in the pin list of the net
Returns
float
Definition at line 593 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementNet::updateBound2BoundNetWeight().
getPins()
std::vector< DesignPin * > & DesignInfo::DesignNet::getPins () inline
Get the vector reference of the pins.
Returns
std::vector<DesignPin *>&
Definition at line 554 of file DesignInfo.h.
Referenced by DesignInfo::loadUserDefinedClusterNets(), and PlacementInfo::PlacementNet::PlacementNet().
getPinsBeDriven()
std::vector< DesignPin * > & DesignInfo::DesignNet::getPinsBeDriven () inline
Get the vector reference of the pins driven by the net.
Returns
std::vector<DesignPin *>&
Definition at line 544 of file DesignInfo.h.
Referenced by InitialPacker::findCARRYMacros(), ParallelCLBPacker::PackingCLBSite::mapCarryRelatedCellsToSlots(), and InitialPacker::mapCarryRelatedRouteThru().
isVirtual()
bool DesignInfo::DesignNet::isVirtual () inline
Definition at line 559 of file DesignInfo.h.
resetEnhanceRatio()
void DesignInfo::DesignNet::resetEnhanceRatio () inline
Definition at line 636 of file DesignInfo.h.
setGlobalClock()
void DesignInfo::DesignNet::setGlobalClock () inline
Set the attribute isGlobalClock to be true.
if the net is a global clock (which could CLK, SR, or CE signal)
Definition at line 647 of file DesignInfo.h.
setOverallNetEnhancement()
void DesignInfo::DesignNet::setOverallNetEnhancement (float r) inline
Set the Overall Net Enhancement (the entire net can be enhanced to a pre-defined extent.)
Parameters
r
Definition at line 621 of file DesignInfo.h.
Member Data Documentation
BeDrivenPinPtrs
std::vector<DesignPin *> DesignInfo::DesignNet::BeDrivenPinPtrs private
Definition at line 678 of file DesignInfo.h.
Referenced by getPinsBeDriven().
driverPinPtrs
std::vector<DesignPin *> DesignInfo::DesignNet::driverPinPtrs private
Definition at line 677 of file DesignInfo.h.
Referenced by getDriverPins().
isGlobalClock
bool DesignInfo::DesignNet::isGlobalClock = false private
Definition at line 682 of file DesignInfo.h.
Referenced by checkIsGlobalClock(), and setGlobalClock().
isPowerNet
bool DesignInfo::DesignNet::isPowerNet = false private
Definition at line 683 of file DesignInfo.h.
Referenced by checkIsPowerNet(), and DesignNet().
overallEnhanceRatio
float DesignInfo::DesignNet::overallEnhanceRatio = 1.0 private
Definition at line 680 of file DesignInfo.h.
Referenced by DesignNet(), enhanceOverallNetEnhancement(), getOverallEnhanceRatio(), and setOverallNetEnhancement().
pinIdPinIdInNet2EnhanceRatio
std::map<std::pair<int, int>, float> DesignInfo::DesignNet::pinIdPinIdInNet2EnhanceRatio private
Definition at line 679 of file DesignInfo.h.
Referenced by enhance(), getPinPairEnhanceRatio(), and resetEnhanceRatio().
pinNames
std::vector<std::string> DesignInfo::DesignNet::pinNames private
Definition at line 675 of file DesignInfo.h.
pinPtrs
std::vector<DesignPin *> DesignInfo::DesignNet::pinPtrs private
Definition at line 676 of file DesignInfo.h.
Referenced by getPins().
virtualNet
bool DesignInfo::DesignNet::virtualNet private
Definition at line 681 of file DesignInfo.h.
Referenced by isVirtual().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/designInfo/DesignInfo.h
src/lib/HiFPlacer/designInfo/DesignInfo.cc