AMF-Placer: PlacementInfo::PlacementMacro Class Reference
PlacementInfo::PlacementMacro Class Reference
a fixed group of multiple standard cells with constraints of their relative locations
#include <PlacementInfo.h>
Classes
struct _fixedPlacementInfo_inMacro
some constaints of elements' relative locations are defined by the design. We need to record this.
Public Types
enum PlacementMacroType {
PlacementMacroType_LUTFFPair = 0, PlacementMacroType_LUTLUTSeires, PlacementMacroType_FFFFPair, PlacementMacroType_HALFCLB,
PlacementMacroType_LCLB, PlacementMacroType_MCLB, PlacementMacroType_CARRY, PlacementMacroType_DSP,
PlacementMacroType_BRAM, PlacementMacroType_MUX7, PlacementMacroType_MUX8, PlacementMacroType_MUX9
}
typedef struct PlacementInfo::PlacementMacro::_fixedPlacementInfo_inMacro fixedPlacementInfo_inMacro
some constaints of elements' relative locations are defined by the design. We need to record this.
Public Member Functions
PlacementMacro (std::string name, int id, PlacementMacroType macroType)
~PlacementMacro ()
bool hasCell (DesignInfo::DesignCell *curCell)
void addCell (DesignInfo::DesignCell *curCell, DesignInfo::DesignCellType cellType, float x, float y)
add a real cell into the macro with its offsets in the macro
DesignInfo::DesignCell * addVirtualCell (std::string virtualCellName, DesignInfo *designInfo, DesignInfo::DesignCellType cellType, float x, float y)
add a virtual cell with a given name into the macro with its offsets in the macro. Usually it is to occupy routing resource in a site.
void addVirtualCell (DesignInfo *designInfo, DesignInfo::DesignCellType cellType, float x, float y)
add a virtual cell without given name into the macro with its offsets in the macro. Usually it is to occupy routing resource in a site.
std::vector< DesignInfo::DesignCell * > & getCells ()
void addFixedCellInfo (DesignInfo::DesignCell *cell, std::string siteName, std::string BELName)
add information of a fixed cell
float getCellOffsetXInMacro (DesignInfo::DesignCell *cell)
float getCellOffsetYInMacro (DesignInfo::DesignCell *cell)
void getVirtualCellInfo (int vId, float &x, float &y, DesignInfo::DesignCellType &cellType)
Get the virtual cell information, including offsets and cell type.
DesignInfo::DesignCellType getVirtualCellType (int vId)
int getNumOfCells ()
DesignInfo::DesignCell * getCell (unsigned int id)
float getTopOffset ()
float getBottomOffset ()
float getLeftOffset ()
float getRightOffset ()
void addOccupiedSite (float siteOffset, float occ)
for site-level cell spreading
bool isCellInMacro (DesignInfo::DesignCell *curCell)
PlacementMacroType getMacroType ()
std::vector< fixedPlacementInfo_inMacro > & getFixedCellInfoVec ()
Public Member Functions inherited from PlacementInfo::PlacementUnit
PlacementUnit (std::string name, int id, PlacementUnitType unitType)
virtual ~PlacementUnit ()
void getAnchorLocation (float &x, float &y)
float X ()
float Y ()
float lastX ()
float lastY ()
void setAnchorLocation (float x, float y)
Set the Anchor Location for the PlacementUnit.
void setSpreadLocation (float x, float y, float forgetRatio)
Set the Spread Location based on forgetting ratio.
void setSpreadLocation_WithLimitDisplacement (float x, float y, float forgetRatio, float limitDisplacement)
Set the Spread Location based on forgetting ratio.
void setAnchorLocationAndForgetTheOriginalOne (float x, float y)
void recordSpreadLocatin ()
void setFixed ()
void setUnfixed ()
void setLocked ()
void setUnlocked ()
bool isLocked ()
void setPlaced ()
bool isFixed ()
bool isPlaced ()
std::string & getName ()
PlacementUnitType getType ()
void setWeight (int numCell)
int getWeight ()
unsigned int getId ()
void renewId (int newId)
void setNetsSetPtr (std::vector< PlacementNet * > *_nets)
Set the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
std::vector< PlacementNet * > * getNetsSetPtr ()
Get the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
int getUnitsBeDrivenByThisPU ()
int getUnitsDriveThisPU ()
void addDSP ()
void addBRAM ()
void addLUTRAM ()
void addLUT ()
void addFF ()
void addCARRY ()
void addMUX ()
bool checkHasDSP ()
bool checkHasBRAM ()
bool checkHasLUTRAM ()
bool checkHasLUT ()
bool checkHasFF ()
bool checkHasCARRY ()
bool checkHasMUX ()
bool hasRegister ()
bool hasLogic ()
bool isMCLB ()
bool isLCLB ()
int getDSPNum ()
int getBRAMNum ()
int getLUTRAMNum ()
int getLUTNum ()
int getCARRYNum ()
int getMUXNum ()
void setPacked ()
void resetPacked ()
bool isPacked ()
std::set< DesignInfo::DesignNet * > & getClockNets ()
Private Attributes
std::set< DesignInfo::DesignCell * > cellSet
std::map< DesignInfo::DesignCell *, int > cell2IdInMacro
std::vector< DesignInfo::DesignCell * > cellsInMacro
std::vector< DesignInfo::DesignCellType > cells_Type
std::vector< float > offsetX
std::vector< float > offsetY
std::vector< fixedPlacementInfo_inMacro > fixedCells
float left
float right
float top
float bottom
PlacementMacroType macroType
Additional Inherited Members
Protected Attributes inherited from PlacementInfo::PlacementUnit
std::set< DesignInfo::DesignNet * > clockNets
record the clock nets connected to this PlacementUnit
Detailed Description
a fixed group of multiple standard cells with constraints of their relative locations
Definition at line 1513 of file PlacementInfo.h.
Member Typedef Documentation
fixedPlacementInfo_inMacro
typedef struct PlacementInfo::PlacementMacro::_fixedPlacementInfo_inMacro PlacementInfo::PlacementMacro::fixedPlacementInfo_inMacro
some constaints of elements' relative locations are defined by the design. We need to record this.
Member Enumeration Documentation
PlacementMacroType
enum PlacementInfo::PlacementMacro::PlacementMacroType
Enumerator
PlacementMacroType_LUTFFPair
PlacementMacroType_LUTLUTSeires
PlacementMacroType_FFFFPair
PlacementMacroType_HALFCLB
PlacementMacroType_LCLB
PlacementMacroType_MCLB
PlacementMacroType_CARRY
PlacementMacroType_DSP
PlacementMacroType_BRAM
PlacementMacroType_MUX7
PlacementMacroType_MUX8
PlacementMacroType_MUX9
Definition at line 1516 of file PlacementInfo.h.
Constructor & Destructor Documentation
PlacementMacro()
PlacementInfo::PlacementMacro::PlacementMacro (std::string name, int id, PlacementMacroType macroType) inline
Definition at line 1534 of file PlacementInfo.h.
~PlacementMacro()
PlacementInfo::PlacementMacro::~PlacementMacro () inline
Definition at line 1547 of file PlacementInfo.h.
Member Function Documentation
addCell()
void PlacementInfo::PlacementMacro::addCell (DesignInfo::DesignCell * curCell, DesignInfo::DesignCellType cellType, float x, float y) inline
add a real cell into the macro with its offsets in the macro
Parameters
curCell
cellType update the cell's "virtual" cell type so it can occupy specific resource (e.g., make an LUT1 an LUT6)
x
y
Definition at line 1565 of file PlacementInfo.h.
Referenced by IncrementalBELPacker::FFPairing(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findLUTRAMMacros(), InitialPacker::findMuxMacros(), InitialPacker::loadOtherCLBMacros(), PlacementInfo::loadPlacementUnitInformation(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::LUTFFPairing(), and ParallelCLBPacker::updatePackedMacro().
addFixedCellInfo()
void PlacementInfo::PlacementMacro::addFixedCellInfo (DesignInfo::DesignCell * cell, std::string siteName, std::string BELName) inline
add information of a fixed cell
Parameters
cell
siteName
BELName
Definition at line 1740 of file PlacementInfo.h.
Referenced by InitialPacker::loadOtherCLBMacros(), and PlacementInfo::loadPlacementUnitInformation().
addOccupiedSite()
void PlacementInfo::PlacementMacro::addOccupiedSite (float siteOffset, float occ) inline
for site-level cell spreading
not used in current implmementation.
Parameters
siteOffset
occ
Definition at line 1816 of file PlacementInfo.h.
Referenced by IncrementalBELPacker::FFPairing(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findLUTRAMMacros(), InitialPacker::findMuxMacros(), InitialPacker::loadOtherCLBMacros(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::LUTFFPairing(), and ParallelCLBPacker::updatePackedMacro().
addVirtualCell() [1/2]
void PlacementInfo::PlacementMacro::addVirtualCell (DesignInfo * designInfo, DesignInfo::DesignCellType cellType, float x, float y) inline
add a virtual cell without given name into the macro with its offsets in the macro. Usually it is to occupy routing resource in a site.
Parameters
designInfo since we are creating virtual cell, it should be added into design information
cellType the type of the virtual cell type
x
y
Definition at line 1674 of file PlacementInfo.h.
addVirtualCell() [2/2]
DesignInfo::DesignCell* PlacementInfo::PlacementMacro::addVirtualCell (std::string virtualCellName, DesignInfo * designInfo, DesignInfo::DesignCellType cellType, float x, float y) inline
add a virtual cell with a given name into the macro with its offsets in the macro. Usually it is to occupy routing resource in a site.
Parameters
virtualCellName the name of the virtual cell to be added into the design
designInfo since we are creating virtual cell, it should be added into design information
cellType the type of the virtual cell type
x
y
Returns
DesignInfo::DesignCell*
Definition at line 1623 of file PlacementInfo.h.
Referenced by InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findMuxMacros(), and InitialPacker::mapCarryRelatedRouteThru().
getBottomOffset()
float PlacementInfo::PlacementMacro::getBottomOffset () inline
Definition at line 1795 of file PlacementInfo.h.
Referenced by operator<<().
getCell()
DesignInfo::DesignCell* PlacementInfo::PlacementMacro::getCell (unsigned int id) inline
Definition at line 1785 of file PlacementInfo.h.
getCellOffsetXInMacro()
float PlacementInfo::PlacementMacro::getCellOffsetXInMacro (DesignInfo::DesignCell * cell) inline
Definition at line 1745 of file PlacementInfo.h.
Referenced by operator<<(), and PlacementInfo::PlacementNet::PlacementNet().
getCellOffsetYInMacro()
float PlacementInfo::PlacementMacro::getCellOffsetYInMacro (DesignInfo::DesignCell * cell) inline
Definition at line 1751 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::mapCarryRelatedCellsToSlots(), InitialPacker::mapCarryRelatedRouteThru(), operator<<(), and PlacementInfo::PlacementNet::PlacementNet().
getCells()
std::vector<DesignInfo::DesignCell *>& PlacementInfo::PlacementMacro::getCells () inline
Definition at line 1713 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findMuxMacros(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getCellSet(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), InitialPacker::loadOtherCLBMacros(), InitialPacker::mapCarryRelatedRouteThru(), ParallelCLBPacker::PackingCLBSite::mapMuxF7Macro(), ParallelCLBPacker::PackingCLBSite::mapMuxF8Macro(), operator<<(), and ParallelCLBPacker::updatePackedMacro().
getFixedCellInfoVec()
std::vector<fixedPlacementInfo_inMacro>& PlacementInfo::PlacementMacro::getFixedCellInfoVec () inline
Definition at line 1835 of file PlacementInfo.h.
Referenced by operator<<().
getLeftOffset()
float PlacementInfo::PlacementMacro::getLeftOffset () inline
Definition at line 1799 of file PlacementInfo.h.
Referenced by operator<<().
getMacroType()
PlacementMacroType PlacementInfo::PlacementMacro::getMacroType () inline
Definition at line 1830 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), operator<<(), and ParallelCLBPacker::prePackLegalizedMacros().
getNumOfCells()
int PlacementInfo::PlacementMacro::getNumOfCells () inline
Definition at line 1780 of file PlacementInfo.h.
getRightOffset()
float PlacementInfo::PlacementMacro::getRightOffset () inline
Definition at line 1803 of file PlacementInfo.h.
Referenced by operator<<().
getTopOffset()
float PlacementInfo::PlacementMacro::getTopOffset () inline
Definition at line 1791 of file PlacementInfo.h.
Referenced by operator<<().
getVirtualCellInfo()
void PlacementInfo::PlacementMacro::getVirtualCellInfo (int vId, float & x, float & y, DesignInfo::DesignCellType & cellType) inline
Get the virtual cell information, including offsets and cell type.
Parameters
vId
x
y
cellType
Definition at line 1768 of file PlacementInfo.h.
getVirtualCellType()
DesignInfo::DesignCellType PlacementInfo::PlacementMacro::getVirtualCellType (int vId) inline
Definition at line 1775 of file PlacementInfo.h.
Referenced by operator<<().
hasCell()
bool PlacementInfo::PlacementMacro::hasCell (DesignInfo::DesignCell * curCell) inline
Definition at line 1551 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::findMuxFromHalfCLB(), InitialPacker::mapCarryRelatedRouteThru(), ParallelCLBPacker::PackingCLBSite::mapMuxF7Macro(), and ParallelCLBPacker::PackingCLBSite::mapMuxF8Macro().
isCellInMacro()
bool PlacementInfo::PlacementMacro::isCellInMacro (DesignInfo::DesignCell * curCell) inline
Definition at line 1825 of file PlacementInfo.h.
Member Data Documentation
bottom
float PlacementInfo::PlacementMacro::bottom private
Definition at line 1852 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getBottomOffset(), and PlacementMacro().
cell2IdInMacro
std::map<DesignInfo::DesignCell *, int> PlacementInfo::PlacementMacro::cell2IdInMacro private
Definition at line 1844 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getCellOffsetXInMacro(), getCellOffsetYInMacro(), and PlacementMacro().
cells_Type
std::vector<DesignInfo::DesignCellType> PlacementInfo::PlacementMacro::cells_Type private
Definition at line 1847 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getNumOfCells(), getVirtualCellInfo(), and getVirtualCellType().
cellSet
std::set<DesignInfo::DesignCell *> PlacementInfo::PlacementMacro::cellSet private
Definition at line 1843 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), hasCell(), isCellInMacro(), and PlacementMacro().
cellsInMacro
std::vector<DesignInfo::DesignCell *> PlacementInfo::PlacementMacro::cellsInMacro private
Definition at line 1845 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getCell(), getCells(), and PlacementMacro().
fixedCells
std::vector<fixedPlacementInfo_inMacro> PlacementInfo::PlacementMacro::fixedCells private
Definition at line 1850 of file PlacementInfo.h.
Referenced by addFixedCellInfo(), getFixedCellInfoVec(), and PlacementMacro().
left
float PlacementInfo::PlacementMacro::left private
Definition at line 1852 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getLeftOffset(), and PlacementMacro().
macroType
PlacementMacroType PlacementInfo::PlacementMacro::macroType private
Definition at line 1853 of file PlacementInfo.h.
Referenced by getMacroType().
offsetX
std::vector<float> PlacementInfo::PlacementMacro::offsetX private
Definition at line 1849 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getCellOffsetXInMacro(), and getVirtualCellInfo().
offsetY
std::vector<float> PlacementInfo::PlacementMacro::offsetY private
Definition at line 1849 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getCellOffsetYInMacro(), and getVirtualCellInfo().
right
float PlacementInfo::PlacementMacro::right private
Definition at line 1852 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getRightOffset(), and PlacementMacro().
top
float PlacementInfo::PlacementMacro::top private
Definition at line 1852 of file PlacementInfo.h.
Referenced by addCell(), addVirtualCell(), getTopOffset(), and PlacementMacro().
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h