AMF-Placer: DesignInfo::DesignElement Class Reference
DesignInfo::DesignElement Class Reference
basic class of element in a design.
#include <DesignInfo.h>
Public Member Functions
DesignElement (const std::string &name, DesignElement *parentPtr, DesignElementType type, int id)
DesignElement (const std::string &name, DesignElementType type, int id)
DesignElement (bool isVirtual, DesignElementType type, int id)
DesignElement (bool isVirtual, const std::string &_name, DesignElementType type, int id)
virtual ~DesignElement ()
const std::string & getName () const
DesignElement * getParentPtr ()
DesignElementType getElementType ()
int getElementIdInType ()
Private Attributes
std::string name
DesignElement * parentPtr = nullptr
DesignElementType type
int id
Detailed Description
basic class of element in a design.
includes the name, id and parent of an element.
Definition at line 214 of file DesignInfo.h.
Constructor & Destructor Documentation
DesignElement() [1/4]
DesignInfo::DesignElement::DesignElement (const std::string & name, DesignElement * parentPtr, DesignElementType type, int id) inline
Definition at line 217 of file DesignInfo.h.
DesignElement() [2/4]
DesignInfo::DesignElement::DesignElement (const std::string & name, DesignElementType type, int id) inline
Definition at line 222 of file DesignInfo.h.
DesignElement() [3/4]
DesignInfo::DesignElement::DesignElement (bool isVirtual, DesignElementType type, int id) inline
Definition at line 226 of file DesignInfo.h.
DesignElement() [4/4]
DesignInfo::DesignElement::DesignElement (bool isVirtual, const std::string & _name, DesignElementType type, int id) inline
Definition at line 232 of file DesignInfo.h.
~DesignElement()
virtual DesignInfo::DesignElement::~DesignElement () inline virtual
Definition at line 239 of file DesignInfo.h.
Member Function Documentation
getElementIdInType()
int DesignInfo::DesignElement::getElementIdInType () inline
Definition at line 255 of file DesignInfo.h.
Referenced by InitialPacker::findMuxMacros(), and DesignInfo::DesignCell::getCellId().
getElementType()
DesignElementType DesignInfo::DesignElement::getElementType () inline
Definition at line 251 of file DesignInfo.h.
getName()
const std::string& DesignInfo::DesignElement::getName () const inline
Definition at line 243 of file DesignInfo.h.
Referenced by DesignInfo::addCell(), DesignInfo::DesignCell::addNetForPin(), DesignInfo::DesignCell::addPin(), DesignInfo::addPinToNet(), DesignInfo::ControlSetInfo::display(), GlobalPlacer::dumpAllCellsCoordinate(), ParallelCLBPacker::dumpAllCellsCoordinate(), GlobalPlacer::dumpBRAMCoordinate(), GlobalPlacer::dumpCARRYCoordinate(), ParallelCLBPacker::dumpCLBPlacementTcl(), GlobalPlacer::dumpDSPCoordinate(), GlobalPlacer::dumpFFCoordinate(), GlobalPlacer::dumpLUTCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), InitialPacker::findMuxMacros(), IncrementalBELPacker::LUTFFPairing(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), InitialPacker::mapCarryRelatedRouteThru(), and operator<<().
getParentPtr()
DesignElement* DesignInfo::DesignElement::getParentPtr () inline
Definition at line 247 of file DesignInfo.h.
Referenced by DesignInfo::DesignPin::getCell().
Member Data Documentation
id
int DesignInfo::DesignElement::id private
Definition at line 264 of file DesignInfo.h.
Referenced by getElementIdInType().
name
std::string DesignInfo::DesignElement::name private
Definition at line 261 of file DesignInfo.h.
Referenced by DesignElement(), DesignInfo::DesignNet::DesignNet(), and getName().
parentPtr
DesignElement* DesignInfo::DesignElement::parentPtr = nullptr private
Definition at line 262 of file DesignInfo.h.
Referenced by getParentPtr().
type
DesignElementType DesignInfo::DesignElement::type private
Definition at line 263 of file DesignInfo.h.
Referenced by getElementType().
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/designInfo/DesignInfo.h