AMF-Placer: DeviceInfo::DeviceTile Class Reference
DeviceInfo::DeviceTile Class Reference
A tile is a combination of sites.
#include <DeviceInfo.h>
Public Member Functions
DeviceTile (std::string &name, std::string &tileType, DeviceInfo *device, int id)
Construct a new Device Tile object.
~DeviceTile ()
void addChildSite (DeviceElement *sitePtr)
std::vector< DeviceSite * > & getChildrenSites ()
std::string & getTileType ()
int getTileIdX ()
int getTileIdY ()
Public Member Functions inherited from DeviceInfo::DeviceElement
DeviceElement (std::string &name, DeviceElement *parentPtr, DeviceElementType type, int id)
DeviceElement (std::string &name, DeviceElementType type, int id)
virtual ~DeviceElement ()
std::string & getName ()
DeviceElement * getParentPtr ()
DeviceElementType getElementType ()
int getElementIdInParent ()
Private Attributes
std::string tileType
std::vector< DeviceSite * > childrenSites
DeviceInfo * device
int tileIdX = -1
int tileIdY = -1
Detailed Description
A tile is a combination of sites.
Definition at line 403 of file DeviceInfo.h.
Constructor & Destructor Documentation
DeviceTile()
DeviceInfo::DeviceTile::DeviceTile (std::string & name, std::string & tileType, DeviceInfo * device, int id) inline
Construct a new Device Tile object.
Parameters
name the tile name in the input file
tileType a string indicating the type of the tile
device
id
Definition at line 414 of file DeviceInfo.h.
~DeviceTile()
DeviceInfo::DeviceTile::~DeviceTile () inline
Definition at line 424 of file DeviceInfo.h.
Member Function Documentation
addChildSite()
void DeviceInfo::DeviceTile::addChildSite (DeviceInfo::DeviceElement * sitePtr)
Definition at line 447 of file DeviceInfo.cc.
Referenced by DeviceInfo::addSite().
getChildrenSites()
std::vector<DeviceSite *>& DeviceInfo::DeviceTile::getChildrenSites () inline
Definition at line 429 of file DeviceInfo.h.
Referenced by DeviceInfo::addSite().
getTileIdX()
int DeviceInfo::DeviceTile::getTileIdX () inline
Definition at line 438 of file DeviceInfo.h.
getTileIdY()
int DeviceInfo::DeviceTile::getTileIdY () inline
Definition at line 443 of file DeviceInfo.h.
getTileType()
std::string& DeviceInfo::DeviceTile::getTileType () inline
Definition at line 433 of file DeviceInfo.h.
Referenced by DeviceInfo::addTile().
Member Data Documentation
childrenSites
std::vector<DeviceSite *> DeviceInfo::DeviceTile::childrenSites private
Definition at line 450 of file DeviceInfo.h.
Referenced by getChildrenSites().
device
DeviceInfo* DeviceInfo::DeviceTile::device private
Definition at line 451 of file DeviceInfo.h.
tileIdX
int DeviceInfo::DeviceTile::tileIdX = -1 private
Definition at line 452 of file DeviceInfo.h.
Referenced by DeviceTile(), and getTileIdX().
tileIdY
int DeviceInfo::DeviceTile::tileIdY = -1 private
Definition at line 453 of file DeviceInfo.h.
Referenced by DeviceTile(), and getTileIdY().
tileType
std::string DeviceInfo::DeviceTile::tileType private
Definition at line 449 of file DeviceInfo.h.
Referenced by getTileType().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/deviceInfo/DeviceInfo.h
src/lib/HiFPlacer/deviceInfo/DeviceInfo.cc