AMF-Placer: DeviceInfo::DeviceElement Class Reference
DeviceInfo::DeviceElement Class Reference
basic class of device element
#include <DeviceInfo.h>
Public Member Functions
DeviceElement (std::string &name, DeviceElement *parentPtr, DeviceElementType type, int id)
DeviceElement (std::string &name, DeviceElementType type, int id)
virtual ~DeviceElement ()
std::string & getName ()
DeviceElement * getParentPtr ()
DeviceElementType getElementType ()
int getElementIdInParent ()
Private Attributes
std::string name
DeviceElement * parentPtr
DeviceElementType type
int id
Detailed Description
basic class of device element
Definition at line 50 of file DeviceInfo.h.
Constructor & Destructor Documentation
DeviceElement() [1/2]
DeviceInfo::DeviceElement::DeviceElement (std::string & name, DeviceElement * parentPtr, DeviceElementType type, int id) inline
Definition at line 53 of file DeviceInfo.h.
DeviceElement() [2/2]
DeviceInfo::DeviceElement::DeviceElement (std::string & name, DeviceElementType type, int id) inline
Definition at line 58 of file DeviceInfo.h.
~DeviceElement()
virtual DeviceInfo::DeviceElement::~DeviceElement () inline virtual
Definition at line 63 of file DeviceInfo.h.
Member Function Documentation
getElementIdInParent()
int DeviceInfo::DeviceElement::getElementIdInParent () inline
Definition at line 79 of file DeviceInfo.h.
Referenced by ParallelCLBPacker::exceptionPULegalize().
getElementType()
DeviceElementType DeviceInfo::DeviceElement::getElementType () inline
Definition at line 75 of file DeviceInfo.h.
getName()
std::string& DeviceInfo::DeviceElement::getName () inline
Definition at line 67 of file DeviceInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPUFailReason(), DeviceInfo::ClockColumn::addSite(), DeviceInfo::ClockRegion::addSite(), PlacementInfo::PlacementBinInfo::addSiteIntoBin(), PlacementInfo::PlacementSiteBinInfo::addSiteIntoBin(), operator<<(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself().
getParentPtr()
DeviceElement* DeviceInfo::DeviceElement::getParentPtr () inline
Definition at line 71 of file DeviceInfo.h.
Member Data Documentation
id
int DeviceInfo::DeviceElement::id private
Definition at line 88 of file DeviceInfo.h.
Referenced by getElementIdInParent(), and DeviceInfo::ClockColumn::getId().
name
std::string DeviceInfo::DeviceElement::name private
Definition at line 85 of file DeviceInfo.h.
Referenced by getName().
parentPtr
DeviceElement* DeviceInfo::DeviceElement::parentPtr private
Definition at line 86 of file DeviceInfo.h.
Referenced by getParentPtr(), and DeviceInfo::DeviceBEL::~DeviceBEL().
type
DeviceElementType DeviceInfo::DeviceElement::type private
Definition at line 87 of file DeviceInfo.h.
Referenced by getElementType().
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/deviceInfo/DeviceInfo.h