AMF-Placer: PlacementInfo::ClusterUnit Class Reference
PlacementInfo::ClusterUnit Class Reference
a group of PlacementUnits
#include <PlacementInfo.h>
Public Member Functions
ClusterUnit (int id)
~ClusterUnit ()
int getWeight ()
int getBRAMNum ()
int getDSPNum ()
void addPlacementUnit (PlacementInfo::PlacementUnit *curPU)
std::vector< PlacementInfo::PlacementUnit * > & getUnits ()
int getId ()
Private Attributes
std::vector< PlacementInfo::PlacementUnit * > PUs
int totalWeight
int totalBRAMNum
int totalDSPNum
int id
Detailed Description
a group of PlacementUnits
record the rought resource demand and PlacementUnits inside it. Usually used for initial processing (initial placement.)
Definition at line 2396 of file PlacementInfo.h.
Constructor & Destructor Documentation
ClusterUnit()
PlacementInfo::ClusterUnit::ClusterUnit (int id) inline
Definition at line 2399 of file PlacementInfo.h.
~ClusterUnit()
PlacementInfo::ClusterUnit::~ClusterUnit () inline
Definition at line 2406 of file PlacementInfo.h.
Member Function Documentation
addPlacementUnit()
void PlacementInfo::ClusterUnit::addPlacementUnit (PlacementInfo::PlacementUnit * curPU) inline
Definition at line 2420 of file PlacementInfo.h.
Referenced by ClusterPlacer::createClockBasedClusterUnits(), ClusterPlacer::createLongPathClusterUnits(), ClusterPlacer::createSinglePUClusterUnits(), and ClusterPlacer::createUserDefinedClusterBasedClusterUnits().
getBRAMNum()
int PlacementInfo::ClusterUnit::getBRAMNum () inline
Definition at line 2411 of file PlacementInfo.h.
getDSPNum()
int PlacementInfo::ClusterUnit::getDSPNum () inline
Definition at line 2415 of file PlacementInfo.h.
getId()
int PlacementInfo::ClusterUnit::getId () inline
Definition at line 2433 of file PlacementInfo.h.
Referenced by ClusterPlacer::createClockBasedClusterUnits(), ClusterPlacer::createLongPathClusterUnits(), ClusterPlacer::createSinglePUClusterUnits(), and ClusterPlacer::createUserDefinedClusterBasedClusterUnits().
getUnits()
std::vector< PlacementInfo::PlacementUnit * > & PlacementInfo::ClusterUnit::getUnits () inline
Definition at line 2428 of file PlacementInfo.h.
Referenced by ClusterPlacer::createClockBasedClusterUnits().
getWeight()
int PlacementInfo::ClusterUnit::getWeight () inline
Definition at line 2407 of file PlacementInfo.h.
Member Data Documentation
id
int PlacementInfo::ClusterUnit::id private
Definition at line 2441 of file PlacementInfo.h.
Referenced by getId().
PUs
std::vector<PlacementInfo::PlacementUnit *> PlacementInfo::ClusterUnit::PUs private
Definition at line 2439 of file PlacementInfo.h.
Referenced by addPlacementUnit(), ClusterUnit(), and getUnits().
totalBRAMNum
int PlacementInfo::ClusterUnit::totalBRAMNum private
Definition at line 2440 of file PlacementInfo.h.
Referenced by addPlacementUnit(), ClusterUnit(), and getBRAMNum().
totalDSPNum
int PlacementInfo::ClusterUnit::totalDSPNum private
Definition at line 2440 of file PlacementInfo.h.
Referenced by addPlacementUnit(), ClusterUnit(), and getDSPNum().
totalWeight
int PlacementInfo::ClusterUnit::totalWeight private
Definition at line 2440 of file PlacementInfo.h.
Referenced by addPlacementUnit(), ClusterUnit(), and getWeight().
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h