AMF-Placer: ParallelCLBPacker::PackingCLBSite Class Reference
ParallelCLBPacker::PackingCLBSite Class Reference
PackingCLBSite is a container for the packing information (parameters, candidates and packing status) of a specific DeviceInfo::DeviceSite.
#include <ParallelCLBPacker.h>
Classes
class PackingCLBCluster
PackingCLBCluster is a container of cells/PlacementUnits which can be packed in the corresponding CLB site.
class SiteBELMapping
SiteBELMapping is a contain recording the mapping between cells and BELs.
Public Member Functions
PackingCLBSite (PlacementInfo *placementInfo, DeviceInfo::DeviceSite *CLBSite, int unchangedIterationThr, int numNeighbor, float deltaD, float curD, float maxD, unsigned int PQSize, float y2xRatio, float HPWLWeight, std::vector< PackingCLBSite *> &PUId2PackingCLBSite)
Construct a new Packing CLB Site object.
~PackingCLBSite ()
bool isPQTopCompletelyAccptedByCells ()
check whether all the PlacementUnit in the top cluster in the priority queue have been assigned to this CLB site
std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > * findNeiborPUsFromBinGrid (DesignInfo::DesignCellType curCellType, float targetX, float targetY, float displacementLowerbound, float displacementUpperbound, int PUNumThreshold, const std::vector< PackingCLBSite *> &PUId2PackingCLBSite, float y2xRatio, std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > *res=nullptr, bool clockRegionAware=true)
find neighbor PlacementUnit around targetX/Y from the bin grid
std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > & getNeighborPUs ()
void refreshPrioryQueue ()
sort the elements in the priority queue
void removeInvalidClustersFromPQ ()
remove invalid clusters from the priority queue
void removeInvalidPUsFromNeighborPUs ()
remove invalid clusters from neighbor PlacementUnits
void removeClustersIncompatibleWithDetClusterFromPQ ()
remove clusters incompatible with determined cluster from PQ
void findNewClustersWithNeighborPUs ()
extend the clusters in the priority queue with the neighbor PlacementUnits
void updateStep (bool initial, bool debug=false)
a iteration to pack PlacementUnit into a CLB site
void updateConsistentPUsInTop ()
update the information of consistent PUs at the top of priority queue
bool hasValidPQTop ()
const PackingCLBCluster * getPriorityQueueTop ()
DeviceInfo::DeviceSite * getCLBSite ()
float getY2xRatio () const
float getDetScore ()
PackingCLBCluster * getDeterminedClusterInSite ()
void setDeterminedClusterInSite (PackingCLBCluster *tmpCluster)
float getHPWLChangeForPU (PlacementInfo::PlacementUnit *tmpPU)
void setDebug ()
PlacementInfo * getPlacementInfo () const
void addCarry ()
add CARRY-related PlacementUnit into this CLB site
void addLUTRAMMacro ()
add LUTRAM-related PlacementUnit into this CLB site
void setNonCLBCell (DesignInfo::DesignCell *_NonCLBCell)
bool checkIsPrePackedSite ()
bool checkIsCarrySite ()
bool checkIsNonCLBSite ()
bool checkIsMuxSite ()
bool checkIsLUTRAMSite ()
PlacementInfo::PlacementMacro * getCarryMacro ()
DesignInfo::DesignCell * getCarryCell ()
PlacementInfo::PlacementMacro * getLUTRAMMacro ()
DesignInfo::DesignCell * getNonCLBCell ()
int getCarrySiteOffset ()
unsigned int getPairPinNum (DesignInfo::DesignCell *LUTA, DesignInfo::DesignCell *LUTB)
check how many input pins will be needed if the two LUTs are packed.
void mapCarryRelatedCellsToSlots (PlacementInfo::PlacementMacro *_CARRYChain, float siteOffset)
void mapLUTRAMRelatedCellsToSlots (PlacementInfo::PlacementMacro *_LUTRAMMacro)
void finalMapToSlotsForCarrySite (int FFControlSetOrderId)
find the slots in the site for Muxes
void finalMapToSlotsForCarrySite ()
find the slots in the site for Carry by enumeration
bool compatibleInOneHalfCLB (int halfCLB, int anotherHalfCLB)
check whether two half CLB can be packed togather
void mapMuxF8Macro (int muxF8Offset, PlacementInfo::PlacementMacro *MUXF8Macro)
map cells in MUXF8 macro to CLB slot
void mapMuxF7Macro (int halfCLBOffset, PlacementInfo::PlacementMacro *MUXF7Macro)
map cells in MUXF7 macro to CLB slot
int findMuxFromHalfCLB (PlacementInfo::PlacementMacro *MUXF8Macro)
find the correspdnding FF control set id for a given Mux macro (this mux macro should have been mapped to a control set in this site)
void greedyMapMuxForCommonLUTFFInSite (int FFControlSetOrderId)
find the slots in the site for Muxes
void greedyMapMuxForCommonLUTFFInSite ()
find the slots in the site for Muxes by enumeration
void finalMapToSlotsForCommonLUTFFInSite (int FFControlSetOrderId)
greedily find the exact slots for the LUTs/FFs in the site
void finalMapToSlotsForCommonLUTFFInSite ()
finally map LUTs/FFs to the exact slots in the sites
bool isMuxMacro (DesignInfo::DesignCell *cell)
bool isCarryMacro (DesignInfo::DesignCell *cell)
void moveLUTToLUT6Slot ()
void finalMapToSlots ()
finally map the elements (CARRY/MUX/LUT/FF) packed in this site into the slots in the site
std::set< std::pair< DesignInfo::DesignCell *, DesignInfo::DesignCell * > > & getFixedPairedLUTs ()
Get the fixed pairs of LUTs which should NOT be broken.
std::set< DesignInfo::DesignCell * > & getConflictLUTs ()
Get the LUTs which CANNOT be paired.
bool conflictLUTsContain (DesignInfo::DesignCell *tmpCell)
check whether a given cell is unpackable
const SiteBELMapping & getSlotMapping () const
Get the slot(BEL) mapping of the cells.
SiteBELMapping & getSlotMappingRef ()
int checkDirectLUTFFConnect (std::map< DesignInfo::DesignCell *, DesignInfo::DesignCell *> &FF2LUT, DesignInfo::DesignCell *tmpLUT, DesignInfo::DesignCell *tmpFF)
check whether the FF/LUT are directly connected
float checkDirectLUTFFConnect_slack (std::map< DesignInfo::DesignCell *, DesignInfo::DesignCell *> &FF2LUT, DesignInfo::DesignCell *tmpLUT, DesignInfo::DesignCell *tmpFF)
check whether the FF/LUT are directly connected and calculate the slack
void setClockRegionAwareTo (bool _clockRegionAware)
std::array< int, 3 > getLUTSlot (DesignInfo::DesignCell *targetCell)
std::array< int, 3 > getFFSlot (DesignInfo::DesignCell *targetCell)
Private Attributes
PlacementInfo * placementInfo
DeviceInfo::DeviceSite * CLBSite
int unchangedIterationThr = 3
specify how many iterations a PlacementUnit should stay at the top priority of a site before we finally map it to the site
unsigned int numNeighbor = 10
the threshold number of cells for site
float deltaD = 1.0
the increase step of the neighbor search diameter
float curD = 0
current neighbor search diameter
float maxD = 10
the maximum constraint of the neighbor search diameter
unsigned int PQSize = 10
the size of priority queue (the low-priority candidates will be removed)
float y2xRatio = 1.0
a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
float HPWLWeight = 0.01
the factor of HPWL overhead in packing evaluation for a cell
bool clockRegionAware = true
whether make clock region become constraints
int unchangeIterationCnt = 0
std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > neighborPUs
std::vector< PackingCLBCluster * > seedClusters
std::vector< PackingCLBCluster * > priorityQueue
std::map< PlacementInfo::PlacementUnit *, int, Packing_PUcompare > PU2TopCnt
const std::vector< PackingCLBSite * > & PUId2PackingCLBSite
PackingCLBCluster * determinedClusterInSite = nullptr
float detScore = 0
bool isCarrySite = false
bool isLUTRAMSite = false
bool isNonCLBSite = false
PlacementInfo::PlacementMacro * CARRYChain = nullptr
PlacementInfo::PlacementMacro * LUTRAMMacro = nullptr
DesignInfo::DesignCell * carryCell = nullptr
DesignInfo::DesignCell * nonCLBCell = nullptr
int CARRYChainSiteOffset = -1
bool debug = false
std::set< DesignInfo::DesignCell * > mappedCells
std::set< DesignInfo::DesignCell * > mappedLUTs
std::set< DesignInfo::DesignCell * > mappedFFs
std::set< std::pair< DesignInfo::DesignCell *, DesignInfo::DesignCell * > > fixedPairedLUTs
std::set< DesignInfo::DesignCell * > fixedLUTsInPairs
std::set< DesignInfo::DesignCell * > conflictLUTs
SiteBELMapping slotMapping
float best_DirectConnect = -100000000
SiteBELMapping best_SlotMapping
std::set< DesignInfo::DesignCell * > best_mappedCells
std::set< DesignInfo::DesignCell * > best_mappedLUTs
std::set< DesignInfo::DesignCell * > best_mappedFFs
Detailed Description
PackingCLBSite is a container for the packing information (parameters, candidates and packing status) of a specific DeviceInfo::DeviceSite.
Definition at line 387 of file ParallelCLBPacker.h.
Constructor & Destructor Documentation
PackingCLBSite()
ParallelCLBPacker::PackingCLBSite::PackingCLBSite (PlacementInfo * placementInfo, DeviceInfo::DeviceSite * CLBSite, int unchangedIterationThr, int numNeighbor, float deltaD, float curD, float maxD, unsigned int PQSize, float y2xRatio, float HPWLWeight, std::vector< PackingCLBSite *> & PUId2PackingCLBSite) inline
Construct a new Packing CLB Site object.
Parameters
placementInfo the PlacementInfo for this placer to handle
CLBSite
unchangedIterationThr specify how many iterations a PlacementUnit should stay at the top priority of a site before we finally map it to the site
numNeighbor the threshold number of cells for site
deltaD the increase step of the neighbor search diameter
curD current neighbor search diameter
maxD the maximum constraint of the neighbor search diameter
PQSize the size of priority queue (the low-priority candidates will be removed)
y2xRatio a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
HPWLWeight the factor of HPWL overhead in packing evaluation for a cell
PUId2PackingCLBSite the reference of a map (actually a vector) recording the mapping of PlacementUnits to the PackingCLBSites
Definition at line 408 of file ParallelCLBPacker.h.
~PackingCLBSite()
ParallelCLBPacker::PackingCLBSite::~PackingCLBSite () inline
Definition at line 423 of file ParallelCLBPacker.h.
Member Function Documentation
addCarry()
void ParallelCLBPacker::PackingCLBSite::addCarry () inline
add CARRY-related PlacementUnit into this CLB site
Definition at line 1982 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::ripUpAndLegalizae().
addLUTRAMMacro()
void ParallelCLBPacker::PackingCLBSite::addLUTRAMMacro () inline
add LUTRAM-related PlacementUnit into this CLB site
Definition at line 2040 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::ripUpAndLegalizae().
checkDirectLUTFFConnect()
int ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect (std::map< DesignInfo::DesignCell *, DesignInfo::DesignCell *> & FF2LUT, DesignInfo::DesignCell * tmpLUT, DesignInfo::DesignCell * tmpFF) inline
check whether the FF/LUT are directly connected
Parameters
FF2LUT
tmpLUT
tmpFF
Returns
int
Definition at line 2574 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
checkDirectLUTFFConnect_slack()
float ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack (std::map< DesignInfo::DesignCell *, DesignInfo::DesignCell *> & FF2LUT, DesignInfo::DesignCell * tmpLUT, DesignInfo::DesignCell * tmpFF) inline
check whether the FF/LUT are directly connected and calculate the slack
Parameters
FF2LUT
tmpLUT
tmpFF
Returns
float
Definition at line 2594 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
checkIsCarrySite()
bool ParallelCLBPacker::PackingCLBSite::checkIsCarrySite () inline
Definition at line 2062 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), finalMapToSlotsForCarrySite(), and ParallelCLBPacker::ripUpAndLegalizae().
checkIsLUTRAMSite()
bool ParallelCLBPacker::PackingCLBSite::checkIsLUTRAMSite () inline
Definition at line 2081 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), and ParallelCLBPacker::ripUpAndLegalizae().
checkIsMuxSite()
bool ParallelCLBPacker::PackingCLBSite::checkIsMuxSite () inline
Definition at line 2072 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
checkIsNonCLBSite()
bool ParallelCLBPacker::PackingCLBSite::checkIsNonCLBSite () inline
Definition at line 2067 of file ParallelCLBPacker.h.
checkIsPrePackedSite()
bool ParallelCLBPacker::PackingCLBSite::checkIsPrePackedSite () inline
Definition at line 2057 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), and ParallelCLBPacker::ripUpAndLegalizae().
compatibleInOneHalfCLB()
bool ParallelCLBPacker::PackingCLBSite::compatibleInOneHalfCLB (int halfCLB, int anotherHalfCLB) inline
check whether two half CLB can be packed togather
Parameters
halfCLB
anotherHalfCLB
Returns
true
false
Definition at line 2387 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
conflictLUTsContain()
bool ParallelCLBPacker::PackingCLBSite::conflictLUTsContain (DesignInfo::DesignCell * tmpCell) inline
check whether a given cell is unpackable
some driver LUTs of CARRY/MUX cannot be paired
Parameters
tmpCell the given cell
Returns
true if the cell CANNOT be paired with other LUTs
false if the cell CAN be paired with other LUTs
Definition at line 2546 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT(), finalMapToSlotsForCarrySite(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::maxCardinalityMatching().
finalMapToSlots()
void ParallelCLBPacker::PackingCLBSite::finalMapToSlots () inline
finally map the elements (CARRY/MUX/LUT/FF) packed in this site into the slots in the site
Definition at line 2489 of file ParallelCLBPacker.h.
finalMapToSlotsForCarrySite() [1/2]
void ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite (int FFControlSetOrderId)
find the slots in the site for Muxes
Parameters
FFControlSetOrderId control the order of FF Control sets
Definition at line 557 of file ParallelCLBPacker_PackingCLBSite.cc.
finalMapToSlotsForCarrySite() [2/2]
void ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite ()
find the slots in the site for Carry by enumeration
Definition at line 532 of file ParallelCLBPacker_PackingCLBSite.cc.
finalMapToSlotsForCommonLUTFFInSite() [1/2]
void ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite (int FFControlSetOrderId)
greedily find the exact slots for the LUTs/FFs in the site
Parameters
FFControlSetOrderId control the order of FF Control sets
Definition at line 1143 of file ParallelCLBPacker_PackingCLBSite.cc.
finalMapToSlotsForCommonLUTFFInSite() [2/2]
void ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite ()
finally map LUTs/FFs to the exact slots in the sites
Definition at line 2707 of file ParallelCLBPacker_PackingCLBSite.cc.
findMuxFromHalfCLB()
int ParallelCLBPacker::PackingCLBSite::findMuxFromHalfCLB (PlacementInfo::PlacementMacro * MUXF8Macro)
find the correspdnding FF control set id for a given Mux macro (this mux macro should have been mapped to a control set in this site)
Parameters
MUXF8Macro a given Mux macro
Returns
int
Definition at line 2028 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by greedyMapMuxForCommonLUTFFInSite().
findNeiborPUsFromBinGrid()
std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > * ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid (DesignInfo::DesignCellType curCellType, float targetX, float targetY, float displacementLowerbound, float displacementUpperbound, int PUNumThreshold, const std::vector< PackingCLBSite *> & PUId2PackingCLBSite, float y2xRatio, std::set< PlacementInfo::PlacementUnit *, Packing_PUcompare > * res = nullptr, bool clockRegionAware = true)
find neighbor PlacementUnit around targetX/Y from the bin grid
Parameters
curCellType the given cell types
targetX target location X
targetY target location Y
displacementLowerbound the lower bound threshold of neighbors' displacement from the center (the neighbors with low displacement might be tried by previous procedure)
displacementUpperbound the upper bound threshold of neighbors' displacement from the center
PUNumThreshold The threshold number of PlacementUnits found to stop the search procedure
PUId2PackingCLBSite The reference mapping indicating mapped PlacementUnits
y2xRatio a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
res a input set to store resultant PUs (for inremental search if it is not nullptr)
clockRegionAware whether make clock region become constraints
Returns
std::set<PlacementInfo::PlacementUnit *, Packing_PUcompare>*
Definition at line 298 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
findNewClustersWithNeighborPUs()
void ParallelCLBPacker::PackingCLBSite::findNewClustersWithNeighborPUs ()
extend the clusters in the priority queue with the neighbor PlacementUnits
Definition at line 244 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
getCarryCell()
DesignInfo::DesignCell* ParallelCLBPacker::PackingCLBSite::getCarryCell () inline
Definition at line 2091 of file ParallelCLBPacker.h.
getCarryMacro()
PlacementInfo::PlacementMacro* ParallelCLBPacker::PackingCLBSite::getCarryMacro () inline
Definition at line 2086 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkCellCorrectness(), operator<<(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself().
getCarrySiteOffset()
int ParallelCLBPacker::PackingCLBSite::getCarrySiteOffset () inline
Definition at line 2106 of file ParallelCLBPacker.h.
Referenced by operator<<(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself().
getCLBSite()
DeviceInfo::DeviceSite* ParallelCLBPacker::PackingCLBSite::getCLBSite () inline
Definition at line 1906 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPUFailReason(), ParallelCLBPacker::exceptionPULegalize(), operator<<(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself(), ParallelCLBPacker::ripUpAndLegalizae(), and ParallelCLBPacker::timingDrivenDetailedPlacement_swap().
getConflictLUTs()
std::set<DesignInfo::DesignCell *>& ParallelCLBPacker::PackingCLBSite::getConflictLUTs () inline
Get the LUTs which CANNOT be paired.
Returns
std::set<DesignInfo::DesignCell *>&
Definition at line 2532 of file ParallelCLBPacker.h.
getDeterminedClusterInSite()
PackingCLBCluster* ParallelCLBPacker::PackingCLBSite::getDeterminedClusterInSite () inline
Definition at line 1921 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::exceptionPULegalize(), ParallelCLBPacker::ripUpAndLegalizae(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), and ParallelCLBPacker::timingDrivenDetailedPlacement_swap().
getDetScore()
float ParallelCLBPacker::PackingCLBSite::getDetScore () inline
Definition at line 1916 of file ParallelCLBPacker.h.
getFFSlot()
std::array<int, 3> ParallelCLBPacker::PackingCLBSite::getFFSlot (DesignInfo::DesignCell * targetCell) inline
Definition at line 2642 of file ParallelCLBPacker.h.
getFixedPairedLUTs()
std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *> >& ParallelCLBPacker::PackingCLBSite::getFixedPairedLUTs () inline
Get the fixed pairs of LUTs which should NOT be broken.
Returns
std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *>>&
Definition at line 2522 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT(), operator<<(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself().
getHPWLChangeForPU()
float ParallelCLBPacker::PackingCLBSite::getHPWLChangeForPU (PlacementInfo::PlacementUnit * tmpPU) inline
Definition at line 1931 of file ParallelCLBPacker.h.
getLUTRAMMacro()
PlacementInfo::PlacementMacro* ParallelCLBPacker::PackingCLBSite::getLUTRAMMacro () inline
Definition at line 2096 of file ParallelCLBPacker.h.
getLUTSlot()
std::array<int, 3> ParallelCLBPacker::PackingCLBSite::getLUTSlot (DesignInfo::DesignCell * targetCell) inline
Definition at line 2623 of file ParallelCLBPacker.h.
getNeighborPUs()
std::set<PlacementInfo::PlacementUnit *, Packing_PUcompare>& ParallelCLBPacker::PackingCLBSite::getNeighborPUs () inline
Definition at line 1836 of file ParallelCLBPacker.h.
getNonCLBCell()
DesignInfo::DesignCell* ParallelCLBPacker::PackingCLBSite::getNonCLBCell () inline
Definition at line 2101 of file ParallelCLBPacker.h.
getPairPinNum()
unsigned int ParallelCLBPacker::PackingCLBSite::getPairPinNum (DesignInfo::DesignCell * LUTA, DesignInfo::DesignCell * LUTB) inline
check how many input pins will be needed if the two LUTs are packed.
Parameters
LUTA
LUTB
Returns
unsigned int
Definition at line 2118 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
getPlacementInfo()
PlacementInfo* ParallelCLBPacker::PackingCLBSite::getPlacementInfo () const inline
Definition at line 1973 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPUFailReason(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkCellCorrectness(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::checkNumMuxCompatibleInFFSet(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::PackingCLBCluster().
getPriorityQueueTop()
const PackingCLBCluster* ParallelCLBPacker::PackingCLBSite::getPriorityQueueTop () inline
Definition at line 1900 of file ParallelCLBPacker.h.
getSlotMapping()
const SiteBELMapping& ParallelCLBPacker::PackingCLBSite::getSlotMapping () const inline
Get the slot(BEL) mapping of the cells.
Returns
const SiteBELMapping&
Definition at line 2556 of file ParallelCLBPacker.h.
getSlotMappingRef()
SiteBELMapping& ParallelCLBPacker::PackingCLBSite::getSlotMappingRef () inline
Definition at line 2561 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping().
getY2xRatio()
float ParallelCLBPacker::PackingCLBSite::getY2xRatio () const inline
Definition at line 1911 of file ParallelCLBPacker.h.
Referenced by operator<<(), and ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself().
greedyMapMuxForCommonLUTFFInSite() [1/2]
void ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite (int FFControlSetOrderId)
find the slots in the site for Muxes
Parameters
FFControlSetOrderId control the order of FF Control sets
Definition at line 2068 of file ParallelCLBPacker_PackingCLBSite.cc.
greedyMapMuxForCommonLUTFFInSite() [2/2]
void ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite ()
find the slots in the site for Muxes by enumeration
Definition at line 2047 of file ParallelCLBPacker_PackingCLBSite.cc.
hasValidPQTop()
bool ParallelCLBPacker::PackingCLBSite::hasValidPQTop () inline
Definition at line 1895 of file ParallelCLBPacker.h.
isCarryMacro()
bool ParallelCLBPacker::PackingCLBSite::isCarryMacro (DesignInfo::DesignCell * cell) inline
Definition at line 2471 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite().
isMuxMacro()
bool ParallelCLBPacker::PackingCLBSite::isMuxMacro (DesignInfo::DesignCell * cell) inline
Definition at line 2458 of file ParallelCLBPacker.h.
Referenced by greedyMapMuxForCommonLUTFFInSite().
isPQTopCompletelyAccptedByCells()
bool ParallelCLBPacker::PackingCLBSite::isPQTopCompletelyAccptedByCells () inline
check whether all the PlacementUnit in the top cluster in the priority queue have been assigned to this CLB site
Returns
true if all the PlacementUnits in the top cluster in the priority queue have been assigned to this CLB site
false if some of the PlacementUnits in the top cluster in the priority queue have NOT been assigned to this CLB site yet (maybe unassigned yet or maybe assigned to some other CLB sites)
Definition at line 1799 of file ParallelCLBPacker.h.
mapCarryRelatedCellsToSlots()
void ParallelCLBPacker::PackingCLBSite::mapCarryRelatedCellsToSlots (PlacementInfo::PlacementMacro * _CARRYChain, float siteOffset)
Definition at line 2751 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by finalMapToSlotsForCarrySite().
mapLUTRAMRelatedCellsToSlots()
void ParallelCLBPacker::PackingCLBSite::mapLUTRAMRelatedCellsToSlots (PlacementInfo::PlacementMacro * _LUTRAMMacro)
Definition at line 2745 of file ParallelCLBPacker_PackingCLBSite.cc.
mapMuxF7Macro()
void ParallelCLBPacker::PackingCLBSite::mapMuxF7Macro (int halfCLBOffset, PlacementInfo::PlacementMacro * MUXF7Macro)
map cells in MUXF7 macro to CLB slot
Parameters
muxF7Offset the offset of the MUXF7 in the CLB site. There is only two slots for MUXF8
MUXF7Macro the pointer of the MUXF7 needed to be mapped into current site
Definition at line 1906 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by greedyMapMuxForCommonLUTFFInSite().
mapMuxF8Macro()
void ParallelCLBPacker::PackingCLBSite::mapMuxF8Macro (int muxF8Offset, PlacementInfo::PlacementMacro * MUXF8Macro)
map cells in MUXF8 macro to CLB slot
Parameters
muxF8Offset the offset of the MUXF8 in the CLB site. There is only two slots for MUXF8
MUXF8Macro the pointer of the MUXF8 needed to be mapped into current site
Definition at line 1763 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by greedyMapMuxForCommonLUTFFInSite().
moveLUTToLUT6Slot()
void ParallelCLBPacker::PackingCLBSite::moveLUTToLUT6Slot ()
Definition at line 2723 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
refreshPrioryQueue()
void ParallelCLBPacker::PackingCLBSite::refreshPrioryQueue ()
sort the elements in the priority queue
Definition at line 16 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
removeClustersIncompatibleWithDetClusterFromPQ()
void ParallelCLBPacker::PackingCLBSite::removeClustersIncompatibleWithDetClusterFromPQ ()
remove clusters incompatible with determined cluster from PQ
some of the clusters in the PQ are not compatible with the determined set of PUs, so we need to remove them too.
Definition at line 58 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
removeInvalidClustersFromPQ()
void ParallelCLBPacker::PackingCLBSite::removeInvalidClustersFromPQ ()
remove invalid clusters from the priority queue
since some of the PlacementUnits have been determined to be mapped to some other sites, they should be removed from the PQ
Definition at line 37 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
removeInvalidPUsFromNeighborPUs()
void ParallelCLBPacker::PackingCLBSite::removeInvalidPUsFromNeighborPUs ()
remove invalid clusters from neighbor PlacementUnits
since some of the PlacementUnits have been determined to be mapped to some other sites, they should be removed from the neighbor PU set. Moreover, some of the candidate PUs are not compatible with the determined set of PUs, so we need to remove them too.
Definition at line 97 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
setClockRegionAwareTo()
void ParallelCLBPacker::PackingCLBSite::setClockRegionAwareTo (bool _clockRegionAware) inline
Definition at line 2618 of file ParallelCLBPacker.h.
setDebug()
void ParallelCLBPacker::PackingCLBSite::setDebug () inline
Definition at line 1968 of file ParallelCLBPacker.h.
Referenced by updateStep().
setDeterminedClusterInSite()
void ParallelCLBPacker::PackingCLBSite::setDeterminedClusterInSite (PackingCLBCluster * tmpCluster) inline
Definition at line 1926 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::ripUpAndLegalizae(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), and ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath().
setNonCLBCell()
void ParallelCLBPacker::PackingCLBSite::setNonCLBCell (DesignInfo::DesignCell * _NonCLBCell) inline
Definition at line 2049 of file ParallelCLBPacker.h.
Referenced by ParallelCLBPacker::addNonCLBPackingSites().
updateConsistentPUsInTop()
void ParallelCLBPacker::PackingCLBSite::updateConsistentPUsInTop ()
update the information of consistent PUs at the top of priority queue
the PQ top might be kept updated but some of its PUs might be consistent, which we can make them as determined PUs.
Definition at line 130 of file ParallelCLBPacker_PackingCLBSite.cc.
Referenced by updateStep().
updateStep()
void ParallelCLBPacker::PackingCLBSite::updateStep (bool initial, bool debug = false)
a iteration to pack PlacementUnit into a CLB site
Parameters
initial indicate whether it is the first packing iteration
debug dump debug information or not
Definition at line 422 of file ParallelCLBPacker_PackingCLBSite.cc.
Member Data Documentation
best_DirectConnect
float ParallelCLBPacker::PackingCLBSite::best_DirectConnect = -100000000 private
Definition at line 2751 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
best_mappedCells
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::best_mappedCells private
Definition at line 2753 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
best_mappedFFs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::best_mappedFFs private
Definition at line 2755 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
best_mappedLUTs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::best_mappedLUTs private
Definition at line 2754 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
best_SlotMapping
SiteBELMapping ParallelCLBPacker::PackingCLBSite::best_SlotMapping private
Definition at line 2752 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), and greedyMapMuxForCommonLUTFFInSite().
carryCell
DesignInfo::DesignCell* ParallelCLBPacker::PackingCLBSite::carryCell = nullptr private
Definition at line 2737 of file ParallelCLBPacker.h.
Referenced by mapCarryRelatedCellsToSlots().
CARRYChain
PlacementInfo::PlacementMacro* ParallelCLBPacker::PackingCLBSite::CARRYChain = nullptr private
Definition at line 2735 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), and mapCarryRelatedCellsToSlots().
CARRYChainSiteOffset
int ParallelCLBPacker::PackingCLBSite::CARRYChainSiteOffset = -1 private
Definition at line 2739 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), and mapCarryRelatedCellsToSlots().
CLBSite
DeviceInfo::DeviceSite* ParallelCLBPacker::PackingCLBSite::CLBSite private
Definition at line 2664 of file ParallelCLBPacker.h.
Referenced by updateConsistentPUsInTop(), and updateStep().
clockRegionAware
bool ParallelCLBPacker::PackingCLBSite::clockRegionAware = true private
whether make clock region become constraints
Definition at line 2720 of file ParallelCLBPacker.h.
conflictLUTs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::conflictLUTs private
Definition at line 2748 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), and mapCarryRelatedCellsToSlots().
curD
float ParallelCLBPacker::PackingCLBSite::curD = 0 private
current neighbor search diameter
Definition at line 2689 of file ParallelCLBPacker.h.
Referenced by updateStep().
debug
bool ParallelCLBPacker::PackingCLBSite::debug = false private
Definition at line 2741 of file ParallelCLBPacker.h.
deltaD
float ParallelCLBPacker::PackingCLBSite::deltaD = 1.0 private
the increase step of the neighbor search diameter
Definition at line 2683 of file ParallelCLBPacker.h.
Referenced by updateStep().
determinedClusterInSite
PackingCLBCluster* ParallelCLBPacker::PackingCLBSite::determinedClusterInSite = nullptr private
Definition at line 2729 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), findMuxFromHalfCLB(), greedyMapMuxForCommonLUTFFInSite(), mapMuxF7Macro(), moveLUTToLUT6Slot(), removeClustersIncompatibleWithDetClusterFromPQ(), removeInvalidClustersFromPQ(), removeInvalidPUsFromNeighborPUs(), updateConsistentPUsInTop(), and updateStep().
detScore
float ParallelCLBPacker::PackingCLBSite::detScore = 0 private
Definition at line 2730 of file ParallelCLBPacker.h.
Referenced by updateConsistentPUsInTop().
fixedLUTsInPairs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::fixedLUTsInPairs private
Definition at line 2747 of file ParallelCLBPacker.h.
Referenced by mapCarryRelatedCellsToSlots().
fixedPairedLUTs
std::set<std::pair<DesignInfo::DesignCell *, DesignInfo::DesignCell *> > ParallelCLBPacker::PackingCLBSite::fixedPairedLUTs private
Definition at line 2746 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), and mapCarryRelatedCellsToSlots().
HPWLWeight
float ParallelCLBPacker::PackingCLBSite::HPWLWeight = 0.01 private
the factor of HPWL overhead in packing evaluation for a cell
Definition at line 2714 of file ParallelCLBPacker.h.
isCarrySite
bool ParallelCLBPacker::PackingCLBSite::isCarrySite = false private
Definition at line 2732 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), and mapCarryRelatedCellsToSlots().
isLUTRAMSite
bool ParallelCLBPacker::PackingCLBSite::isLUTRAMSite = false private
Definition at line 2733 of file ParallelCLBPacker.h.
Referenced by mapLUTRAMRelatedCellsToSlots().
isNonCLBSite
bool ParallelCLBPacker::PackingCLBSite::isNonCLBSite = false private
Definition at line 2734 of file ParallelCLBPacker.h.
LUTRAMMacro
PlacementInfo::PlacementMacro* ParallelCLBPacker::PackingCLBSite::LUTRAMMacro = nullptr private
Definition at line 2736 of file ParallelCLBPacker.h.
Referenced by mapLUTRAMRelatedCellsToSlots().
mappedCells
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::mappedCells private
Definition at line 2743 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), mapCarryRelatedCellsToSlots(), mapMuxF7Macro(), and mapMuxF8Macro().
mappedFFs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::mappedFFs private
Definition at line 2745 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), mapCarryRelatedCellsToSlots(), mapMuxF7Macro(), and mapMuxF8Macro().
mappedLUTs
std::set<DesignInfo::DesignCell *> ParallelCLBPacker::PackingCLBSite::mappedLUTs private
Definition at line 2744 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), mapCarryRelatedCellsToSlots(), mapMuxF7Macro(), and mapMuxF8Macro().
maxD
float ParallelCLBPacker::PackingCLBSite::maxD = 10 private
the maximum constraint of the neighbor search diameter
Definition at line 2695 of file ParallelCLBPacker.h.
Referenced by updateStep().
neighborPUs
std::set<PlacementInfo::PlacementUnit *, Packing_PUcompare> ParallelCLBPacker::PackingCLBSite::neighborPUs private
Definition at line 2723 of file ParallelCLBPacker.h.
Referenced by findNewClustersWithNeighborPUs(), removeInvalidPUsFromNeighborPUs(), and updateStep().
nonCLBCell
DesignInfo::DesignCell* ParallelCLBPacker::PackingCLBSite::nonCLBCell = nullptr private
Definition at line 2738 of file ParallelCLBPacker.h.
numNeighbor
unsigned int ParallelCLBPacker::PackingCLBSite::numNeighbor = 10 private
the threshold number of cells for site
Definition at line 2677 of file ParallelCLBPacker.h.
Referenced by updateStep().
placementInfo
PlacementInfo* ParallelCLBPacker::PackingCLBSite::placementInfo private
Definition at line 2663 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), findNeiborPUsFromBinGrid(), greedyMapMuxForCommonLUTFFInSite(), mapCarryRelatedCellsToSlots(), and updateConsistentPUsInTop().
PQSize
unsigned int ParallelCLBPacker::PackingCLBSite::PQSize = 10 private
the size of priority queue (the low-priority candidates will be removed)
Definition at line 2701 of file ParallelCLBPacker.h.
Referenced by updateStep().
priorityQueue
std::vector<PackingCLBCluster *> ParallelCLBPacker::PackingCLBSite::priorityQueue private
Definition at line 2726 of file ParallelCLBPacker.h.
Referenced by findNewClustersWithNeighborPUs(), refreshPrioryQueue(), removeClustersIncompatibleWithDetClusterFromPQ(), removeInvalidClustersFromPQ(), updateConsistentPUsInTop(), and updateStep().
PU2TopCnt
std::map<PlacementInfo::PlacementUnit *, int, Packing_PUcompare> ParallelCLBPacker::PackingCLBSite::PU2TopCnt private
Definition at line 2727 of file ParallelCLBPacker.h.
Referenced by updateConsistentPUsInTop().
PUId2PackingCLBSite
const std::vector<PackingCLBSite *>& ParallelCLBPacker::PackingCLBSite::PUId2PackingCLBSite private
Definition at line 2728 of file ParallelCLBPacker.h.
Referenced by removeInvalidClustersFromPQ(), removeInvalidPUsFromNeighborPUs(), updateConsistentPUsInTop(), and updateStep().
seedClusters
std::vector<PackingCLBCluster *> ParallelCLBPacker::PackingCLBSite::seedClusters private
Definition at line 2725 of file ParallelCLBPacker.h.
Referenced by findNewClustersWithNeighborPUs(), and updateStep().
slotMapping
SiteBELMapping ParallelCLBPacker::PackingCLBSite::slotMapping private
Definition at line 2749 of file ParallelCLBPacker.h.
Referenced by finalMapToSlotsForCarrySite(), finalMapToSlotsForCommonLUTFFInSite(), greedyMapMuxForCommonLUTFFInSite(), mapCarryRelatedCellsToSlots(), mapMuxF7Macro(), mapMuxF8Macro(), and moveLUTToLUT6Slot().
unchangedIterationThr
int ParallelCLBPacker::PackingCLBSite::unchangedIterationThr = 3 private
specify how many iterations a PlacementUnit should stay at the top priority of a site before we finally map it to the site
Definition at line 2671 of file ParallelCLBPacker.h.
Referenced by updateConsistentPUsInTop().
unchangeIterationCnt
int ParallelCLBPacker::PackingCLBSite::unchangeIterationCnt = 0 private
Definition at line 2722 of file ParallelCLBPacker.h.
y2xRatio
float ParallelCLBPacker::PackingCLBSite::y2xRatio = 1.0 private
a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
Definition at line 2708 of file ParallelCLBPacker.h.
Referenced by updateStep().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/packing/ParallelCLBPacker.h
src/lib/HiFPlacer/placement/packing/ParallelCLBPacker_PackingCLBSite.cc