AMF-Placer: PlacementInfo::PlacementBinInfo Class Reference
PlacementInfo::PlacementBinInfo Class Reference
BEL bin for global placement for a specific shared BEL type.
#include <PlacementInfo.h>
Public Member Functions
PlacementBinInfo (std::string sharedCellType, float leftX, float rightX, float bottomY, float topY, int row, int column, CompatiblePlacementTable *compatiblePlacementTable)
Construct a new Placement Bin Info object.
~PlacementBinInfo ()
float getManhattanDistanceTo (float inX, float inY)
Get the shortest Manhattan distance from the bin to a specific location.
void addSiteIntoBin (DeviceInfo::DeviceSite *curSite)
add a resource site into the bin
bool inRange (float x, float y)
check if the bin covers a given location on the device
bool inRangeY (float y)
void addCell (DesignInfo::DesignCell *cell, int occupationAdded)
add a design cell into the bin
void removeCell (DesignInfo::DesignCell *cell, int occupationAdded)
remove a design cell from the bin
bool contains (DesignInfo::DesignCell *cell)
void reset ()
void shrinkBinBy (float r)
reduce the resource capacity by a given ratio
void inflateBinBy (float r)
increase the resource capacity by a given ratio
void resetBinShrinkRatio ()
float getRequiredBinShrinkRatio ()
void setRequiredBinShrinkRatio (float r)
Set the Required Bin Shrink Ratio for a bin.
std::set< DesignInfo::DesignCell * > & getCells ()
Get the reference of the set of cells in the bin.
float getBinShrinkRatio ()
float getUtilizationRate ()
Get the Utilization Rate: utilization / (capacity * binShrinkRatio)
float getRealUtilizationRate ()
Get the theoratical utilization rate (use LUT theoratical resource utilization without any adjustment to dump bin information)
float getUtilization ()
float getCapacity ()
bool isOverflow (float overflowThreshold)
check whether the resource demand in the bin is higher than the supply.
bool canAddMore (int BELAmo)
check whether we can add some BEL demand to the bin
int Y ()
return the row of the bin in the grid
int X ()
return the column of the bin in the grid
float left ()
return the left boundary of the bin
float right ()
return the right boundary of the bin
float top ()
return the top boundary of the bin
float bottom ()
return the bottom boundary of the bin
std::string getType ()
void countOverflow ()
increase one time of overflow situation
void countNoOverflow ()
increase one time of non-overflow situation
void resetNoOverflowCounter ()
void resetOverflowCounter ()
int getNoOverflowCounter ()
int getOverflowCounter ()
std::vector< DeviceInfo::DeviceSite * > & getCorrespondingSites ()
Get the reference of the set of sites in the bin.
std::string & getSharedCellType ()
void increaseSWDemandBy (float additionalDemand)
increase the net routing demand of the bin
float getSwitchDemandForNets () const
get the net routing demand of the bin
void setClockRegionX (int _x)
Set the clock region X for this bin.
int getClockRegionX ()
Get the clock region X for this bin.
Private Attributes
std::string sharedCellType
std::vector< DeviceInfo::DeviceSite * > correspondingSites
CompatiblePlacementTable * compatiblePlacementTable
std::set< DesignInfo::DesignCell * > cells
int capacity = 0
int utilization = 0
float binShrinkRatio = 1.0
float requiredBinShrinkRatio = 1.0
const float leftX
const float rightX
const float topY
const float bottomY
float eps = 1e-5
const int row
const int column
int overflowCnt = 0
int noOverflowCnt = 0
float switchDemandForNets = 0.0
float switchSupplyForNets = 0.0
std::mutex mtx
int clockRegionX = -1
Detailed Description
BEL bin for global placement for a specific shared BEL type.
To easier to find the neighbors of a design instance, we divide the design instances in the placement into a grid of bins. A placement bin will record the instances and resource sites inside it.
Definition at line 359 of file PlacementInfo.h.
Constructor & Destructor Documentation
PlacementBinInfo()
PlacementInfo::PlacementBinInfo::PlacementBinInfo (std::string sharedCellType, float leftX, float rightX, float bottomY, float topY, int row, int column, CompatiblePlacementTable * compatiblePlacementTable) inline
Construct a new Placement Bin Info object.
To construct a placement bin, we need to indicate its boundaries and target cell type for later information processing.
Parameters
sharedCellType
leftX bin left boundary
rightX bin right boundary
bottomY bin bottom boundary
topY bin top boundary
row which row in the grid
column which column in the grid
compatiblePlacementTable
Definition at line 378 of file PlacementInfo.h.
~PlacementBinInfo()
PlacementInfo::PlacementBinInfo::~PlacementBinInfo () inline
Definition at line 388 of file PlacementInfo.h.
Member Function Documentation
addCell()
void PlacementInfo::PlacementBinInfo::addCell (DesignInfo::DesignCell * cell, int occupationAdded) inline
add a design cell into the bin
we have to set the mutex locked during the process since we enable multi-threading in the placer.
Parameters
cell
occupationAdded how many slots will the cell occupy
Definition at line 457 of file PlacementInfo.h.
addSiteIntoBin()
void PlacementInfo::PlacementBinInfo::addSiteIntoBin (DeviceInfo::DeviceSite * curSite)
add a resource site into the bin
check the resources in the site and increase the resource capacity of the bin
Parameters
curSite
Definition at line 290 of file PlacementInfo.cc.
bottom()
float PlacementInfo::PlacementBinInfo::bottom () inline
return the bottom boundary of the bin
Returns
float
Definition at line 711 of file PlacementInfo.h.
Referenced by GeneralSpreader::expandFromABin(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
canAddMore()
bool PlacementInfo::PlacementBinInfo::canAddMore (int BELAmo) inline
check whether we can add some BEL demand to the bin
Parameters
BELAmo
Returns
true when there are available resources meeting the BEL demand.
false when there is no available resource meeting the BEL demand.
Definition at line 649 of file PlacementInfo.h.
contains()
bool PlacementInfo::PlacementBinInfo::contains (DesignInfo::DesignCell * cell) inline
Definition at line 487 of file PlacementInfo.h.
countNoOverflow()
void PlacementInfo::PlacementBinInfo::countNoOverflow () inline
increase one time of non-overflow situation
Definition at line 734 of file PlacementInfo.h.
countOverflow()
void PlacementInfo::PlacementBinInfo::countOverflow () inline
increase one time of overflow situation
Definition at line 725 of file PlacementInfo.h.
getBinShrinkRatio()
float PlacementInfo::PlacementBinInfo::getBinShrinkRatio () inline
Definition at line 556 of file PlacementInfo.h.
getCapacity()
float PlacementInfo::PlacementBinInfo::getCapacity () inline
Definition at line 615 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SpreadRegion().
getCells()
std::set<DesignInfo::DesignCell *>& PlacementInfo::PlacementBinInfo::getCells () inline
Get the reference of the set of cells in the bin.
Returns
std::set<DesignInfo::DesignCell *>&
Definition at line 551 of file PlacementInfo.h.
Referenced by PlacementInfo::findNeiborLUTFFsFromBinGrid(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), and GeneralSpreader::SpreadRegion::SpreadRegion().
getClockRegionX()
int PlacementInfo::PlacementBinInfo::getClockRegionX () inline
Get the clock region X for this bin.
Definition at line 806 of file PlacementInfo.h.
getCorrespondingSites()
std::vector<DeviceInfo::DeviceSite *>& PlacementInfo::PlacementBinInfo::getCorrespondingSites () inline
Get the reference of the set of sites in the bin.
Returns
std::vector<DeviceInfo::DeviceSite *>&
Definition at line 763 of file PlacementInfo.h.
Referenced by PlacementInfo::findNeiborSiteFromBinGrid(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
getManhattanDistanceTo()
float PlacementInfo::PlacementBinInfo::getManhattanDistanceTo (float inX, float inY) inline
Get the shortest Manhattan distance from the bin to a specific location.
Parameters
inX
inY
Returns
float
Definition at line 401 of file PlacementInfo.h.
Referenced by PlacementInfo::findNeiborLUTFFsFromBinGrid(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), PlacementInfo::findNeiborSiteFromBinGrid(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
getNoOverflowCounter()
int PlacementInfo::PlacementBinInfo::getNoOverflowCounter () inline
Definition at line 749 of file PlacementInfo.h.
getOverflowCounter()
int PlacementInfo::PlacementBinInfo::getOverflowCounter () inline
Definition at line 753 of file PlacementInfo.h.
getRealUtilizationRate()
float PlacementInfo::PlacementBinInfo::getRealUtilizationRate () inline
Get the theoratical utilization rate (use LUT theoratical resource utilization without any adjustment to dump bin information)
Returns
float
Definition at line 580 of file PlacementInfo.h.
getRequiredBinShrinkRatio()
float PlacementInfo::PlacementBinInfo::getRequiredBinShrinkRatio () inline
Definition at line 529 of file PlacementInfo.h.
getSharedCellType()
std::string& PlacementInfo::PlacementBinInfo::getSharedCellType () inline
Definition at line 768 of file PlacementInfo.h.
getSwitchDemandForNets()
float PlacementInfo::PlacementBinInfo::getSwitchDemandForNets () const inline
get the net routing demand of the bin
Definition at line 787 of file PlacementInfo.h.
Referenced by PlacementInfo::adjustLUTFFUtilization_Routability().
getType()
std::string PlacementInfo::PlacementBinInfo::getType () inline
Definition at line 716 of file PlacementInfo.h.
getUtilization()
float PlacementInfo::PlacementBinInfo::getUtilization () inline
Definition at line 610 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SpreadRegion().
getUtilizationRate()
float PlacementInfo::PlacementBinInfo::getUtilizationRate () inline
Get the Utilization Rate: utilization / (capacity * binShrinkRatio)
Returns
float
Definition at line 566 of file PlacementInfo.h.
Referenced by siteSortCmp().
increaseSWDemandBy()
void PlacementInfo::PlacementBinInfo::increaseSWDemandBy (float additionalDemand) inline
increase the net routing demand of the bin
Parameters
additionalDemand
Definition at line 778 of file PlacementInfo.h.
inflateBinBy()
void PlacementInfo::PlacementBinInfo::inflateBinBy (float r) inline
increase the resource capacity by a given ratio
Parameters
r
Definition at line 519 of file PlacementInfo.h.
inRange()
bool PlacementInfo::PlacementBinInfo::inRange (float x, float y) inline
check if the bin covers a given location on the device
Parameters
x
y
Returns
true if the bin covers the given location on the device
false if the bin does not cover the given location on the device
Definition at line 437 of file PlacementInfo.h.
inRangeY()
bool PlacementInfo::PlacementBinInfo::inRangeY (float y) inline
Definition at line 442 of file PlacementInfo.h.
isOverflow()
bool PlacementInfo::PlacementBinInfo::isOverflow (float overflowThreshold) inline
check whether the resource demand in the bin is higher than the supply.
Parameters
overflowThreshold
Returns
true if the resource supply is enough.
false if the resource supply is not enough.
Definition at line 627 of file PlacementInfo.h.
left()
float PlacementInfo::PlacementBinInfo::left () inline
return the left boundary of the bin
Returns
float
Definition at line 681 of file PlacementInfo.h.
Referenced by GeneralSpreader::expandFromABin(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
removeCell()
void PlacementInfo::PlacementBinInfo::removeCell (DesignInfo::DesignCell * cell, int occupationAdded) inline
remove a design cell from the bin
Parameters
cell
occupationAdded how many slots were occupied by the cell
we have to set the mutex locked during the process since we enable multi-threading in the placer.
Definition at line 476 of file PlacementInfo.h.
reset()
void PlacementInfo::PlacementBinInfo::reset () inline
Definition at line 493 of file PlacementInfo.h.
resetBinShrinkRatio()
void PlacementInfo::PlacementBinInfo::resetBinShrinkRatio () inline
Definition at line 524 of file PlacementInfo.h.
resetNoOverflowCounter()
void PlacementInfo::PlacementBinInfo::resetNoOverflowCounter () inline
Definition at line 741 of file PlacementInfo.h.
resetOverflowCounter()
void PlacementInfo::PlacementBinInfo::resetOverflowCounter () inline
Definition at line 745 of file PlacementInfo.h.
right()
float PlacementInfo::PlacementBinInfo::right () inline
return the right boundary of the bin
Returns
float
Definition at line 691 of file PlacementInfo.h.
Referenced by GeneralSpreader::expandFromABin(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
setClockRegionX()
void PlacementInfo::PlacementBinInfo::setClockRegionX (int _x) inline
Set the clock region X for this bin.
Parameters
_x
Definition at line 797 of file PlacementInfo.h.
setRequiredBinShrinkRatio()
void PlacementInfo::PlacementBinInfo::setRequiredBinShrinkRatio (float r) inline
Set the Required Bin Shrink Ratio for a bin.
For example, to resolve routing congestion, we will modify the default resource capacity of a bin
Parameters
r
Definition at line 541 of file PlacementInfo.h.
shrinkBinBy()
void PlacementInfo::PlacementBinInfo::shrinkBinBy (float r) inline
reduce the resource capacity by a given ratio
Parameters
r
Definition at line 509 of file PlacementInfo.h.
top()
float PlacementInfo::PlacementBinInfo::top () inline
return the top boundary of the bin
Returns
float
Definition at line 701 of file PlacementInfo.h.
Referenced by GeneralSpreader::expandFromABin(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
X()
int PlacementInfo::PlacementBinInfo::X () inline
return the column of the bin in the grid
Returns
int
Definition at line 671 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SpreadRegion().
Y()
int PlacementInfo::PlacementBinInfo::Y () inline
return the row of the bin in the grid
Returns
int
Definition at line 661 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SpreadRegion().
Member Data Documentation
binShrinkRatio
float PlacementInfo::PlacementBinInfo::binShrinkRatio = 1.0 private
Definition at line 819 of file PlacementInfo.h.
bottomY
const float PlacementInfo::PlacementBinInfo::bottomY private
Definition at line 825 of file PlacementInfo.h.
capacity
int PlacementInfo::PlacementBinInfo::capacity = 0 private
Definition at line 817 of file PlacementInfo.h.
cells
std::set<DesignInfo::DesignCell *> PlacementInfo::PlacementBinInfo::cells private
Definition at line 815 of file PlacementInfo.h.
clockRegionX
int PlacementInfo::PlacementBinInfo::clockRegionX = -1 private
Definition at line 838 of file PlacementInfo.h.
column
const int PlacementInfo::PlacementBinInfo::column private
Definition at line 829 of file PlacementInfo.h.
compatiblePlacementTable
CompatiblePlacementTable* PlacementInfo::PlacementBinInfo::compatiblePlacementTable private
Definition at line 814 of file PlacementInfo.h.
correspondingSites
std::vector<DeviceInfo::DeviceSite *> PlacementInfo::PlacementBinInfo::correspondingSites private
Definition at line 813 of file PlacementInfo.h.
eps
float PlacementInfo::PlacementBinInfo::eps = 1e-5 private
Definition at line 827 of file PlacementInfo.h.
leftX
const float PlacementInfo::PlacementBinInfo::leftX private
Definition at line 822 of file PlacementInfo.h.
mtx
std::mutex PlacementInfo::PlacementBinInfo::mtx private
Definition at line 836 of file PlacementInfo.h.
noOverflowCnt
int PlacementInfo::PlacementBinInfo::noOverflowCnt = 0 private
Definition at line 832 of file PlacementInfo.h.
overflowCnt
int PlacementInfo::PlacementBinInfo::overflowCnt = 0 private
Definition at line 831 of file PlacementInfo.h.
requiredBinShrinkRatio
float PlacementInfo::PlacementBinInfo::requiredBinShrinkRatio = 1.0 private
Definition at line 820 of file PlacementInfo.h.
rightX
const float PlacementInfo::PlacementBinInfo::rightX private
Definition at line 823 of file PlacementInfo.h.
row
const int PlacementInfo::PlacementBinInfo::row private
Definition at line 828 of file PlacementInfo.h.
sharedCellType
std::string PlacementInfo::PlacementBinInfo::sharedCellType private
Definition at line 812 of file PlacementInfo.h.
switchDemandForNets
float PlacementInfo::PlacementBinInfo::switchDemandForNets = 0.0 private
Definition at line 834 of file PlacementInfo.h.
switchSupplyForNets
float PlacementInfo::PlacementBinInfo::switchSupplyForNets = 0.0 private
Definition at line 835 of file PlacementInfo.h.
topY
const float PlacementInfo::PlacementBinInfo::topY private
Definition at line 824 of file PlacementInfo.h.
utilization
int PlacementInfo::PlacementBinInfo::utilization = 0 private
Definition at line 818 of file PlacementInfo.h.
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.cc