AMF-Placer: DeviceInfo Class Reference
DeviceInfo Class Reference
Information class related to FPGA device, including the details of BEL/Site/Tile/ClockRegion.
#include <DeviceInfo.h>
Classes
class ClockColumn
a column of site in clock region
class ClockRegion
class for clock regions on FPGA
class DeviceBEL
BEL(Basic Element of Logic), the smallest undividable element.
class DeviceElement
basic class of device element
class DeviceSite
Site class for site on device.
class DeviceTile
A tile is a combination of sites.
Public Types
enum DeviceElementType {
DeviceElementType_BEL = 0, DeviceElementType_Site, DeviceElementType_Tile, DeviceElementType_CLOCKREGION,
DeviceElementType_Device
}
types of the elements in a device
Public Member Functions
DeviceInfo (std::map< std::string, std::string > &JSONCfg, std::string _deviceName)
Construct a new Device Info object.
~DeviceInfo ()
void printStat (bool verbose=false)
void addBELTypes (std::string &strBELType)
add a BEL type into the set of the existing BEL types
void addBEL (std::string &BELName, std::string &BELType, DeviceSite *parentSite)
add a BEL element into the device information
void addSiteTypes (std::string &strSiteType)
add a Site type into the set of the existing site types
void addSite (std::string &siteName, std::string &siteType, float locx, float locy, int clockRegionX, int clockRegionY, DeviceTile *parentTile)
add a site into the device information class
void addTileTypes (std::string &strTileType)
void addTile (std::string &tileName, std::string &tileType)
std::string & getDeviceName ()
std::set< std::string > & getBELTypes ()
get BEL types in the device
DeviceBEL * getBELWithName (std::string &BELName)
get a BEL based on a given name
std::vector< DeviceBEL * > & getBELsInType (std::string &BELType)
get BELs of a specific type
std::set< std::string > & getSiteTypes ()
Get the Site Types in the device.
DeviceSite * getSiteWithName (std::string &siteName)
Get a site based on a given name.
std::vector< DeviceSite * > & getSitesInType (std::string &siteType)
Get sites of a specfic type.
std::set< std::string > & getTileTypes ()
Get the tile types in the device.
DeviceTile * getTileWithName (std::string &tileName)
Get a tile With name.
std::vector< DeviceTile * > & getTilesInType (std::string &tileType)
Get the tiles of a specific type.
void loadPCIEPinOffset (std::string specialPinOffsetFileName)
load the detailed location information of pins on PCIE IO slot
std::vector< DeviceBEL * > & getBELs ()
std::vector< DeviceSite * > & getSites ()
std::vector< DeviceTile * > & getTiles ()
DeviceBEL * getBEL (std::string &Name)
DeviceSite * getSite (std::string &Name)
DeviceTile * getTile (std::string &Name)
std::string getBELType2FalseBELType (std::string curBELType)
void loadBELType2FalseBELType (std::string curFileName)
load BEL type remapping information since some cell can be placed in sites of different sites. For cell spreading, we need to remap some BEL types to a unified BEL types. Belows are some examples:
void resetAllSiteMapping ()
remove the mapped flags for all sites without fixed elements
void mapClockRegionToArray ()
map recognized clock regions into an array for later clock utilization evaluation
float getBoundaryTolerance ()
void getClockRegionByLocation (float locX, float locY, int &clockRegionX, int &clockRegionY)
Get the clock region ID (X/Y) by a given location (X/Y)
int getClockRegionNumX ()
Get the number of columns of the clock region array.
int getClockRegionNumY ()
Get the number of rows of the clock region array.
void recordClockRelatedCell (float locX, float locY, int regionX, int regionY, int cellId, int netId)
record the information of cell in a specific clock region
int getMaxUtilizationOfClockColumns_InClockRegion (int regionX, int regionY)
Get the maximum utilization among the clock columns in clock region.
std::vector< std::vector< ClockRegion * > > & getClockRegions ()
std::vector< ClockColumn * > & getClockColumns ()
Private Attributes
std::string deviceName
std::set< std::string > BELTypes
std::map< std::string, std::vector< DeviceBEL * > > BELType2BELs
std::vector< DeviceBEL * > BELs
std::set< std::string > siteTypes
std::map< std::string, std::vector< DeviceSite * > > siteType2Sites
std::vector< DeviceSite * > sites
std::set< std::string > tileTypes
std::map< std::string, std::vector< DeviceTile * > > tileType2Tiles
std::vector< DeviceTile * > tiles
std::map< std::string, std::string > BELType2FalseBELType
std::map< std::string, DeviceBEL * > name2BEL
std::map< std::string, DeviceSite * > name2Site
std::map< std::string, DeviceTile * > name2Tile
std::map< std::pair< int, int >, ClockRegion * > coord2ClockRegion
std::vector< std::vector< ClockRegion * > > clockRegions
std::vector< ClockColumn * > clockColumns
std::vector< float > clockRegionXBounds
std::vector< float > clockRegionYBounds
std::map< std::string, std::string > & JSONCfg
std::string deviceArchievedTextFileName
std::string specialPinOffsetFileName
float boundaryTolerance = 0.5
int clockRegionNumX = 1
int clockRegionNumY = 1
Detailed Description
Information class related to FPGA device, including the details of BEL/Site/Tile/ClockRegion.
Definition at line 30 of file DeviceInfo.h.
Member Enumeration Documentation
DeviceElementType
enum DeviceInfo::DeviceElementType
types of the elements in a device
Enumerator
DeviceElementType_BEL
DeviceElementType_Site
DeviceElementType_Tile
DeviceElementType_CLOCKREGION
DeviceElementType_Device
Definition at line 37 of file DeviceInfo.h.
Constructor & Destructor Documentation
DeviceInfo()
DeviceInfo::DeviceInfo (std::map< std::string, std::string > & JSONCfg, std::string _deviceName)
Construct a new Device Info object.
Parameters
JSONCfg user configuration JSON mapping
_deviceName device file name
The device information file will contain information like the text shown below
 site=> SLICE_X59Y220 tile=> CLEL_R_X36Y220 sitetype=> SLICEL tiletype=> CLE_R centerx=> 37.25 centery=> 220.15
 BELs=> [SLICE_X59Y220/A5LUT,SLICE_X59Y220/A6LUT,SLICE_X59Y220/AFF,SLICE_X59Y220/AFF2,SLICE_X59Y220/B5LUT,SLICE_X59Y220/B6LUT,SLICE_X59Y220/BFF,SLICE_X59Y220/BFF2,SLICE_X59Y220/C5LUT,SLICE_X59Y220/C6LUT,SLICE_X59Y220/CARRY8,SLICE_X59Y220/CFF,SLICE_X59Y220/CFF2,SLICE_X59Y220/D5LUT,SLICE_X59Y220/D6LUT,SLICE_X59Y220/DFF,SLICE_X59Y220/DFF2,SLICE_X59Y220/E5LUT,SLICE_X59Y220/E6LUT,SLICE_X59Y220/EFF,SLICE_X59Y220/EFF2,SLICE_X59Y220/F5LUT,SLICE_X59Y220/F6LUT,SLICE_X59Y220/F7MUX_AB,SLICE_X59Y220/F7MUX_CD,SLICE_X59Y220/F7MUX_EF,SLICE_X59Y220/F7MUX_GH,SLICE_X59Y220/F8MUX_BOT,SLICE_X59Y220/F8MUX_TOP,SLICE_X59Y220/F9MUX,SLICE_X59Y220/FFF,SLICE_X59Y220/FFF2,SLICE_X59Y220/G5LUT,SLICE_X59Y220/G6LUT,SLICE_X59Y220/GFF,SLICE_X59Y220/GFF2,SLICE_X59Y220/H5LUT,SLICE_X59Y220/H6LUT,SLICE_X59Y220/HFF,SLICE_X59Y220/HFF2]
 site=> RAMB18_X7Y88 tile=> BRAM_X36Y220 sitetype=> RAMBFIFO18 tiletype=> CLE_R centerx=> 36.75 centery=> 221.96249999999998
 BELs=> [RAMB18_X7Y88/RAMBFIFO18] site=> RAMB18_X7Y89 tile=> BRAM_X36Y220 sitetype=> RAMB181
 tiletype=> CLE_R centerx=> 36.75 centery=> 224.11249999999998 BELs=> [RAMB18_X7Y89/RAMB18E2_U]
Definition at line 32 of file DeviceInfo.cc.
~DeviceInfo()
DeviceInfo::~DeviceInfo () inline
Definition at line 903 of file DeviceInfo.h.
Member Function Documentation
addBEL()
void DeviceInfo::addBEL (std::string & BELName, std::string & BELType, DeviceSite * parentSite)
add a BEL element into the device information
Parameters
BELName
BELType
parentSite
Definition at line 506 of file DeviceInfo.cc.
Referenced by addBELTypes(), and DeviceInfo().
addBELTypes()
void DeviceInfo::addBELTypes (std::string & strBELType) inline
add a BEL type into the set of the existing BEL types
Parameters
strBELType
Definition at line 920 of file DeviceInfo.h.
Referenced by addBEL().
addSite()
void DeviceInfo::addSite (std::string & siteName, std::string & siteType, float locx, float locy, int clockRegionX, int clockRegionY, DeviceTile * parentTile)
add a site into the device information class
Parameters
siteName site name string
siteType site type string
locx the location (X) of the site on the device
locy the location (Y) of the site on the device
clockRegionX the clock region ID X of the site
clockRegionY the clock region ID Y of the site
parentTile parent tile of this site
Definition at line 523 of file DeviceInfo.cc.
Referenced by addSiteTypes(), and DeviceInfo().
addSiteTypes()
void DeviceInfo::addSiteTypes (std::string & strSiteType) inline
add a Site type into the set of the existing site types
Parameters
strSiteType
Definition at line 939 of file DeviceInfo.h.
Referenced by addSite().
addTile()
void DeviceInfo::addTile (std::string & tileName, std::string & tileType)
Definition at line 542 of file DeviceInfo.cc.
Referenced by addTileTypes(), and DeviceInfo().
addTileTypes()
void DeviceInfo::addTileTypes (std::string & strTileType) inline
Definition at line 958 of file DeviceInfo.h.
Referenced by addTile().
getBEL()
DeviceBEL* DeviceInfo::getBEL (std::string & Name) inline
Definition at line 1094 of file DeviceInfo.h.
getBELs()
std::vector<DeviceBEL *>& DeviceInfo::getBELs () inline
Definition at line 1081 of file DeviceInfo.h.
getBELsInType()
std::vector<DeviceBEL *>& DeviceInfo::getBELsInType (std::string & BELType) inline
get BELs of a specific type
Parameters
BELType the target BEL type
Returns
std::vector<DeviceBEL *>&
Definition at line 997 of file DeviceInfo.h.
getBELType2FalseBELType()
std::string DeviceInfo::getBELType2FalseBELType (std::string curBELType) inline
Definition at line 1110 of file DeviceInfo.h.
Referenced by PlacementInfo::getBELType2FalseBELType(), and PlacementInfo::CompatiblePlacementTable::setBELTypeForCells().
getBELTypes()
std::set<std::string>& DeviceInfo::getBELTypes () inline
get BEL types in the device
Returns
std::set<std::string>&
Definition at line 974 of file DeviceInfo.h.
Referenced by PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable().
getBELWithName()
DeviceBEL* DeviceInfo::getBELWithName (std::string & BELName) inline
get a BEL based on a given name
Parameters
BELName
Returns
DeviceBEL*
Definition at line 985 of file DeviceInfo.h.
getBoundaryTolerance()
float DeviceInfo::getBoundaryTolerance () inline
Definition at line 1158 of file DeviceInfo.h.
Referenced by PlacementInfo::createGridBins().
getClockColumns()
std::vector<ClockColumn *>& DeviceInfo::getClockColumns () inline
Definition at line 1249 of file DeviceInfo.h.
Referenced by mapClockRegionToArray(), and ParallelCLBPacker::ParallelCLBPacker().
getClockRegionByLocation()
void DeviceInfo::getClockRegionByLocation (float locX, float locY, int & clockRegionX, int & clockRegionY) inline
Get the clock region ID (X/Y) by a given location (X/Y)
Parameters
locX
locY
clockRegionX
clockRegionY
Definition at line 1171 of file DeviceInfo.h.
Referenced by PlacementInfo::adjustLUTFFUtilization_Clocking(), PlacementInfo::checkClockUtilization(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementInfo::enhanceRiskyClockNet(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), ParallelCLBPacker::findNeiborSitesFromBinGrid(), PlacementTimingOptimizer::getDelayByModel_conservative(), and PlacementTimingOptimizer::stretchClockRegionColumns().
getClockRegionNumX()
int DeviceInfo::getClockRegionNumX () inline
Get the number of columns of the clock region array.
Returns
int
Definition at line 1205 of file DeviceInfo.h.
Referenced by PlacementInfo::adjustLUTFFUtilization_Clocking(), PlacementInfo::checkClockUtilization(), PlacementInfo::dumpOverflowClockUtilization(), and ClusterPlacer::isDensePlacement().
getClockRegionNumY()
int DeviceInfo::getClockRegionNumY () inline
Get the number of rows of the clock region array.
Returns
int
Definition at line 1215 of file DeviceInfo.h.
Referenced by PlacementInfo::adjustLUTFFUtilization_Clocking(), PlacementInfo::checkClockUtilization(), PlacementInfo::dumpOverflowClockUtilization(), and ClusterPlacer::isDensePlacement().
getClockRegions()
std::vector<std::vector<ClockRegion *> >& DeviceInfo::getClockRegions () inline
Definition at line 1244 of file DeviceInfo.h.
Referenced by PlacementInfo::adjustLUTFFUtilization_Clocking(), PlacementInfo::checkClockUtilization(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementInfo::dumpOverflowClockUtilization(), PlacementInfo::PlacementInfo(), PlacementTimingOptimizer::stretchClockRegionColumns(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and WirelengthOptimizer::updatePseudoNetForClockRegion().
getDeviceName()
std::string& DeviceInfo::getDeviceName () inline
Definition at line 964 of file DeviceInfo.h.
getMaxUtilizationOfClockColumns_InClockRegion()
int DeviceInfo::getMaxUtilizationOfClockColumns_InClockRegion (int regionX, int regionY) inline
Get the maximum utilization among the clock columns in clock region.
Parameters
regionX clock region ID X
regionY clock region ID Y
Returns
int
Definition at line 1239 of file DeviceInfo.h.
Referenced by PlacementInfo::checkClockUtilization().
getSite()
DeviceSite* DeviceInfo::getSite (std::string & Name) inline
Definition at line 1099 of file DeviceInfo.h.
Referenced by InitialPacker::loadFixedPlacementUnits(), and PlacementInfo::PlacementUnpackedCell::setLockedAt().
getSites()
std::vector<DeviceSite *>& DeviceInfo::getSites () inline
Definition at line 1085 of file DeviceInfo.h.
Referenced by PlacementInfo::createGridBins(), DeviceInfo::ClockRegion::mapSiteToClockColumns(), and PlacementInfo::PlacementInfo().
getSitesInType()
std::vector<DeviceSite *>& DeviceInfo::getSitesInType (std::string & siteType) inline
Get sites of a specfic type.
Parameters
siteType
Returns
std::vector<DeviceSite *>&
Definition at line 1031 of file DeviceInfo.h.
Referenced by PlacementInfo::createGridBins(), PlacementInfo::createSiteBinGrid(), DesignInfo::DesignInfo(), MacroLegalizer::findMacroType2AvailableSites(), CLBLegalizer::findSiteType2AvailableSites(), loadPCIEPinOffset(), and ParallelCLBPacker::ParallelCLBPacker().
getSiteTypes()
std::set<std::string>& DeviceInfo::getSiteTypes () inline
Get the Site Types in the device.
Returns
std::set<std::string>&
Definition at line 1008 of file DeviceInfo.h.
getSiteWithName()
DeviceSite* DeviceInfo::getSiteWithName (std::string & siteName) inline
Get a site based on a given name.
Parameters
siteName
Returns
DeviceSite*
Definition at line 1019 of file DeviceInfo.h.
Referenced by InitialPacker::loadOtherCLBMacros(), and PlacementInfo::loadPlacementUnitInformation().
getTile()
DeviceTile* DeviceInfo::getTile (std::string & Name) inline
Definition at line 1104 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::mapSiteToClockColumns().
getTiles()
std::vector<DeviceTile *>& DeviceInfo::getTiles () inline
Definition at line 1089 of file DeviceInfo.h.
getTilesInType()
std::vector<DeviceTile *>& DeviceInfo::getTilesInType (std::string & tileType) inline
Get the tiles of a specific type.
Parameters
tileType
Returns
std::vector<DeviceTile *>&
Definition at line 1065 of file DeviceInfo.h.
getTileTypes()
std::set<std::string>& DeviceInfo::getTileTypes () inline
Get the tile types in the device.
Returns
std::set<std::string>&
Definition at line 1042 of file DeviceInfo.h.
getTileWithName()
DeviceTile* DeviceInfo::getTileWithName (std::string & tileName) inline
Get a tile With name.
Parameters
tileName
Returns
DeviceTile*
Definition at line 1053 of file DeviceInfo.h.
loadBELType2FalseBELType()
void DeviceInfo::loadBELType2FalseBELType (std::string curFileName)
load BEL type remapping information since some cell can be placed in sites of different sites. For cell spreading, we need to remap some BEL types to a unified BEL types. Belows are some examples:
SLICEM_CARRY8 => SLICEL_CARRY8
SLICEM_LUT => SLICEL_LUT
SLICEM_FF => SLICEL_FF
Parameters
curFileName
Definition at line 558 of file DeviceInfo.cc.
Referenced by DeviceInfo(), and getBELType2FalseBELType().
loadPCIEPinOffset()
void DeviceInfo::loadPCIEPinOffset (std::string specialPinOffsetFileName)
load the detailed location information of pins on PCIE IO slot
PCIE I/O is a long slot which contains pins at various location so we cannot ignore the pin location on the PCIE BEL!
Parameters
specialPinOffsetFileName a file name which records these information
Definition at line 382 of file DeviceInfo.cc.
Referenced by DeviceInfo(), and getTilesInType().
mapClockRegionToArray()
void DeviceInfo::mapClockRegionToArray ()
map recognized clock regions into an array for later clock utilization evaluation
Definition at line 160 of file DeviceInfo.cc.
Referenced by DeviceInfo(), and resetAllSiteMapping().
printStat()
void DeviceInfo::printStat (bool verbose = false)
Definition at line 454 of file DeviceInfo.cc.
Referenced by AMFPlacer::AMFPlacer(), and ~DeviceInfo().
recordClockRelatedCell()
void DeviceInfo::recordClockRelatedCell (float locX, float locY, int regionX, int regionY, int cellId, int netId)
record the information of cell in a specific clock region
Parameters
locX cell location X
locY cell location Y
regionX clock region ID X
regionY clock region ID Y
cellId target cell ID
netId clock net ID
Definition at line 376 of file DeviceInfo.cc.
Referenced by PlacementInfo::checkClockUtilization(), and getClockRegionNumY().
resetAllSiteMapping()
void DeviceInfo::resetAllSiteMapping () inline
remove the mapped flags for all sites without fixed elements
Definition at line 1141 of file DeviceInfo.h.
Referenced by GlobalPlacer::macroLegalize().
Member Data Documentation
BELs
std::vector<DeviceBEL *> DeviceInfo::BELs private
Definition at line 1258 of file DeviceInfo.h.
Referenced by addBEL(), DeviceInfo(), getBELs(), printStat(), and ~DeviceInfo().
BELType2BELs
std::map<std::string, std::vector<DeviceBEL *> > DeviceInfo::BELType2BELs private
Definition at line 1257 of file DeviceInfo.h.
Referenced by addBEL(), DeviceInfo(), getBELsInType(), and printStat().
BELType2FalseBELType
std::map<std::string, std::string> DeviceInfo::BELType2FalseBELType private
Definition at line 1268 of file DeviceInfo.h.
Referenced by DeviceInfo(), getBELType2FalseBELType(), and loadBELType2FalseBELType().
BELTypes
std::set<std::string> DeviceInfo::BELTypes private
Definition at line 1256 of file DeviceInfo.h.
Referenced by addBELTypes(), DeviceInfo(), getBELTypes(), and printStat().
boundaryTolerance
float DeviceInfo::boundaryTolerance = 0.5 private
Definition at line 1284 of file DeviceInfo.h.
Referenced by getBoundaryTolerance(), and mapClockRegionToArray().
clockColumns
std::vector<ClockColumn *> DeviceInfo::clockColumns private
Definition at line 1276 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::addClockAndCell(), DeviceInfo::ClockRegion::ClockRegion(), DeviceInfo::ClockRegion::getClockColumns(), getClockColumns(), DeviceInfo::ClockRegion::getMaxUtilizationClockColumnsPtr(), DeviceInfo::ClockRegion::getMaxUtilizationOfClockColumns(), mapClockRegionToArray(), DeviceInfo::ClockRegion::mapSiteToClockColumns(), DeviceInfo::ClockRegion::resetClockUtilizationInfo(), and DeviceInfo::ClockRegion::~ClockRegion().
clockRegionNumX
int DeviceInfo::clockRegionNumX = 1 private
Definition at line 1285 of file DeviceInfo.h.
Referenced by DeviceInfo(), getClockRegionByLocation(), getClockRegionNumX(), and mapClockRegionToArray().
clockRegionNumY
int DeviceInfo::clockRegionNumY = 1 private
Definition at line 1286 of file DeviceInfo.h.
Referenced by DeviceInfo(), getClockRegionByLocation(), getClockRegionNumY(), and mapClockRegionToArray().
clockRegions
std::vector<std::vector<ClockRegion *> > DeviceInfo::clockRegions private
Definition at line 1275 of file DeviceInfo.h.
Referenced by getClockRegions(), getMaxUtilizationOfClockColumns_InClockRegion(), mapClockRegionToArray(), and recordClockRelatedCell().
clockRegionXBounds
std::vector<float> DeviceInfo::clockRegionXBounds private
Definition at line 1277 of file DeviceInfo.h.
Referenced by getClockRegionByLocation(), and mapClockRegionToArray().
clockRegionYBounds
std::vector<float> DeviceInfo::clockRegionYBounds private
Definition at line 1278 of file DeviceInfo.h.
Referenced by getClockRegionByLocation(), and mapClockRegionToArray().
coord2ClockRegion
std::map<std::pair<int, int>, ClockRegion *> DeviceInfo::coord2ClockRegion private
Definition at line 1274 of file DeviceInfo.h.
Referenced by DeviceInfo(), and mapClockRegionToArray().
deviceArchievedTextFileName
std::string DeviceInfo::deviceArchievedTextFileName private
Definition at line 1281 of file DeviceInfo.h.
Referenced by DeviceInfo().
deviceName
std::string DeviceInfo::deviceName private
Definition at line 1255 of file DeviceInfo.h.
Referenced by DeviceInfo(), and getDeviceName().
JSONCfg
std::map<std::string, std::string>& DeviceInfo::JSONCfg private
Definition at line 1280 of file DeviceInfo.h.
name2BEL
std::map<std::string, DeviceBEL *> DeviceInfo::name2BEL private
Definition at line 1270 of file DeviceInfo.h.
Referenced by addBEL(), getBEL(), and getBELWithName().
name2Site
std::map<std::string, DeviceSite *> DeviceInfo::name2Site private
Definition at line 1271 of file DeviceInfo.h.
Referenced by addSite(), DeviceInfo(), getSite(), and getSiteWithName().
name2Tile
std::map<std::string, DeviceTile *> DeviceInfo::name2Tile private
Definition at line 1272 of file DeviceInfo.h.
Referenced by addTile(), DeviceInfo(), getTile(), and getTileWithName().
sites
std::vector<DeviceSite *> DeviceInfo::sites private
Definition at line 1262 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockColumn::addSite(), DeviceInfo::ClockRegion::addSite(), addSite(), DeviceInfo::ClockColumn::ClockColumn(), DeviceInfo::ClockRegion::ClockRegion(), DeviceInfo(), DeviceInfo::ClockColumn::getSites(), getSites(), DeviceInfo::ClockRegion::mapSiteToClockColumns(), printStat(), resetAllSiteMapping(), DeviceInfo::ClockColumn::~ClockColumn(), DeviceInfo::ClockRegion::~ClockRegion(), and ~DeviceInfo().
siteType2Sites
std::map<std::string, std::vector<DeviceSite *> > DeviceInfo::siteType2Sites private
Definition at line 1261 of file DeviceInfo.h.
Referenced by addSite(), DeviceInfo(), getSitesInType(), and printStat().
siteTypes
std::set<std::string> DeviceInfo::siteTypes private
Definition at line 1260 of file DeviceInfo.h.
Referenced by addSiteTypes(), DeviceInfo(), getSiteTypes(), and printStat().
specialPinOffsetFileName
std::string DeviceInfo::specialPinOffsetFileName private
Definition at line 1282 of file DeviceInfo.h.
Referenced by DeviceInfo(), and getTilesInType().
tiles
std::vector<DeviceTile *> DeviceInfo::tiles private
Definition at line 1266 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::addSite(), addTile(), DeviceInfo::ClockRegion::ClockRegion(), DeviceInfo(), getTiles(), printStat(), and ~DeviceInfo().
tileType2Tiles
std::map<std::string, std::vector<DeviceTile *> > DeviceInfo::tileType2Tiles private
Definition at line 1265 of file DeviceInfo.h.
Referenced by addTile(), DeviceInfo(), getTilesInType(), and printStat().
tileTypes
std::set<std::string> DeviceInfo::tileTypes private
Definition at line 1264 of file DeviceInfo.h.
Referenced by addTileTypes(), DeviceInfo(), getTileTypes(), and printStat().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/deviceInfo/DeviceInfo.h
src/lib/HiFPlacer/deviceInfo/DeviceInfo.cc