AMF-Placer: DesignInfo::DesignCell Class Reference
DesignInfo::DesignCell Class Reference
a DesignCell in design netlist, DesignPin objects of which might connect to DesignNet objects
#include <DesignInfo.h>
Public Member Functions
DesignCell (const std::string &name, DesignElement *parentPtr, DesignCellType cellType, int id)
Construct a new Design Cell object.
DesignCell (const std::string &name, DesignCellType cellType, int id)
Construct a new Design Cell object.
DesignCell (bool isVirtual, DesignCellType cellType, int id)
Construct a new Design Cell object without given name. The cell name will be its id string.
DesignCell (bool isVirtual, const std::string &name, DesignCellType cellType, int id)
Construct a new Design Cell object.
~DesignCell ()
Destroy the Design Cell object and its binded DesignPin objects.
DesignCellType getCellType ()
void addPin (DesignPin *_pinPtr)
bind a pin to the cell
std::vector< DesignPin * > & getPins ()
void addNetForPin (DesignPin *_pinPtr, DesignNet *_netPtr)
add a net and assign it into output/input net list
std::vector< DesignNet * > & getOutputNets ()
std::vector< DesignNet * > & getInputNets ()
std::vector< DesignPin * > & getOutputPins ()
std::vector< DesignPin * > & getInputPins ()
bool isLUT6 ()
bool isLUT ()
bool isFF ()
bool isLUTRAM ()
bool originallyIsLUTRAM ()
bool isBRAM ()
bool isMux ()
bool isCarry ()
bool isShift ()
bool isDSP ()
bool checkHasDSPReg ()
bool isIO ()
bool isClockBuffer ()
bool isShifter ()
bool isTimingEndPoint ()
check whether the cell is an endpoint in timing graph
bool isLogicRelated ()
check whether the cell is related to logic computation
int getCellId ()
Get the Cell Id in the cell list.
bool isVirtualCell ()
ControlSetInfo * getControlSetInfo ()
Get the Control Set Info object of this cell.
void setControlSetInfo (ControlSetInfo *_controlSetInfo)
Set the Control Set Info object of this cell.
void setVirtualType (DesignCellType NewCellType)
Set the Virtual Type object which might override the actual type in later processing.
DesignCellType getOriCellType ()
Get the Original Cell Type object defined in the design netlist.
void addClockNet (DesignNet *aClockNet)
add a clock net which is connected to this cell for later legalization
std::set< DesignNet * > & getClockNets ()
Get the clock nets connected to this cell for later legalization.
void setHasDSPReg (bool _hasDSPReg)
void setTimingLength (int _timingLength)
int getTimingLength ()
Public Member Functions inherited from DesignInfo::DesignElement
DesignElement (const std::string &name, DesignElement *parentPtr, DesignElementType type, int id)
DesignElement (const std::string &name, DesignElementType type, int id)
DesignElement (bool isVirtual, DesignElementType type, int id)
DesignElement (bool isVirtual, const std::string &_name, DesignElementType type, int id)
virtual ~DesignElement ()
const std::string & getName () const
DesignElement * getParentPtr ()
DesignElementType getElementType ()
int getElementIdInType ()
Private Attributes
std::vector< DesignPin * > pinPtrs
std::vector< DesignPin * > inputPinPtrs
std::vector< DesignPin * > outputPinPtrs
std::vector< std::string > pinNames
std::vector< DesignNet * > netPtrs
std::vector< DesignNet * > inputNetPtrs
std::vector< DesignNet * > outputNetPtrs
std::set< DesignNet * > clockNetPtrs
std::vector< std::string > netNames
DesignCellType cellType
DesignCellType oriCellType
bool isVirtual = false
bool hasDSPReg = false
ControlSetInfo * controlSetInfo = nullptr
int timingLength = 0
Detailed Description
a DesignCell in design netlist, DesignPin objects of which might connect to DesignNet objects
Definition at line 769 of file DesignInfo.h.
Constructor & Destructor Documentation
DesignCell() [1/4]
DesignInfo::DesignCell::DesignCell (const std::string & name, DesignElement * parentPtr, DesignCellType cellType, int id) inline
Construct a new Design Cell object.
Parameters
name the name of the cell
parentPtr the hierarchy parent of the design cell
cellType the design cell type (NOT resourse BEL type!)
id the id of cell in the cell list
Definition at line 780 of file DesignInfo.h.
DesignCell() [2/4]
DesignInfo::DesignCell::DesignCell (const std::string & name, DesignCellType cellType, int id) inline
Construct a new Design Cell object.
Parameters
name the name of the cell
cellType the design cell type (NOT resourse BEL type!)
id the id of cell in the cell list
Definition at line 800 of file DesignInfo.h.
DesignCell() [3/4]
DesignInfo::DesignCell::DesignCell (bool isVirtual, DesignCellType cellType, int id) inline
Construct a new Design Cell object without given name. The cell name will be its id string.
Parameters
isVirtual indicate whether the cell is a virtual one not in the design netlist
cellType the design cell type (NOT resourse BEL type!)
id the id of cell in the cell list
Definition at line 821 of file DesignInfo.h.
DesignCell() [4/4]
DesignInfo::DesignCell::DesignCell (bool isVirtual, const std::string & name, DesignCellType cellType, int id) inline
Construct a new Design Cell object.
Parameters
isVirtual indicate whether the cell is a virtual one not in the design netlist
name the name of the cell
cellType the design cell type (NOT resourse BEL type!)
id the id of cell in the cell list
Definition at line 844 of file DesignInfo.h.
~DesignCell()
DesignInfo::DesignCell::~DesignCell () inline
Destroy the Design Cell object and its binded DesignPin objects.
Definition at line 863 of file DesignInfo.h.
Member Function Documentation
addClockNet()
void DesignInfo::DesignCell::addClockNet (DesignNet * aClockNet) inline
add a clock net which is connected to this cell for later legalization
Parameters
aClockNet
Definition at line 1087 of file DesignInfo.h.
addNetForPin()
void DesignInfo::DesignCell::addNetForPin (DesignPin * _pinPtr, DesignNet * _netPtr)
add a net and assign it into output/input net list
Parameters
_pinPtr
_netPtr
Definition at line 84 of file DesignInfo.cc.
Referenced by DesignInfo::DesignPin::updateParentCellNetInfo().
addPin()
void DesignInfo::DesignCell::addPin (DesignPin * _pinPtr)
bind a pin to the cell
Parameters
_pinPtr
Definition at line 105 of file DesignInfo.cc.
Referenced by DesignInfo::DesignInfo().
checkHasDSPReg()
bool DesignInfo::DesignCell::checkHasDSPReg () inline
Definition at line 963 of file DesignInfo.h.
getCellId()
int DesignInfo::DesignCell::getCellId () inline
Get the Cell Id in the cell list.
Returns
int
Definition at line 1025 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT(), PlacementInfo::adjustLUTFFUtilization_Packablity(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack(), IncrementalBELPacker::FFPairing(), MacroLegalizer::findMacroCell2SitesInDistance(), PlacementInfo::findNeiborLUTFFsFromBinGrid(), PlacementInfo::findNeiborSiteFromBinGrid(), CLBLegalizer::findPU2SitesInDistance(), PlacementInfo::CompatiblePlacementTable::getActualOccupation(), DesignInfo::getFFControlSetId(), PlacementInfo::CompatiblePlacementTable::getInflateRatio(), PlacementInfo::getPlacementUnitByCell(), PlacementInfo::CompatiblePlacementTable::getPotentialBELTypeIDs(), PlacementInfo::getPULocationByCellLocation(), PlacementTimingOptimizer::getWorstSlackOfCell(), PlacementInfo::isLegalLocation(), IncrementalBELPacker::LUTFFPairing(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), operator<<(), WirelengthOptimizer::reloadPlacementInfo(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), PlacementInfo::updateElementBinGrid(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocationsWorker().
getCellType()
DesignCellType DesignInfo::DesignCell::getCellType () inline
Definition at line 869 of file DesignInfo.h.
Referenced by DesignInfo::addCell(), InitialPacker::BFSExpandViaSpecifiedPorts(), IncrementalBELPacker::FFPairing(), InitialPacker::findMuxMacros(), PlacementInfo::findNeiborSiteFromBinGrid(), IncrementalBELPacker::LUTFFPairing(), and operator<<().
getClockNets()
std::set< DesignNet * > & DesignInfo::DesignCell::getClockNets () inline
Get the clock nets connected to this cell for later legalization.
Returns
std::vector<DesignNet *>&
Definition at line 1097 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
getControlSetInfo()
ControlSetInfo * DesignInfo::DesignCell::getControlSetInfo () inline
Get the Control Set Info object of this cell.
A control set is a combination of CLK, CE and SR signal. It could be nullptr (not related to control set)
Returns
ControlSetInfo*
Definition at line 1042 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), InitialPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::addLUTFFPair(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), and ParallelCLBPacker::PackingCLBSite::SiteBELMapping::canDirectConnectInSlot().
getInputNets()
std::vector< DesignNet * > & DesignInfo::DesignCell::getInputNets () inline
Definition at line 898 of file DesignInfo.h.
getInputPins()
std::vector< DesignPin * > & DesignInfo::DesignCell::getInputPins () inline
Definition at line 906 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT(), canLUTPacked(), DesignInfo::ControlSetInfo::compatibleWith(), InitialPacker::findMuxMacros(), DesignInfo::getCLKSRCENet(), DesignInfo::getCLKSRCENetId(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPairPinNum(), ParallelCLBPacker::PackingCLBSite::getPairPinNum(), PlacementInfo::getPairPinNum(), and DesignInfo::ControlSetInfo::setControlSetInfoAs().
getOriCellType()
DesignCellType DesignInfo::DesignCell::getOriCellType () inline
Get the Original Cell Type object defined in the design netlist.
Returns
DesignCellType
Definition at line 1077 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), ParallelCLBPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), DesignInfo::ControlSetInfo::compatibleWith(), hasLUT62(), isLUT6(), InitialPacker::mapCarryRelatedRouteThru(), and DesignInfo::ControlSetInfo::setControlSetInfoAs().
getOutputNets()
std::vector< DesignNet * > & DesignInfo::DesignCell::getOutputNets () inline
Definition at line 894 of file DesignInfo.h.
Referenced by InitialPacker::BFSExpandViaSpecifiedPorts(), and PlacementTimingOptimizer::getWorstSlackOfCell().
getOutputPins()
std::vector< DesignPin * > & DesignInfo::DesignCell::getOutputPins () inline
Definition at line 902 of file DesignInfo.h.
Referenced by IncrementalBELPacker::LUTFFPairing().
getPins()
std::vector< DesignPin * > & DesignInfo::DesignCell::getPins () inline
Definition at line 881 of file DesignInfo.h.
Referenced by IncrementalBELPacker::FFPairing(), and IncrementalBELPacker::LUTFFPairing().
getTimingLength()
int DesignInfo::DesignCell::getTimingLength () inline
Definition at line 1112 of file DesignInfo.h.
isBRAM()
bool DesignInfo::DesignCell::isBRAM () inline
Definition at line 942 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), GlobalPlacer::dumpBRAMCoordinate(), isLogicRelated(), isTimingEndPoint(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
isCarry()
bool DesignInfo::DesignCell::isCarry () inline
Definition at line 951 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), GlobalPlacer::dumpCARRYCoordinate(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
isClockBuffer()
bool DesignInfo::DesignCell::isClockBuffer () inline
Definition at line 986 of file DesignInfo.h.
Referenced by isTimingEndPoint().
isDSP()
bool DesignInfo::DesignCell::isDSP () inline
Definition at line 959 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), GlobalPlacer::dumpDSPCoordinate(), isLogicRelated(), isTimingEndPoint(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
isFF()
bool DesignInfo::DesignCell::isFF () inline
Definition at line 921 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::adjustLUTFFUtilization_Packablity(), DesignInfo::DesignPin::checkPinType(), GlobalPlacer::dumpFFCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), DesignInfo::getCLKSRCENet(), DesignInfo::getCLKSRCENetId(), DesignInfo::getFFControlSetId(), ParallelCLBPacker::PackingCLBSite::getFFSlot(), isLogicRelated(), isTimingEndPoint(), IncrementalBELPacker::LUTFFPairing(), PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell(), and PlacementInfo::updateElementBinGrid().
isIO()
bool DesignInfo::DesignCell::isIO () inline
Definition at line 967 of file DesignInfo.h.
Referenced by isTimingEndPoint().
isLogicRelated()
bool DesignInfo::DesignCell::isLogicRelated () inline
check whether the cell is related to logic computation
Returns
true
false
Definition at line 1015 of file DesignInfo.h.
isLUT()
bool DesignInfo::DesignCell::isLUT () inline
Definition at line 915 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), PlacementInfo::adjustLUTFFUtilization_Packablity(), canLUTPacked(), DesignInfo::DesignPin::checkPinType(), GlobalPlacer::dumpLUTCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), InitialPacker::findCARRYMacros(), PlacementInfo::findNeiborLUTFFsFromBinGrid(), ParallelCLBPacker::PackingCLBSite::getLUTSlot(), isLogicRelated(), IncrementalBELPacker::isLUTsPackable(), IncrementalBELPacker::LUTFFPairing(), PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell(), and PlacementInfo::updateElementBinGrid().
isLUT6()
bool DesignInfo::DesignCell::isLUT6 () inline
Definition at line 911 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addLUT(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::addLUTFFPair(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::canDirectConnectInSlot(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPairPinNum(), ParallelCLBPacker::PackingCLBSite::getPairPinNum(), PlacementInfo::getPairPinNum(), IncrementalBELPacker::isLUTsPackable(), and InitialPacker::mapCarryRelatedRouteThru().
isLUTRAM()
bool DesignInfo::DesignCell::isLUTRAM () inline
Definition at line 926 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), isLogicRelated(), isTimingEndPoint(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
isMux()
bool DesignInfo::DesignCell::isMux () inline
Definition at line 947 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), InitialPacker::findMuxMacros(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
isShift()
bool DesignInfo::DesignCell::isShift () inline
Definition at line 955 of file DesignInfo.h.
isShifter()
bool DesignInfo::DesignCell::isShifter () inline
Definition at line 992 of file DesignInfo.h.
Referenced by isLogicRelated(), and isTimingEndPoint().
isTimingEndPoint()
bool DesignInfo::DesignCell::isTimingEndPoint () inline
check whether the cell is an endpoint in timing graph
Returns
true
false
Definition at line 1003 of file DesignInfo.h.
isVirtualCell()
bool DesignInfo::DesignCell::isVirtualCell () inline
Definition at line 1030 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::addCarry(), PlacementInfo::PlacementMacro::addCell(), InitialPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack(), hasLUT62(), and InitialPacker::mapCarryRelatedRouteThru().
originallyIsLUTRAM()
bool DesignInfo::DesignCell::originallyIsLUTRAM () inline
Definition at line 933 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), isLogicRelated(), isTimingEndPoint(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
setControlSetInfo()
void DesignInfo::DesignCell::setControlSetInfo (ControlSetInfo * _controlSetInfo) inline
Set the Control Set Info object of this cell.
A control set is a combination of CLK, CE and SR signal. It could be nullptr (not related to control set)
Parameters
_controlSetInfo
Definition at line 1054 of file DesignInfo.h.
setHasDSPReg()
void DesignInfo::DesignCell::setHasDSPReg (bool _hasDSPReg) inline
Definition at line 1102 of file DesignInfo.h.
setTimingLength()
void DesignInfo::DesignCell::setTimingLength (int _timingLength) inline
Definition at line 1107 of file DesignInfo.h.
setVirtualType()
void DesignInfo::DesignCell::setVirtualType (DesignCellType NewCellType) inline
Set the Virtual Type object which might override the actual type in later processing.
for example, for some LUT1-5, we might set its virtual type to be LUT6 to ensure that it will be paired with other LUTs.
Parameters
NewCellType
Definition at line 1067 of file DesignInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell().
Member Data Documentation
cellType
DesignCellType DesignInfo::DesignCell::cellType private
Definition at line 1127 of file DesignInfo.h.
Referenced by DesignCell(), getCellType(), isBRAM(), isCarry(), isClockBuffer(), isDSP(), isFF(), isIO(), isLUT(), isLUT6(), isLUTRAM(), isMux(), isShift(), isShifter(), and setVirtualType().
clockNetPtrs
std::set<DesignNet *> DesignInfo::DesignCell::clockNetPtrs private
Definition at line 1125 of file DesignInfo.h.
Referenced by addClockNet(), and getClockNets().
controlSetInfo
ControlSetInfo* DesignInfo::DesignCell::controlSetInfo = nullptr private
Definition at line 1131 of file DesignInfo.h.
Referenced by getControlSetInfo(), and setControlSetInfo().
hasDSPReg
bool DesignInfo::DesignCell::hasDSPReg = false private
Definition at line 1130 of file DesignInfo.h.
Referenced by checkHasDSPReg(), and setHasDSPReg().
inputNetPtrs
std::vector<DesignNet *> DesignInfo::DesignCell::inputNetPtrs private
Definition at line 1123 of file DesignInfo.h.
Referenced by DesignCell(), and getInputNets().
inputPinPtrs
std::vector<DesignPin *> DesignInfo::DesignCell::inputPinPtrs private
Definition at line 1119 of file DesignInfo.h.
Referenced by DesignCell(), and getInputPins().
isVirtual
bool DesignInfo::DesignCell::isVirtual = false private
Definition at line 1129 of file DesignInfo.h.
Referenced by DesignCell(), and isVirtualCell().
netNames
std::vector<std::string> DesignInfo::DesignCell::netNames private
Definition at line 1126 of file DesignInfo.h.
Referenced by DesignCell().
netPtrs
std::vector<DesignNet *> DesignInfo::DesignCell::netPtrs private
Definition at line 1122 of file DesignInfo.h.
Referenced by DesignCell().
oriCellType
DesignCellType DesignInfo::DesignCell::oriCellType private
Definition at line 1128 of file DesignInfo.h.
Referenced by DesignCell(), getOriCellType(), and originallyIsLUTRAM().
outputNetPtrs
std::vector<DesignNet *> DesignInfo::DesignCell::outputNetPtrs private
Definition at line 1124 of file DesignInfo.h.
Referenced by DesignCell(), and getOutputNets().
outputPinPtrs
std::vector<DesignPin *> DesignInfo::DesignCell::outputPinPtrs private
Definition at line 1120 of file DesignInfo.h.
Referenced by DesignCell(), and getOutputPins().
pinNames
std::vector<std::string> DesignInfo::DesignCell::pinNames private
Definition at line 1121 of file DesignInfo.h.
Referenced by DesignCell().
pinPtrs
std::vector<DesignPin *> DesignInfo::DesignCell::pinPtrs private
Definition at line 1118 of file DesignInfo.h.
Referenced by DesignCell(), getPins(), and ~DesignCell().
timingLength
int DesignInfo::DesignCell::timingLength = 0 private
Definition at line 1132 of file DesignInfo.h.
Referenced by getTimingLength(), and setTimingLength().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/designInfo/DesignInfo.h
src/lib/HiFPlacer/designInfo/DesignInfo.cc