AMF-Placer: DesignInfo::ControlSetInfo Class Reference
DesignInfo::ControlSetInfo Class Reference
A control set is a combination of CLK, CE and SR signal. It could be nullptr (not related to control set)
#include <DesignInfo.h>
Public Member Functions
ControlSetInfo (DesignInfo::DesignCell *curFF, int id)
Construct a new Control Set Info object with signals of a given FF and a given ID.
~ControlSetInfo ()
bool compatibleWith (DesignInfo::DesignCell *curFF)
check if a FF is compatible with the control set
void setControlSetInfoAs (DesignInfo::DesignCell *curFF)
Set the control set information accoridng to a given FF.
DesignInfo::DesignNet * getCLK () const
DesignInfo::DesignNet * getSR () const
DesignInfo::DesignNet * getCE () const
DesignInfo::DesignCellType getFFType () const
const int getId () const
Get the Id of the control set (each control set will have a unique Id)
void addFF (DesignInfo::DesignCell *curFF)
add a FF into the set of FFs which are compatible to this control set
std::vector< DesignInfo::DesignCell * > & getFFs ()
get the set of FFs which are compatible to this control set
void display ()
Private Attributes
DesignInfo::DesignNet * CLK = nullptr
DesignInfo::DesignNet * SR = nullptr
DesignInfo::DesignNet * CE = nullptr
DesignInfo::DesignCellType FFType
std::vector< DesignInfo::DesignCell * > FFs
int id = -1
Detailed Description
A control set is a combination of CLK, CE and SR signal. It could be nullptr (not related to control set)
Definition at line 1139 of file DesignInfo.h.
Constructor & Destructor Documentation
ControlSetInfo()
DesignInfo::ControlSetInfo::ControlSetInfo (DesignInfo::DesignCell * curFF, int id) inline
Construct a new Control Set Info object with signals of a given FF and a given ID.
Parameters
curFF FF to extract control set signal
id assign an Id for this combination
Definition at line 1148 of file DesignInfo.h.
~ControlSetInfo()
DesignInfo::ControlSetInfo::~ControlSetInfo () inline
Definition at line 1154 of file DesignInfo.h.
Member Function Documentation
addFF()
void DesignInfo::ControlSetInfo::addFF (DesignInfo::DesignCell * curFF) inline
add a FF into the set of FFs which are compatible to this control set
Parameters
curFF
Definition at line 1276 of file DesignInfo.h.
Referenced by DesignInfo::updateFFControlSets().
compatibleWith()
bool DesignInfo::ControlSetInfo::compatibleWith (DesignInfo::DesignCell * curFF) inline
check if a FF is compatible with the control set
check all the control signals of the FF are identical to those of control set respectively. Only those FFs compatible to the same control set can be packed in one Half CLB block in CLB site.
Parameters
curFF a given FF
Returns
true if a FF is compatible with the control set
false if a FF is NOT compatible with the control set
Definition at line 1166 of file DesignInfo.h.
display()
void DesignInfo::ControlSetInfo::display () inline
Definition at line 1291 of file DesignInfo.h.
getCE()
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::getCE () const inline
Definition at line 1252 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackedControlSet::addFF(), and InitialPacker::PackedControlSet::addFF().
getCLK()
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::getCLK () const inline
Definition at line 1244 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackedControlSet::addFF(), InitialPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::addLUTFFPair(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::canDirectConnectInSlot(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::compatibleInOneHalfCLB(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), and ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite().
getFFs()
std::vector<DesignInfo::DesignCell *>& DesignInfo::ControlSetInfo::getFFs () inline
get the set of FFs which are compatible to this control set
Returns
std::vector<DesignInfo::DesignCell *>&
Definition at line 1286 of file DesignInfo.h.
getFFType()
DesignInfo::DesignCellType DesignInfo::ControlSetInfo::getFFType () const inline
Definition at line 1257 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::compatibleInOneHalfCLB().
getId()
const int DesignInfo::ControlSetInfo::getId () const inline
Get the Id of the control set (each control set will have a unique Id)
Returns
const int
Definition at line 1266 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackedControlSet::addFF(), InitialPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addFFGroup(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::addLUTFFPair(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::canDirectConnectInSlot(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), and ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite().
getSR()
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::getSR () const inline
Definition at line 1248 of file DesignInfo.h.
Referenced by ParallelCLBPacker::PackedControlSet::addFF(), InitialPacker::PackedControlSet::addFF(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::addLUTFFPair(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addToFFSet(), ParallelCLBPacker::PackingCLBSite::SiteBELMapping::canDirectConnectInSlot(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::compatibleInOneHalfCLB(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), and ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite().
setControlSetInfoAs()
void DesignInfo::ControlSetInfo::setControlSetInfoAs (DesignInfo::DesignCell * curFF) inline
Set the control set information accoridng to a given FF.
Parameters
curFF target FF to extract control set signal
Definition at line 1210 of file DesignInfo.h.
Member Data Documentation
CE
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::CE = nullptr private
Definition at line 1306 of file DesignInfo.h.
CLK
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::CLK = nullptr private
Definition at line 1304 of file DesignInfo.h.
FFs
std::vector<DesignInfo::DesignCell *> DesignInfo::ControlSetInfo::FFs private
Definition at line 1308 of file DesignInfo.h.
FFType
DesignInfo::DesignCellType DesignInfo::ControlSetInfo::FFType private
Definition at line 1307 of file DesignInfo.h.
id
int DesignInfo::ControlSetInfo::id = -1 private
Definition at line 1309 of file DesignInfo.h.
SR
DesignInfo::DesignNet* DesignInfo::ControlSetInfo::SR = nullptr private
Definition at line 1305 of file DesignInfo.h.
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/designInfo/DesignInfo.h