AMF-Placer: PlacementInfo::PlacementUnit Class Reference
PlacementInfo::PlacementUnit Class Reference
a movement unit in placement with information of location and resource demand
#include <PlacementInfo.h>
Public Member Functions
PlacementUnit (std::string name, int id, PlacementUnitType unitType)
virtual ~PlacementUnit ()
void getAnchorLocation (float &x, float &y)
float X ()
float Y ()
float lastX ()
float lastY ()
void setAnchorLocation (float x, float y)
Set the Anchor Location for the PlacementUnit.
void setSpreadLocation (float x, float y, float forgetRatio)
Set the Spread Location based on forgetting ratio.
void setSpreadLocation_WithLimitDisplacement (float x, float y, float forgetRatio, float limitDisplacement)
Set the Spread Location based on forgetting ratio.
void setAnchorLocationAndForgetTheOriginalOne (float x, float y)
void recordSpreadLocatin ()
void setFixed ()
void setUnfixed ()
void setLocked ()
void setUnlocked ()
bool isLocked ()
void setPlaced ()
bool isFixed ()
bool isPlaced ()
std::string & getName ()
PlacementUnitType getType ()
void setWeight (int numCell)
int getWeight ()
unsigned int getId ()
void renewId (int newId)
void setNetsSetPtr (std::vector< PlacementNet * > *_nets)
Set the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
std::vector< PlacementNet * > * getNetsSetPtr ()
Get the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
int getUnitsBeDrivenByThisPU ()
int getUnitsDriveThisPU ()
void addDSP ()
void addBRAM ()
void addLUTRAM ()
void addLUT ()
void addFF ()
void addCARRY ()
void addMUX ()
bool checkHasDSP ()
bool checkHasBRAM ()
bool checkHasLUTRAM ()
bool checkHasLUT ()
bool checkHasFF ()
bool checkHasCARRY ()
bool checkHasMUX ()
bool hasRegister ()
bool hasLogic ()
bool isMCLB ()
bool isLCLB ()
int getDSPNum ()
int getBRAMNum ()
int getLUTRAMNum ()
int getLUTNum ()
int getCARRYNum ()
int getMUXNum ()
void setPacked ()
void resetPacked ()
bool isPacked ()
std::set< DesignInfo::DesignNet * > & getClockNets ()
Protected Attributes
std::set< DesignInfo::DesignNet * > clockNets
record the clock nets connected to this PlacementUnit
Private Attributes
std::string name
int id
float anchorX = -2000
float anchorY = -2000
float lastAnchorX = -2000
float lastAnchorY = -2000
float lastSpreadX = -2000
float lastSpreadY = -2000
PlacementUnitType unitType
std::vector< PlacementNet * > * nets
record the nets connected to this PlacementUnit
bool fixed = false
fixed simply means the PlacementUnit cannot be moved.
bool placed = false
the PlacementUnit is placed to BEL slot.
bool locked = false
if locked, the attributes of the PlacementUnit cannot be changed (more than fixed.)
int weight = 1
int DSPcnt = 0
int BRAMcnt = 0
int LUTRAMcnt = 0
int LUTcnt = 0
int FFcnt = 0
int CARRYcnt = 0
int MUXcnt = 0
int numUnitsBeDrivenByThisPU = -1
int numUnitsDriveThisPU = -1
bool packed = false
Detailed Description
a movement unit in placement with information of location and resource demand
Definition at line 997 of file PlacementInfo.h.
Constructor & Destructor Documentation
PlacementUnit()
PlacementInfo::PlacementUnit::PlacementUnit (std::string name, int id, PlacementUnitType unitType) inline
Definition at line 1000 of file PlacementInfo.h.
~PlacementUnit()
virtual PlacementInfo::PlacementUnit::~PlacementUnit () inline virtual
Definition at line 1003 of file PlacementInfo.h.
Member Function Documentation
addBRAM()
void PlacementInfo::PlacementUnit::addBRAM () inline
Definition at line 1264 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addCARRY()
void PlacementInfo::PlacementUnit::addCARRY () inline
Definition at line 1280 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addDSP()
void PlacementInfo::PlacementUnit::addDSP () inline
Definition at line 1260 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addFF()
void PlacementInfo::PlacementUnit::addFF () inline
Definition at line 1276 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addLUT()
void PlacementInfo::PlacementUnit::addLUT () inline
Definition at line 1272 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addLUTRAM()
void PlacementInfo::PlacementUnit::addLUTRAM () inline
Definition at line 1268 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), InitialPacker::loadOtherCLBMacros(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
addMUX()
void PlacementInfo::PlacementUnit::addMUX () inline
Definition at line 1284 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
checkHasBRAM()
bool PlacementInfo::PlacementUnit::checkHasBRAM () inline
Definition at line 1292 of file PlacementInfo.h.
Referenced by hasLogic(), and hasRegister().
checkHasCARRY()
bool PlacementInfo::PlacementUnit::checkHasCARRY () inline
Definition at line 1308 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), and hasLogic().
checkHasDSP()
bool PlacementInfo::PlacementUnit::checkHasDSP () inline
Definition at line 1288 of file PlacementInfo.h.
Referenced by hasLogic(), and hasRegister().
checkHasFF()
bool PlacementInfo::PlacementUnit::checkHasFF () inline
Definition at line 1304 of file PlacementInfo.h.
Referenced by hasLogic(), and hasRegister().
checkHasLUT()
bool PlacementInfo::PlacementUnit::checkHasLUT () inline
Definition at line 1300 of file PlacementInfo.h.
Referenced by hasLogic().
checkHasLUTRAM()
bool PlacementInfo::PlacementUnit::checkHasLUTRAM () inline
Definition at line 1296 of file PlacementInfo.h.
Referenced by hasLogic(), and hasRegister().
checkHasMUX()
bool PlacementInfo::PlacementUnit::checkHasMUX () inline
Definition at line 1312 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), and ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite().
getAnchorLocation()
void PlacementInfo::PlacementUnit::getAnchorLocation (float & x, float & y) inline
Definition at line 1006 of file PlacementInfo.h.
getBRAMNum()
int PlacementInfo::PlacementUnit::getBRAMNum () inline
Definition at line 1337 of file PlacementInfo.h.
Referenced by PlacementInfo::ClusterUnit::addPlacementUnit().
getCARRYNum()
int PlacementInfo::PlacementUnit::getCARRYNum () inline
Definition at line 1349 of file PlacementInfo.h.
Referenced by GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate().
getClockNets()
std::set<DesignInfo::DesignNet *>& PlacementInfo::PlacementUnit::getClockNets () inline
Definition at line 1370 of file PlacementInfo.h.
Referenced by PlacementInfo::addPUIntoClockColumn(), PlacementInfo::checkClockColumnLegalization(), PlacementInfo::getClockColumnUtilizationIncrease(), and PlacementInfo::printOutClockColumnLegalization().
getDSPNum()
int PlacementInfo::PlacementUnit::getDSPNum () inline
Definition at line 1333 of file PlacementInfo.h.
Referenced by PlacementInfo::ClusterUnit::addPlacementUnit().
getId()
unsigned int PlacementInfo::PlacementUnit::getId () inline
Definition at line 1194 of file PlacementInfo.h.
Referenced by PlacementInfo::addPseudoNetsInPlacementInfo(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::clusterHash(), CLBLegalizer::getHPWLChange(), MacroLegalizer::getHPWLChange(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), Packing_PUcompare::operator()(), operator<<(), ClusterPlacer::refineClustersWithPredefinedClusters(), and ParallelCLBPacker::timingDrivenDetailedPlacement_swap().
getLUTNum()
int PlacementInfo::PlacementUnit::getLUTNum () inline
Definition at line 1345 of file PlacementInfo.h.
getLUTRAMNum()
int PlacementInfo::PlacementUnit::getLUTRAMNum () inline
Definition at line 1341 of file PlacementInfo.h.
getMUXNum()
int PlacementInfo::PlacementUnit::getMUXNum () inline
Definition at line 1353 of file PlacementInfo.h.
getName()
std::string& PlacementInfo::PlacementUnit::getName () inline
Definition at line 1174 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU(), ParallelCLBPacker::dumpFinalPacking(), MacroLegalizer::dumpMatching(), and operator<<().
getNetsSetPtr()
std::vector<PlacementNet *>* PlacementInfo::PlacementUnit::getNetsSetPtr () inline
Get the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
Returns
std::vector<PlacementNet *>*
Definition at line 1219 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::exceptionPULegalize(), ParallelCLBPacker::PackingCLBSite::getHPWLChangeForPU(), and PlacementInfo::updateLongPaths().
getType()
PlacementUnitType PlacementInfo::PlacementUnit::getType () inline
Definition at line 1179 of file PlacementInfo.h.
Referenced by PlacementInfo::enforceLegalizeXYInArea(), PlacementInfo::isLegalLocation(), PlacementInfo::legalizeXYInArea(), and PlacementInfo::PlacementNet::PlacementNet().
getUnitsBeDrivenByThisPU()
int PlacementInfo::PlacementUnit::getUnitsBeDrivenByThisPU () inline
Definition at line 1224 of file PlacementInfo.h.
getUnitsDriveThisPU()
int PlacementInfo::PlacementUnit::getUnitsDriveThisPU () inline
Definition at line 1242 of file PlacementInfo.h.
getWeight()
int PlacementInfo::PlacementUnit::getWeight () inline
Definition at line 1189 of file PlacementInfo.h.
Referenced by PlacementInfo::ClusterUnit::addPlacementUnit(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), and ParallelCLBPacker::updatePackedMacro().
hasLogic()
bool PlacementInfo::PlacementUnit::hasLogic () inline
Definition at line 1320 of file PlacementInfo.h.
Referenced by PlacementInfo::updateLongPaths().
hasRegister()
bool PlacementInfo::PlacementUnit::hasRegister () inline
Definition at line 1316 of file PlacementInfo.h.
Referenced by PlacementInfo::updateLongPaths().
isFixed()
bool PlacementInfo::PlacementUnit::isFixed () inline
Definition at line 1165 of file PlacementInfo.h.
Referenced by PlacementInfo::addPseudoNetsInPlacementInfo(), PlacementInfo::loadPlacementUnitInformation(), and operator<<().
isLCLB()
bool PlacementInfo::PlacementUnit::isLCLB () inline
Definition at line 1329 of file PlacementInfo.h.
isLocked()
bool PlacementInfo::PlacementUnit::isLocked () inline
Definition at line 1154 of file PlacementInfo.h.
Referenced by operator<<().
isMCLB()
bool PlacementInfo::PlacementUnit::isMCLB () inline
Definition at line 1325 of file PlacementInfo.h.
isPacked()
bool PlacementInfo::PlacementUnit::isPacked () inline
Definition at line 1365 of file PlacementInfo.h.
isPlaced()
bool PlacementInfo::PlacementUnit::isPlaced () inline
Definition at line 1169 of file PlacementInfo.h.
Referenced by operator<<().
lastX()
float PlacementInfo::PlacementUnit::lastX () inline
Definition at line 1022 of file PlacementInfo.h.
lastY()
float PlacementInfo::PlacementUnit::lastY () inline
Definition at line 1027 of file PlacementInfo.h.
recordSpreadLocatin()
void PlacementInfo::PlacementUnit::recordSpreadLocatin () inline
Definition at line 1126 of file PlacementInfo.h.
renewId()
void PlacementInfo::PlacementUnit::renewId (int newId) inline
Definition at line 1199 of file PlacementInfo.h.
resetPacked()
void PlacementInfo::PlacementUnit::resetPacked () inline
Definition at line 1361 of file PlacementInfo.h.
setAnchorLocation()
void PlacementInfo::PlacementUnit::setAnchorLocation (float x, float y) inline
Set the Anchor Location for the PlacementUnit.
meanwhile, if it is not the first iteration in placement, record last anchor location
Parameters
x
y
Definition at line 1040 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementUnpackedCell::setLockedAt().
setAnchorLocationAndForgetTheOriginalOne()
void PlacementInfo::PlacementUnit::setAnchorLocationAndForgetTheOriginalOne (float x, float y) inline
Definition at line 1116 of file PlacementInfo.h.
Referenced by PlacementInfo::enforceLegalizeXYInArea(), IncrementalBELPacker::FFPairing(), PlacementInfo::loadPlacementUnitInformation(), IncrementalBELPacker::LUTFFPairing(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), and ParallelCLBPacker::updatePackedMacro().
setFixed()
void PlacementInfo::PlacementUnit::setFixed () inline
Definition at line 1132 of file PlacementInfo.h.
Referenced by PlacementInfo::loadPlacementUnitInformation(), PlacementInfo::PlacementUnpackedCell::setLockedAt(), and ParallelCLBPacker::updatePackedMacro().
setLocked()
void PlacementInfo::PlacementUnit::setLocked () inline
Definition at line 1144 of file PlacementInfo.h.
Referenced by PlacementInfo::loadPlacementUnitInformation(), and PlacementInfo::PlacementUnpackedCell::setLockedAt().
setNetsSetPtr()
void PlacementInfo::PlacementUnit::setNetsSetPtr (std::vector< PlacementNet * > * _nets) inline
Set the Nets Set Ptr object which records the nets connecting to the PlacementUnit.
Parameters
_nets
Definition at line 1209 of file PlacementInfo.h.
setPacked()
void PlacementInfo::PlacementUnit::setPacked () inline
Definition at line 1357 of file PlacementInfo.h.
Referenced by IncrementalBELPacker::LUTFFPairing(), and ParallelCLBPacker::updatePackedMacro().
setPlaced()
void PlacementInfo::PlacementUnit::setPlaced () inline
Definition at line 1159 of file PlacementInfo.h.
Referenced by PlacementInfo::loadPlacementUnitInformation(), and PlacementInfo::PlacementUnpackedCell::setLockedAt().
setSpreadLocation()
void PlacementInfo::PlacementUnit::setSpreadLocation (float x, float y, float forgetRatio) inline
Set the Spread Location based on forgetting ratio.
Parameters
x
y
forgetRatio how much should the PlacementUnit forget the original location from later iteration
Definition at line 1064 of file PlacementInfo.h.
setSpreadLocation_WithLimitDisplacement()
void PlacementInfo::PlacementUnit::setSpreadLocation_WithLimitDisplacement (float x, float y, float forgetRatio, float limitDisplacement) inline
Set the Spread Location based on forgetting ratio.
Parameters
x
y
forgetRatio how much should the PlacementUnit forget the original location from later iteration
limitDisplacement limit the displacement
Definition at line 1090 of file PlacementInfo.h.
setUnfixed()
void PlacementInfo::PlacementUnit::setUnfixed () inline
Definition at line 1138 of file PlacementInfo.h.
setUnlocked()
void PlacementInfo::PlacementUnit::setUnlocked () inline
Definition at line 1149 of file PlacementInfo.h.
setWeight()
void PlacementInfo::PlacementUnit::setWeight (int numCell) inline
Definition at line 1184 of file PlacementInfo.h.
Referenced by IncrementalBELPacker::FFPairing(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findLUTRAMMacros(), InitialPacker::findMuxMacros(), InitialPacker::findUnpackedUnits(), InitialPacker::loadOtherCLBMacros(), PlacementInfo::loadPlacementUnitInformation(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::LUTFFPairing(), and ParallelCLBPacker::updatePackedMacro().
X()
float PlacementInfo::PlacementUnit::X () inline
Definition at line 1012 of file PlacementInfo.h.
Referenced by PlacementInfo::enforceLegalizeXYInArea(), ParallelCLBPacker::exceptionPULegalize(), IncrementalBELPacker::FFLocation::FFLocation(), CLBLegalizer::getDisplacement(), MacroLegalizer::getDisplacement(), MacroLegalizer::getHPWLChange(), ParallelCLBPacker::PackingCLBSite::getHPWLChangeForPU(), operator<<(), ParallelCLBPacker::PULocation::PULocation(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and WirelengthOptimizer::updatePseudoNetForUserDefinedClusters().
Y()
float PlacementInfo::PlacementUnit::Y () inline
Definition at line 1017 of file PlacementInfo.h.
Referenced by PlacementInfo::enforceLegalizeXYInArea(), ParallelCLBPacker::exceptionPULegalize(), IncrementalBELPacker::FFLocation::FFLocation(), CLBLegalizer::getDisplacement(), MacroLegalizer::getDisplacement(), MacroLegalizer::getHPWLChange(), ParallelCLBPacker::PackingCLBSite::getHPWLChangeForPU(), operator<<(), and ParallelCLBPacker::PULocation::PULocation().
Member Data Documentation
anchorX
float PlacementInfo::PlacementUnit::anchorX = -2000 private
Definition at line 1385 of file PlacementInfo.h.
Referenced by getAnchorLocation(), recordSpreadLocatin(), setAnchorLocation(), setAnchorLocationAndForgetTheOriginalOne(), setSpreadLocation(), setSpreadLocation_WithLimitDisplacement(), and X().
anchorY
float PlacementInfo::PlacementUnit::anchorY = -2000 private
Definition at line 1385 of file PlacementInfo.h.
Referenced by getAnchorLocation(), recordSpreadLocatin(), setAnchorLocation(), setAnchorLocationAndForgetTheOriginalOne(), setSpreadLocation(), setSpreadLocation_WithLimitDisplacement(), and Y().
BRAMcnt
int PlacementInfo::PlacementUnit::BRAMcnt = 0 private
Definition at line 1418 of file PlacementInfo.h.
Referenced by addBRAM(), checkHasBRAM(), and getBRAMNum().
CARRYcnt
int PlacementInfo::PlacementUnit::CARRYcnt = 0 private
Definition at line 1422 of file PlacementInfo.h.
Referenced by addCARRY(), checkHasCARRY(), getCARRYNum(), and isLCLB().
clockNets
std::set<DesignInfo::DesignNet *> PlacementInfo::PlacementUnit::clockNets protected
record the clock nets connected to this PlacementUnit
Definition at line 1380 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addCell(), PlacementInfo::PlacementMacro::addVirtualCell(), getClockNets(), and PlacementInfo::PlacementUnpackedCell::PlacementUnpackedCell().
DSPcnt
int PlacementInfo::PlacementUnit::DSPcnt = 0 private
Definition at line 1417 of file PlacementInfo.h.
Referenced by addDSP(), checkHasDSP(), and getDSPNum().
FFcnt
int PlacementInfo::PlacementUnit::FFcnt = 0 private
Definition at line 1421 of file PlacementInfo.h.
Referenced by addFF(), and checkHasFF().
fixed
bool PlacementInfo::PlacementUnit::fixed = false private
fixed simply means the PlacementUnit cannot be moved.
Definition at line 1400 of file PlacementInfo.h.
Referenced by isFixed(), setFixed(), and setUnfixed().
id
int PlacementInfo::PlacementUnit::id private
Definition at line 1384 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::getCell(), and getId().
lastAnchorX
float PlacementInfo::PlacementUnit::lastAnchorX = -2000 private
Definition at line 1386 of file PlacementInfo.h.
Referenced by lastX(), setAnchorLocation(), setAnchorLocationAndForgetTheOriginalOne(), setSpreadLocation(), and setSpreadLocation_WithLimitDisplacement().
lastAnchorY
float PlacementInfo::PlacementUnit::lastAnchorY = -2000 private
Definition at line 1386 of file PlacementInfo.h.
Referenced by lastY(), setAnchorLocation(), setAnchorLocationAndForgetTheOriginalOne(), setSpreadLocation(), and setSpreadLocation_WithLimitDisplacement().
lastSpreadX
float PlacementInfo::PlacementUnit::lastSpreadX = -2000 private
Definition at line 1387 of file PlacementInfo.h.
Referenced by recordSpreadLocatin(), setSpreadLocation(), and setSpreadLocation_WithLimitDisplacement().
lastSpreadY
float PlacementInfo::PlacementUnit::lastSpreadY = -2000 private
Definition at line 1387 of file PlacementInfo.h.
Referenced by recordSpreadLocatin(), setSpreadLocation(), and setSpreadLocation_WithLimitDisplacement().
locked
bool PlacementInfo::PlacementUnit::locked = false private
if locked, the attributes of the PlacementUnit cannot be changed (more than fixed.)
Definition at line 1414 of file PlacementInfo.h.
Referenced by isLocked(), setAnchorLocation(), setAnchorLocationAndForgetTheOriginalOne(), setFixed(), setLocked(), setPlaced(), setSpreadLocation(), setSpreadLocation_WithLimitDisplacement(), setUnfixed(), and setUnlocked().
LUTcnt
int PlacementInfo::PlacementUnit::LUTcnt = 0 private
Definition at line 1420 of file PlacementInfo.h.
Referenced by addLUT(), checkHasLUT(), getLUTNum(), and isLCLB().
LUTRAMcnt
int PlacementInfo::PlacementUnit::LUTRAMcnt = 0 private
Definition at line 1419 of file PlacementInfo.h.
Referenced by addLUTRAM(), checkHasLUTRAM(), getLUTRAMNum(), and isMCLB().
MUXcnt
int PlacementInfo::PlacementUnit::MUXcnt = 0 private
Definition at line 1423 of file PlacementInfo.h.
Referenced by addMUX(), checkHasMUX(), and getMUXNum().
name
std::string PlacementInfo::PlacementUnit::name private
Definition at line 1383 of file PlacementInfo.h.
Referenced by getName().
nets
std::vector<PlacementNet *>* PlacementInfo::PlacementUnit::nets private
record the nets connected to this PlacementUnit
Definition at line 1394 of file PlacementInfo.h.
Referenced by getNetsSetPtr(), getUnitsBeDrivenByThisPU(), getUnitsDriveThisPU(), and setNetsSetPtr().
numUnitsBeDrivenByThisPU
int PlacementInfo::PlacementUnit::numUnitsBeDrivenByThisPU = -1 private
Definition at line 1424 of file PlacementInfo.h.
Referenced by getUnitsBeDrivenByThisPU().
numUnitsDriveThisPU
int PlacementInfo::PlacementUnit::numUnitsDriveThisPU = -1 private
Definition at line 1425 of file PlacementInfo.h.
Referenced by getUnitsDriveThisPU().
packed
bool PlacementInfo::PlacementUnit::packed = false private
Definition at line 1427 of file PlacementInfo.h.
Referenced by isPacked(), resetPacked(), and setPacked().
placed
bool PlacementInfo::PlacementUnit::placed = false private
the PlacementUnit is placed to BEL slot.
Currently, this attribute is not used.
Definition at line 1408 of file PlacementInfo.h.
Referenced by isPlaced(), and setPlaced().
unitType
PlacementUnitType PlacementInfo::PlacementUnit::unitType private
Definition at line 1388 of file PlacementInfo.h.
Referenced by getType().
weight
int PlacementInfo::PlacementUnit::weight = 1 private
Definition at line 1415 of file PlacementInfo.h.
Referenced by getWeight(), and setWeight().
The documentation for this class was generated from the following file:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h