AMF-Placer: PlacementInfo Class Reference
PlacementInfo Class Reference
Information related to FPGA placement (wirelength optimization, cell spreading, legalization, packing)
#include <PlacementInfo.h>
Classes
struct _ClockNetCoverage
the retangular clock region coverage of a clock net
struct CellBinInfo
record the bin information for a cell (BELtype, column/row, resource demand)
class ClusterNet
The net between the objects of ClusterUnit class.
class ClusterUnit
a group of PlacementUnits
class CompatiblePlacementTable
describes the type mapping from design to device, where a cell can be placed (which BEL in which site)
struct Location
class PlacementBinInfo
BEL bin for global placement for a specific shared BEL type.
class PlacementHybridBinInfo
BEL bin for global placement for multiple specific shared BEL types.
class PlacementMacro
a fixed group of multiple standard cells with constraints of their relative locations
class PlacementNet
Placement net, compared to design net, includes information related to placement.
class PlacementSiteBinInfo
Site bin for global placement for some specific Site types.
class PlacementSiteTypeInfo
information for a site, e.g. what BEL in site and where are these kind of sites
class PlacementUnit
a movement unit in placement with information of location and resource demand
class PlacementUnpackedCell
the smallest, indivisible, representable component. It will include only one standard cell
Public Types
enum PlacementUnitType { PlacementUnitType_UnpackedCell = 0, PlacementUnitType_Macro }
Placement Instance Types.
typedef struct PlacementInfo::Location Location
typedef struct PlacementInfo::CellBinInfo CellBinInfo
record the bin information for a cell (BELtype, column/row, resource demand)
Public Member Functions
PlacementInfo (DesignInfo *designInfo, DeviceInfo *deviceInfo, std::map< std::string, std::string > &JSONCfg)
Construct a new Placement Info object based on the information of design and device.
~PlacementInfo ()
void printStat (bool verbose=false)
CompatiblePlacementTable * loadCompatiblePlacementTable (std::string cellType2fixedAmoFileName, std::string cellType2sharedCellTypeFileName, std::string sharedCellType2BELtypeFileName)
describes the type mapping from design to device, where a cell can be placed (which BEL in which site)
CompatiblePlacementTable * getCompatiblePlacementTable ()
void setBELTypeForCells (DesignInfo *designInfo)
float getMinXFromSites (std::vector< DeviceInfo::DeviceSite * > &sites)
Get the Min X of sites to identify the boundary of the device.
float getMinYFromSites (std::vector< DeviceInfo::DeviceSite * > &sites)
Get the Min Y of sites to identify the boundary of the device.
float getMaxXFromSites (std::vector< DeviceInfo::DeviceSite * > &sites)
Get the Max X of sites to identify the boundary of the device.
float getMaxYFromSites (std::vector< DeviceInfo::DeviceSite * > &sites)
Get the Max Y of sites to identify the boundary of the device.
void createGridBins (float binWidth, float binHeight)
Create a grid of bins on the device.
void createSiteBinGrid ()
void reloadNets ()
update PlacementNet objects when there are some updates of PlacementUnit objects (e.g., some cells are packed)
void updateLongPaths ()
update the long path in the design and enhance their net weights
void verifyDeviceForDesign ()
verify that each cells in the design can be mapped on the resource elements on the device.
std::vector< PlacementUnit * > & getPlacementUnits ()
std::vector< PlacementMacro * > & getPlacementMacros ()
std::vector< PlacementUnit * > & getFixedPlacementUnits ()
std::vector< PlacementNet * > & getPlacementNets ()
std::set< DesignInfo::DesignCell * > & getCellInMacros ()
std::map< int, PlacementUnit * > & getCellId2PlacementUnit ()
std::vector< PlacementUnit * > & getCellId2PlacementUnitVec ()
std::vector< PlacementUnpackedCell * > & getPlacementUnpackedCells ()
int getNumCells ()
float getGlobalMaxX ()
Get the Global Max X (right boundary of the device)
float getGlobalMaxY ()
Get the Global Max Y (top boundary of the device)
float getGlobalMinX ()
Get the Global Min X (left boundary of the device)
float getGlobalMinY ()
Get the Global Min Y (bottom boundary of the device)
float getGlobalBinMaxLocX ()
get right boundary of the bin grid
float getGlobalBinMaxLocY ()
get top boundary of the bin grid
float getGlobalBinMinLocX ()
get left boundary of the bin grid
float getGlobalBinMinLocY ()
get bottom boundary of the bin grid
float getDeviceMaxEdgeLength ()
std::vector< int > & getPotentialBELTypeIDs (DesignInfo::DesignCell *cell)
std::vector< int > & getPotentialBELTypeIDs (DesignInfo::DesignCellType cellType)
int getSharedBELTypeId (std::string tmpStr)
float getActualOccupation (DesignInfo::DesignCell *cell)
Get the actual occupation of a specific cell.
float getInflateRatio (DesignInfo::DesignCell *cell)
Get the inflate ratio of a cell.
std::vector< float > & getcellId2Occupation ()
float getOccupation (DesignInfo::DesignCellType cellType)
Get the theoratical occupation of a specific cell type.
float getActualOccupationByCellId (int id)
Get the Actual Occupation By Cell Id.
std::vector< DesignInfo::DesignCell * > * findNeiborLUTFFsFromBinGrid (DesignInfo::DesignCell *curCell, float displacementUpperbound, int minNumNeighbor=10)
find neibor LUTs/FFs from bin grid
std::vector< std::vector< PlacementBinInfo * > > & getBinGrid (unsigned int BELTypeId)
Get the Bin Grid object.
std::vector< std::vector< std::vector< PlacementBinInfo * > > > & getBinGrid ()
Get the Bin Grid object for all types of BEL.
std::vector< std::vector< PlacementSiteBinInfo * > > & getSiteBinGrid ()
PlacementUnit * getPlacementUnitByCell (DesignInfo::DesignCell *curCell)
PlacementUnit * getPlacementUnitByCellId (int cellId)
PlacementNet * getPlacementNetByDesignNetId (int netId)
void addB2BNetInPlacementInfo (std::vector< Eigen::Triplet< float >> &objectiveMatrixTripletList, std::vector< float > &objectiveMatrixDiag, Eigen::VectorXd &objectiveVector, int puId0, int puId1, float pos0, float pos1, float pinOffset0, float pinOffset1, bool movable0, bool movable1, float w)
directly set weight in the quadratic Matrix and vector according to given request.
void addPseudoNetsInPlacementInfo (std::vector< Eigen::Triplet< float >> &objectiveMatrixTripletList, std::vector< float > &objectiveMatrixDiag, Eigen::VectorXd &objectiveVector, PlacementUnit *tmpPU, float targetLoc, float pseudoWeight, float y2xRatio, bool updateX, bool updateY)
directly set weight in the quadratic Matrix and vector according to given request.
void updateCells2PlacementUnits ()
update the mapping from Cells to PlacementUnits, since sometime, PlacementUnits might change
void updateElementBinGrid ()
map design cells to the bins in the bin grid.
void adjustLUTFFUtilization_Routability (bool enfore)
adjust the resource demand of LUTs/FFs according to routing congestion refer to RippleFPGA's implementation
void adjustLUTFFUtilization_Routability_Reset ()
reset the inflate ratio of all the cells to be 1, for re-evaluation
void adjustLUTFFUtilization_Packablity (float neighborDisplacementUpperbound, bool enfore)
adjust the resource demand of LUTs/FFs according to packing feasibility
void adjustLUTFFUtilization (float neighborDisplacementUpperbound, bool enfore=false)
adjust the resource demand of LUTs/FFs according to packing feasibility and routing congestion
void adjustLUTFFUtilization_Clocking ()
adjust the utlization of clock-related elements to mitigate the overflow of clock utilization
void resetElementBinGrid ()
clean the information in bin grid
void updateSiteBinGrid ()
void resetSiteBinGrid ()
DesignInfo * getDesignInfo ()
DeviceInfo * getDeviceInfo ()
PlacementTimingInfo * getTimingInfo ()
std::string getBELType2FalseBELType (std::string curBELType)
get the remapped BEL type of a specific BEL type since some cell can be placed in sites of different sites. For cell spreading, we need to remap some BEL types to a unified BEL types. Belows are some examples:
void getGridXY (float cellX, float cellY, int &binIdX, int &binIdY)
Get the Grid row/column based on given location X,Y.
void legalizeXYInArea (PlacementUnit *curPU, float &fX, float &fY)
move the PlacementUnit to ensure the cells in it are within the device area.
void enforceLegalizeXYInArea (PlacementUnit *curPU)
move the PlacementUnit to ensure the cells in it are within the device area.
bool isLegalLocation (DesignInfo::DesignCell *curCell, float targetX, float targetY)
check whether the PlacementUnit is legalized in the device area when a cell in it is placed at target location
bool isLegalLocation (PlacementUnit *curPU, float targetX, float targetY)
check whether the PlacementUnit is legalized in the device area when it is placed at target location
void getPULocationByCellLocation (DesignInfo::DesignCell *curCell, float targetX, float targetY, float &PUX, float &PUY)
std::vector< Location > & getCellId2location ()
std::vector< Location > & getPinId2location ()
float getBinGridW ()
Get the width of a bin in grid.
float getBinGridH ()
Get the height of a bin in grid.
void setPULegalXY (std::map< PlacementInfo::PlacementUnit *, float > &PU2X, std::map< PlacementInfo::PlacementUnit *, float > &PU2Y)
set the legalization of some PlacementUnit objects
void setPULegalSite (std::map< PlacementInfo::PlacementUnit *, std::vector< DeviceInfo::DeviceSite * >> &PU2Sites)
set the sites occupied by the PlacementUnit objects
std::map< PlacementInfo::PlacementUnit *, std::vector< DeviceInfo::DeviceSite * > > & getPULegalSite ()
get the sites occupied by the legalized PlacementUnit objects
std::pair< std::map< PlacementInfo::PlacementUnit *, float >, std::map< PlacementInfo::PlacementUnit *, float > > & getPULegalXY ()
get the locations (pair of X,Y) of the legalized PlacementUnit objects
void resetPULegalInformation ()
forget all the legalization information
void deleteLegalizationInfoFor (PlacementInfo::PlacementUnit *curPU)
remove the legalization information of a PlacementUnit object
void setCellBinInfo (int cellId, int sharedTypeId, int X, int Y, float occupation)
Set the cell bin Information of a design cell.
void transferCellBinInfo (int cellId, float fX, int fY)
update the bin information of a design cell when it is moved to a new location
float getDisplacement (float fX, float fY, DeviceInfo::DeviceSite *curSite)
Get the Displacement from a given location to a device site (y2xRatio is considered.)
std::vector< DeviceInfo::DeviceSite * > * findNeiborSiteFromBinGrid (DesignInfo::DesignCell *curCell, float targetX, float targetY, float displacementThreshold, int siteNumThreshold, bool checkClockRegion=false)
find neibor device sites of a given cell from bin grid
std::vector< CellBinInfo > & getCellId2CellBinInfo ()
std::vector< DesignInfo::DesignCell * > & getCells ()
std::vector< std::vector< PlacementNet * > > & getPlacementUnitId2Nets ()
double updateB2BAndGetTotalHPWL ()
update the B2B net model for the placement and get the total HPWL of all the nets in the design
double getTotalHPWL ()
get the total HPWL of all the nets in the design without updating the B2B net model for the placement
void setProgress (float p)
Set the progress ratio, indicating the progress of the placement convergence,.
float getProgress ()
Get the Progress ratio of the placement.
void dumpCongestion (std::string dumpFileName)
dump the congestion mesh grid for evaluation
void dumpVivadoPlacementTclWithPULegalizationInfo (std::string dumpFile)
dump the placement commands to place cells in Vivado (do not use this temporarily)
void dumpPlacementUnitInformation (std::string dumpFile)
dump the PlacementUnit objects and some placement parameters as a checkpoint
void loadPlacementUnitInformation (std::string locationFile)
load the data of the PlacementUnit objects and some placement parameters from a checkpoint file
void setPseudoNetWeight (float weight)
Set the Pseudo Net Weight according to a given value.
float getPseudoNetWeight ()
Get the Pseudo Net Weight object.
int getMacroPseudoNetEnhanceCnt ()
Get the Macro Pseudo Net Enhance Counter.
float getMacroLegalizationWeight ()
Get the Macro Legalization Weight.
void setMacroLegalizationParameters (int cnt, float _macroLegalizationWeight)
Set the Macro Legalization Parameters.
void resetLUTFFDeterminedOccupation ()
reset the LUTFFDeterminedOccupation object
int getDeterminedOccupation (int cellId)
void setDeterminedOccupation (int cellId, int occupation)
Set the Determined Occupation of a specific cell.
unsigned int getPairPinNum (DesignInfo::DesignCell *LUTA, DesignInfo::DesignCell *LUTB)
Get the Pair Pin Num of two LUTs.
void calculateNetNumDistributionOfPUs ()
calculate the proportion of the PlacementUnit objects with high interconnection density
float getPUWithManyNetsRatio ()
get the proportion of the PlacementUnit objects with high interconnection density
void setMinHPWL (float val)
record the minimum HPWL during placement procedure
float getMinHPWL ()
bool checkClockUtilization (bool dump)
check the utlization of the clock regions on the device
void enhanceRiskyClockNet ()
void enhanceDDRNet ()
void enhanceHighFanoutNet ()
void dumpOverflowClockUtilization ()
bool checkClockColumnLegalization (PlacementInfo::PlacementUnit *curPU, DeviceInfo::DeviceSite *curSite)
check whether the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
int getClockColumnUtilizationIncrease (PlacementInfo::PlacementUnit *curPU, DeviceInfo::DeviceSite *curSite)
check the clock resource increase extent if the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
void printOutClockColumnLegalization (PlacementInfo::PlacementUnit *curPU, DeviceInfo::DeviceSite *curSite)
void addPUIntoClockColumn (PlacementInfo::PlacementUnit *curPU, DeviceInfo::DeviceSite *curSite)
map the given PlacementUnit to the site for later checking of the half-column clock legalization rules
std::vector< std::vector< PlacementUnit * > > & getLongPaths ()
Get the Long Paths in the net list for later optimization.
void optimizeLongPaths ()
make the PlacementUnits in the long path closer to each other
void buildSimpleTimingGraph ()
call timing info to build simple timing graph
std::map< PlacementUnit *, std::pair< float, float > > & getPU2ClockRegionCenters ()
get the PlacementUnit Mapping to clock region centers for timing optimzation
std::map< PlacementUnit *, int > & getPU2ClockRegionColumn ()
get the PlacementUnit Mapping to clock region column for timing optimzation
int getLongPathThresholdLevel ()
int getMediumPathThresholdLevel ()
std::map< DeviceInfo::ClockColumn *, std::set< DesignInfo::DesignNet * > > & getClockCol2ClockNets ()
std::vector< std::vector< PlacementBinInfo * > > & getGlobalBinGrid ()
void setClusterNum (int _clusterNum)
int getClusterNum ()
bool isDensePlacement ()
bool isClockLegalizationRisky ()
int getHighFanOutThr ()
int getNetDistributionByDensity (int density)
float getMacroRatio ()
void setPaintDataBase (PaintDataBase *_paintData)
Private Types
typedef struct PlacementInfo::_ClockNetCoverage ClockNetCoverage
the retangular clock region coverage of a clock net
Private Attributes
CompatiblePlacementTable * compatiblePlacementTable = nullptr
std::vector< PlacementUnit * > placementUnits
std::vector< PlacementUnpackedCell * > placementUnpackedCells
std::vector< PlacementMacro * > placementMacros
std::vector< PlacementUnit * > fixedPlacementUnits
std::set< DesignInfo::DesignCell * > cellInMacros
std::map< int, PlacementUnit * > cellId2PlacementUnit
std::vector< PlacementUnit * > cellId2PlacementUnitVec
std::vector< CellBinInfo > cellId2CellBinInfo
std::vector< Location > cellId2location
std::vector< Location > pinId2location
DesignInfo * designInfo
DeviceInfo * deviceInfo
PlacementTimingInfo * simplePlacementTimingInfo = nullptr
std::pair< std::map< PlacementInfo::PlacementUnit *, float >, std::map< PlacementInfo::PlacementUnit *, float > > PULegalXY
a mapping from PlaceuementUnit objects to legalized locations
std::map< PlacementInfo::PlacementUnit *, std::vector< DeviceInfo::DeviceSite * > > PU2LegalSites
a mapping from PlaceuementUnit objects to device sites
float globalMinX
left boundary of the device
float globalMinY
bottom boundary of the device
float globalMaxX
right boundary of the device
float globalMaxY
top boundary of the device
float startX
left boundary of the bin grid
float startY
bottom boundary of the bin grid
float endX
right boundary of the bin grid
float endY
bottom boundary of the bin grid
float eps = 1e-5
std::vector< std::vector< std::vector< PlacementBinInfo * > > > SharedBELTypeBinGrid
std::vector< std::vector< PlacementBinInfo * > > LUTFFBinGrid
Bin Grid for LUTs and FFs, mainly for searching neighbor elements during packing.
std::vector< std::vector< PlacementBinInfo * > > globalBinGrid
Bin Grid includes all types of sites, mainly for congestion evalution.
std::vector< std::vector< PlacementSiteBinInfo * > > siteGridForMacros
float binWidth
float binHeight
std::vector< PlacementNet * > placementNets
std::vector< std::vector< PlacementNet * > > placementUnitId2Nets
std::vector< PlacementNet * > designNetId2PlacementNet
std::vector< PlacementNet * > clockNets
std::vector< std::vector< int > > clockRegionUtilization
std::set< PlacementUnit * > PUSetContainingFF
std::vector< PlacementUnit * > PUsContainingFF
std::vector< std::vector< PlacementUnit * > > longPaths
std::map< PlacementUnit *, std::pair< float, float > > PU2ClockRegionCenters
std::map< PlacementUnit *, int > PU2ClockRegionColumn
std::map< DeviceInfo::ClockColumn *, std::set< DesignInfo::DesignNet * > > clockCol2ClockNets
PaintDataBase * paintData = nullptr
std::vector< float > PaintXs
std::vector< float > PaintYs
std::vector< int > PaintTypes
std::vector< ClockNetCoverage > clockNetCoverages
float placementProressRatio = 0.01
the progress ratio, indicating the progress of the placement convergence.
std::map< std::string, std::string > & JSONCfg
std::string cellType2fixedAmoFileName
std::string cellType2sharedCellTypeFileName
std::string sharedCellType2BELtypeFileName
int netPinNumDistribution [8] = {8, 16, 24, 32, 64, 256, 512, 1000000}
int netDistribution [8] = {0, 0, 0, 0, 0, 0, 0, 0}
float y2xRatio = 1.0
a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
int longPathThresholdLevel = 10
the long path threshold for timing optimization
int mediumPathThresholdLevel = 5
the medium path threshold for timing optimization
int dumpPlacementUnitLocationCnt = 0
int clusterNum = 1
bool clockLegalizationRisky = false
float oriPseudoNetWeight = -1
int macroPseudoNetEnhanceCnt = -1
float macroLegalizationWeight = -1
float lastProgressWhenLUTFFUtilAdjust = -1.0
float PUWithManyNetsRatio = -1
float minHPWL = 1e8
bool LUTFFUtilizationAdjusted = false
int highFanOutThr = 10000000
float macroRatio = 0.0
Detailed Description
Information related to FPGA placement (wirelength optimization, cell spreading, legalization, packing)
includes design information, device information includes numerical information for: wirelength optimization: Bound2Bound model, HPWL for nets, macros cell spreading: bin grid, instance density, routing congestion, packability legalization: mapping design instance to device site at coarse-grained level packing: mapping fine-grained instances to sites (e.g., CLB site)
Definition at line 47 of file PlacementInfo.h.
Member Typedef Documentation
CellBinInfo
typedef struct PlacementInfo::CellBinInfo PlacementInfo::CellBinInfo
record the bin information for a cell (BELtype, column/row, resource demand)
ClockNetCoverage
typedef struct PlacementInfo::_ClockNetCoverage PlacementInfo::ClockNetCoverage private
the retangular clock region coverage of a clock net
Location
typedef struct PlacementInfo::Location PlacementInfo::Location
Member Enumeration Documentation
PlacementUnitType
enum PlacementInfo::PlacementUnitType
Placement Instance Types.
UnpackedCell: the smallest, indivisible, representable component Macro: a fixed group of multiple standard cells with constraints of their relative locations
Enumerator
PlacementUnitType_UnpackedCell
PlacementUnitType_Macro
Definition at line 56 of file PlacementInfo.h.
Constructor & Destructor Documentation
PlacementInfo()
PlacementInfo::PlacementInfo (DesignInfo * designInfo, DeviceInfo * deviceInfo, std::map< std::string, std::string > & JSONCfg)
Construct a new Placement Info object based on the information of design and device.
Parameters
designInfo
deviceInfo
JSONCfg user-defined placement configuration
Definition at line 23 of file PlacementInfo.cc.
~PlacementInfo()
PlacementInfo::~PlacementInfo () inline
Definition at line 2686 of file PlacementInfo.h.
Member Function Documentation
addB2BNetInPlacementInfo()
void PlacementInfo::addB2BNetInPlacementInfo (std::vector< Eigen::Triplet< float >> & objectiveMatrixTripletList, std::vector< float > & objectiveMatrixDiag, Eigen::VectorXd & objectiveVector, int puId0, int puId1, float pos0, float pos1, float pinOffset0, float pinOffset1, bool movable0, bool movable1, float w) inline
directly set weight in the quadratic Matrix and vector according to given request.
Usually B2B Net will be called inside PlacementNet, but we set this API to handle pseudo net settings.
Parameters
objectiveMatrixTripletList The non-Diag elements in matrix Q, stored in the vector of Eigen Triplet (i,j,val)
objectiveMatrixDiag The Diag elements in matrix Q, stored in a 1-D vector
objectiveVector The elements in the vector P
puId0 PlacementUnit 0's Id (might be invaid -1)
puId1 PlacementUnit 1's Id (might be invaid -1)
pos0 PlacementUnit 0's position on one of the dimensions
pos1 PlacementUnit 1's position on one of the dimensions
pinOffset0 The pin's offset in PlacementUnit 0
pinOffset1 The pin's offset in PlacementUnit 1
movable0 whether the object 0 is movable
movable1 whether the object 0 is movable
w the weight of the net
Definition at line 3148 of file PlacementInfo.h.
Referenced by addPseudoNetsInPlacementInfo().
addPseudoNetsInPlacementInfo()
void PlacementInfo::addPseudoNetsInPlacementInfo (std::vector< Eigen::Triplet< float >> & objectiveMatrixTripletList, std::vector< float > & objectiveMatrixDiag, Eigen::VectorXd & objectiveVector, PlacementUnit * tmpPU, float targetLoc, float pseudoWeight, float y2xRatio, bool updateX, bool updateY) inline
directly set weight in the quadratic Matrix and vector according to given request.
Usually B2B Net will be called inside PlacementNet, but we set this API to handle pseudo net settings.
Parameters
objectiveMatrixTripletList The non-Diag elements in matrix Q, stored in the vector of Eigen Triplet (i,j,val)
objectiveMatrixDiag The Diag elements in matrix Q, stored in a 1-D vector
objectiveVector The elements in the vector P
tmpPU PlacementUnit which need a pseudo net
targetLoc the location of the anchor which the pseudo net connected to
pseudoWeight pseudo net weight to constrain the movement of PlacementUnits from their locations in last optimization iteration
y2xRatio a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
updateX update the X-coordinate term in the quadratic problem
updateY update the X-coordinate term in the quadratic problem
Definition at line 3217 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet2LoctionForAllPUs(), WirelengthOptimizer::addPseudoNetForMacros(), WirelengthOptimizer::updatePseudoNetForClockRegion(), and WirelengthOptimizer::updatePseudoNetForUserDefinedClusters().
addPUIntoClockColumn()
void PlacementInfo::addPUIntoClockColumn (PlacementInfo::PlacementUnit * curPU, DeviceInfo::DeviceSite * curSite) inline
map the given PlacementUnit to the site for later checking of the half-column clock legalization rules
Parameters
curPU a given PU
curSite the target site
Definition at line 4290 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::packCLBsIteration(), ParallelCLBPacker::prePackLegalizedMacros(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ParallelCLBPacker::PackingCLBSite::updateConsistentPUsInTop().
adjustLUTFFUtilization()
void PlacementInfo::adjustLUTFFUtilization (float neighborDisplacementUpperbound, bool enfore = false)
adjust the resource demand of LUTs/FFs according to packing feasibility and routing congestion
Parameters
neighborDisplacementUpperbound set displacement threshold to identify the neighbors of a cell
enfore enfore adjustment without considering other factors
Definition at line 1550 of file PlacementInfo.cc.
Referenced by AMFPlacer::run(), and GlobalPlacer::spreading().
adjustLUTFFUtilization_Clocking()
void PlacementInfo::adjustLUTFFUtilization_Clocking ()
adjust the utlization of clock-related elements to mitigate the overflow of clock utilization
Definition at line 1415 of file PlacementInfo.cc.
Referenced by adjustLUTFFUtilization().
adjustLUTFFUtilization_Packablity()
void PlacementInfo::adjustLUTFFUtilization_Packablity (float neighborDisplacementUpperbound, bool enfore)
adjust the resource demand of LUTs/FFs according to packing feasibility
Parameters
neighborDisplacementUpperbound set displacement threshold to identify the neighbors of a cell
enfore enfore adjustment without considering other factors
Definition at line 1079 of file PlacementInfo.cc.
Referenced by adjustLUTFFUtilization().
adjustLUTFFUtilization_Routability()
void PlacementInfo::adjustLUTFFUtilization_Routability (bool enfore)
adjust the resource demand of LUTs/FFs according to routing congestion refer to RippleFPGA's implementation
Parameters
enfore enfore adjustment without considering other factors
Definition at line 1279 of file PlacementInfo.cc.
Referenced by adjustLUTFFUtilization().
adjustLUTFFUtilization_Routability_Reset()
void PlacementInfo::adjustLUTFFUtilization_Routability_Reset ()
reset the inflate ratio of all the cells to be 1, for re-evaluation
Definition at line 1517 of file PlacementInfo.cc.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements(), and GlobalPlacer::updatePseudoNetWeight().
buildSimpleTimingGraph()
void PlacementInfo::buildSimpleTimingGraph () inline
call timing info to build simple timing graph
Definition at line 4320 of file PlacementInfo.h.
Referenced by AMFPlacer::run().
calculateNetNumDistributionOfPUs()
void PlacementInfo::calculateNetNumDistributionOfPUs () inline
calculate the proportion of the PlacementUnit objects with high interconnection density
if a PlacementUnit connects to more than 30 nets, count it. calculate the proportion of the PlacementUnit objects with high interconnection density
Definition at line 4165 of file PlacementInfo.h.
Referenced by InitialPacker::pack().
checkClockColumnLegalization()
bool PlacementInfo::checkClockColumnLegalization (PlacementInfo::PlacementUnit * curPU, DeviceInfo::DeviceSite * curSite) inline
check whether the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
Parameters
curPU a given PU
curSite the target site
Returns
true if the the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
false if the the given PlacementUnit CANNOT be mapped to the site considering the half-column clock legalization rules
Definition at line 4231 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::areAllPUsValidForThisSite(), ParallelCLBPacker::packCLBsIteration(), and ParallelCLBPacker::PackingCLBSite::updateConsistentPUsInTop().
checkClockUtilization()
bool PlacementInfo::checkClockUtilization (bool dump)
check the utlization of the clock regions on the device
Parameters
dump dump the clock utilization
Returns
true if the placement does not cause clock legalization problem
false if the placement causes clock legalization problem
Definition at line 2093 of file PlacementInfo.cc.
Referenced by ClusterPlacer::ClusterPlacement(), GlobalPlacer::GlobalPlacement_CLBElements(), and AMFPlacer::run().
createGridBins()
void PlacementInfo::createGridBins (float binWidth, float binHeight)
Create a grid of bins on the device.
Parameters
binWidth the width of each bin
binHeight the height of each bin
Definition at line 307 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
createSiteBinGrid()
void PlacementInfo::createSiteBinGrid ()
Definition at line 1588 of file PlacementInfo.cc.
deleteLegalizationInfoFor()
void PlacementInfo::deleteLegalizationInfoFor (PlacementInfo::PlacementUnit * curPU) inline
remove the legalization information of a PlacementUnit object
Parameters
curPU
Definition at line 3703 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::updatePackedMacro().
dumpCongestion()
void PlacementInfo::dumpCongestion (std::string dumpFileName)
dump the congestion mesh grid for evaluation
Parameters
dumpFileName
Definition at line 1568 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
dumpOverflowClockUtilization()
void PlacementInfo::dumpOverflowClockUtilization ()
Definition at line 2169 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
dumpPlacementUnitInformation()
void PlacementInfo::dumpPlacementUnitInformation (std::string dumpFile)
dump the PlacementUnit objects and some placement parameters as a checkpoint
Parameters
dumpFile
Definition at line 1729 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
dumpVivadoPlacementTclWithPULegalizationInfo()
void PlacementInfo::dumpVivadoPlacementTclWithPULegalizationInfo (std::string dumpFile)
dump the placement commands to place cells in Vivado (do not use this temporarily)
(do not use this temporarily) We move this functionality to the packer/placer. There is a conterpart function in ParallelPack, which is relatively complete. We will collect those information back to PlacementInfo in later implementation.
Parameters
dumpFile
Definition at line 1702 of file PlacementInfo.cc.
enforceLegalizeXYInArea()
void PlacementInfo::enforceLegalizeXYInArea (PlacementUnit * curPU) inline
move the PlacementUnit to ensure the cells in it are within the device area.
Parameters
curPU target PlacementUnit
Definition at line 3391 of file PlacementInfo.h.
Referenced by optimizeLongPaths(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocationsWorker().
enhanceDDRNet()
void PlacementInfo::enhanceDDRNet ()
Definition at line 2079 of file PlacementInfo.cc.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
enhanceHighFanoutNet()
void PlacementInfo::enhanceHighFanoutNet ()
Definition at line 2025 of file PlacementInfo.cc.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
enhanceRiskyClockNet()
void PlacementInfo::enhanceRiskyClockNet ()
Definition at line 2040 of file PlacementInfo.cc.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
findNeiborLUTFFsFromBinGrid()
std::vector<DesignInfo::DesignCell *>* PlacementInfo::findNeiborLUTFFsFromBinGrid (DesignInfo::DesignCell * curCell, float displacementUpperbound, int minNumNeighbor = 10) inline
find neibor LUTs/FFs from bin grid
Parameters
curCell target Cell
displacementUpperbound displacement threshold
minNumNeighbor currently not used
Returns
std::vector<DesignInfo::DesignCell *>*
Definition at line 2998 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity().
findNeiborSiteFromBinGrid()
std::vector<DeviceInfo::DeviceSite *>* PlacementInfo::findNeiborSiteFromBinGrid (DesignInfo::DesignCell * curCell, float targetX, float targetY, float displacementThreshold, int siteNumThreshold, bool checkClockRegion = false) inline
find neibor device sites of a given cell from bin grid
Parameters
curCell target cell
targetX target location X
targetY target location Y
displacementThreshold the displacement threshold from the sites to the target location
siteNumThreshold if the number of sites exceed this threshold, stop the searching
checkClockRegion enable to check whether the clock region column of the sites are the same as the one of the cell
Returns
std::vector<DeviceInfo::DeviceSite *>*
Definition at line 3788 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::dumpFinalPacking(), MacroLegalizer::findMacroCell2SitesInDistance(), and CLBLegalizer::findPU2SitesInDistance().
getActualOccupation()
float PlacementInfo::getActualOccupation (DesignInfo::DesignCell * cell) inline
Get the actual occupation of a specific cell.
Parameters
cell
Returns
float
it will be the multiplication of cellId2Occupation and cellId2InfationRatio. cellId2Occupation might be adjusted by the packing feasibility. cellId2InfationRatio might be adjusted by the routing congestion level.
Definition at line 2946 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::exceptionHandling(), and updateElementBinGrid().
getActualOccupationByCellId()
float PlacementInfo::getActualOccupationByCellId (int id) inline
Get the Actual Occupation By Cell Id.
Parameters
id
Returns
float
Definition at line 2984 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::dumpFinalPacking(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getTotalCellWeight(), GeneralSpreader::SpreadRegion::SubBox::spreadCellsH(), and GeneralSpreader::SpreadRegion::SubBox::spreadCellsV().
getBELType2FalseBELType()
std::string PlacementInfo::getBELType2FalseBELType (std::string curBELType) inline
get the remapped BEL type of a specific BEL type since some cell can be placed in sites of different sites. For cell spreading, we need to remap some BEL types to a unified BEL types. Belows are some examples:
SLICEM_CARRY8 => SLICEL_CARRY8
SLICEM_LUT => SLICEL_LUT
SLICEM_FF => SLICEL_FF
Parameters
curBELType
Returns
std::string
Definition at line 3320 of file PlacementInfo.h.
Referenced by createGridBins().
getBinGrid() [1/2]
std::vector<std::vector<std::vector<PlacementBinInfo *> > >& PlacementInfo::getBinGrid () inline
Get the Bin Grid object for all types of BEL.
Returns
std::vector<std::vector<std::vector<PlacementBinInfo *>>>&
Definition at line 3099 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), adjustLUTFFUtilization_Routability(), adjustLUTFFUtilization_Routability_Reset(), and updateElementBinGrid().
getBinGrid() [2/2]
std::vector<std::vector<PlacementBinInfo *> >& PlacementInfo::getBinGrid (unsigned int BELTypeId) inline
Get the Bin Grid object.
Parameters
BELTypeId indicate the target BELtype ID, since we map the different resource to different grid for easier processing
Returns
std::vector<std::vector<PlacementBinInfo *>>&
Definition at line 3088 of file PlacementInfo.h.
Referenced by GeneralSpreader::dumpSiteGridDensity(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), and ParallelCLBPacker::findNeiborSitesFromBinGrid().
getBinGridH()
float PlacementInfo::getBinGridH () inline
Get the height of a bin in grid.
Returns
float
Definition at line 3614 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SubBox::spreadCellsV().
getBinGridW()
float PlacementInfo::getBinGridW () inline
Get the width of a bin in grid.
Returns
float
Definition at line 3604 of file PlacementInfo.h.
Referenced by GeneralSpreader::SpreadRegion::SubBox::spreadCellsH(), and GlobalPlacer::spreading().
getCellId2CellBinInfo()
std::vector<CellBinInfo>& PlacementInfo::getCellId2CellBinInfo () inline
Definition at line 3882 of file PlacementInfo.h.
getCellId2location()
std::vector<Location>& PlacementInfo::getCellId2location () inline
Definition at line 3589 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementTimingOptimizer::conductStaticTimingAnalysis(), GeneralSpreader::DumpCellsCoordinate(), IncrementalBELPacker::FFPairing(), PlacementTimingOptimizer::getPUId2Slack(), PlacementTimingOptimizer::getSlackThr(), PlacementTimingOptimizer::getWorstSlackOfCell(), IncrementalBELPacker::LUTFFPairing(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), GeneralSpreader::SpreadRegion::SubBox::Partition(), PlacementTimingOptimizer::setPinsLocation(), GeneralSpreader::SpreadRegion::SubBox::spreadCellsH(), GeneralSpreader::SpreadRegion::SubBox::spreadCellsV(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::updatePackedMacro(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocationsWorker().
getcellId2Occupation()
std::vector<float>& PlacementInfo::getcellId2Occupation () inline
Definition at line 2962 of file PlacementInfo.h.
getCellId2PlacementUnit()
std::map<int, PlacementUnit *>& PlacementInfo::getCellId2PlacementUnit () inline
Definition at line 2819 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacement_fixedCLB().
getCellId2PlacementUnitVec()
std::vector<PlacementUnit *>& PlacementInfo::getCellId2PlacementUnitVec () inline
Definition at line 2823 of file PlacementInfo.h.
getCellInMacros()
std::set<DesignInfo::DesignCell *>& PlacementInfo::getCellInMacros () inline
Definition at line 2815 of file PlacementInfo.h.
getCells()
std::vector<DesignInfo::DesignCell *>& PlacementInfo::getCells () inline
Definition at line 3887 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), adjustLUTFFUtilization_Packablity(), adjustLUTFFUtilization_Routability(), adjustLUTFFUtilization_Routability_Reset(), ParallelCLBPacker::checkPackedPUsAndUnpackedPUs(), ParallelCLBPacker::dumpFinalPacking(), MacroLegalizer::getMacrosToLegalize(), GlobalPlacer::GlobalPlacement_fixedCLB(), loadPlacementUnitInformation(), ParallelCLBPacker::packCLBs(), PlacementTimingOptimizer::setPinsLocation(), and GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate().
getClockCol2ClockNets()
std::map<DeviceInfo::ClockColumn *, std::set<DesignInfo::DesignNet *> >& PlacementInfo::getClockCol2ClockNets () inline
Definition at line 4357 of file PlacementInfo.h.
getClockColumnUtilizationIncrease()
int PlacementInfo::getClockColumnUtilizationIncrease (PlacementInfo::PlacementUnit * curPU, DeviceInfo::DeviceSite * curSite) inline
check the clock resource increase extent if the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
Parameters
curPU a given PU
curSite the target site
Returns
true if the the given PlacementUnit can be mapped to the site considering the half-column clock legalization rules
int
Definition at line 4255 of file PlacementInfo.h.
getClusterNum()
int PlacementInfo::getClusterNum () inline
Definition at line 4372 of file PlacementInfo.h.
Referenced by isDensePlacement().
getCompatiblePlacementTable()
CompatiblePlacementTable* PlacementInfo::getCompatiblePlacementTable () inline
Definition at line 2729 of file PlacementInfo.h.
Referenced by loadPlacementUnitInformation(), and ParallelCLBPacker::updatePackedMacro().
getDesignInfo()
DesignInfo* PlacementInfo::getDesignInfo () inline
Definition at line 3292 of file PlacementInfo.h.
Referenced by ClusterPlacer::clockBasedPartitioning(), ClusterPlacer::createClockBasedClusterUnits(), ClusterPlacer::createUserDefinedClusterBasedClusterUnits(), GlobalPlacer::GlobalPlacement_CLBElements(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), PlacementTimingOptimizer::PlacementTimingOptimizer(), ClusterPlacer::refineClustersWithPredefinedClusters(), WirelengthOptimizer::reloadPlacementInfo(), and WirelengthOptimizer::updatePseudoNetForUserDefinedClusters().
getDeterminedOccupation()
int PlacementInfo::getDeterminedOccupation (int cellId) inline
@briefget the Determined Occupation of a specific cell
LUTFFDeterminedOccupation is used to record the final resource demand of a LUT/FF after final packing
Parameters
cellId target cell
Returns
int
Definition at line 4088 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity().
getDeviceInfo()
DeviceInfo* PlacementInfo::getDeviceInfo () inline
Definition at line 3297 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), ParallelCLBPacker::findNeiborSitesFromBinGrid(), PlacementInfo::PlacementNet::getNewHPWLByTrying(), GlobalPlacer::GlobalPlacer(), ClusterPlacer::isDensePlacement(), isDensePlacement(), GlobalPlacer::macroLegalize(), ParallelCLBPacker::ParallelCLBPacker(), PlacementTimingOptimizer::PlacementTimingOptimizer(), PlacementInfo::PlacementNet::updateBound2BoundNetWeight(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and WirelengthOptimizer::updatePseudoNetForClockRegion().
getDeviceMaxEdgeLength()
float PlacementInfo::getDeviceMaxEdgeLength () inline
Definition at line 2916 of file PlacementInfo.h.
getDisplacement()
float PlacementInfo::getDisplacement (float fX, float fY, DeviceInfo::DeviceSite * curSite) inline
Get the Displacement from a given location to a device site (y2xRatio is considered.)
Parameters
fX given X
fY given Y
curSite target device site
Returns
float
Definition at line 3770 of file PlacementInfo.h.
Referenced by findNeiborSiteFromBinGrid().
getFixedPlacementUnits()
std::vector<PlacementUnit *>& PlacementInfo::getFixedPlacementUnits () inline
Definition at line 2807 of file PlacementInfo.h.
Referenced by ClusterPlacer::setClusterNetsAdjMat().
getGlobalBinGrid()
std::vector<std::vector<PlacementBinInfo *> >& PlacementInfo::getGlobalBinGrid () inline
Definition at line 4362 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::stretchClockRegionColumns().
getGlobalBinMaxLocX()
float PlacementInfo::getGlobalBinMaxLocX () inline
get right boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 2881 of file PlacementInfo.h.
getGlobalBinMaxLocY()
float PlacementInfo::getGlobalBinMaxLocY () inline
get top boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 2891 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::stretchClockRegionColumns().
getGlobalBinMinLocX()
float PlacementInfo::getGlobalBinMinLocX () inline
get left boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 2901 of file PlacementInfo.h.
getGlobalBinMinLocY()
float PlacementInfo::getGlobalBinMinLocY () inline
get bottom boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 2911 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::stretchClockRegionColumns().
getGlobalMaxX()
float PlacementInfo::getGlobalMaxX () inline
Get the Global Max X (right boundary of the device)
Returns
float
Definition at line 2841 of file PlacementInfo.h.
Referenced by ClusterPlacer::ClusterPlacement(), GeneralSpreader::makeCellInLegalArea(), ClusterPlacer::placeClusters(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), WirelengthOptimizer::reloadPlacementInfo(), ClusterPlacer::setClusterNetsAdjMat(), and WirelengthOptimizer::WirelengthOptimizer().
getGlobalMaxY()
float PlacementInfo::getGlobalMaxY () inline
Get the Global Max Y (top boundary of the device)
Returns
float
Definition at line 2851 of file PlacementInfo.h.
Referenced by ClusterPlacer::ClusterPlacement(), GeneralSpreader::makeCellInLegalArea(), ClusterPlacer::placeClusters(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), WirelengthOptimizer::reloadPlacementInfo(), and WirelengthOptimizer::WirelengthOptimizer().
getGlobalMinX()
float PlacementInfo::getGlobalMinX () inline
Get the Global Min X (left boundary of the device)
Returns
float
Definition at line 2861 of file PlacementInfo.h.
Referenced by ClusterPlacer::ClusterPlacement(), GeneralSpreader::makeCellInLegalArea(), ClusterPlacer::placeClusters(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), WirelengthOptimizer::reloadPlacementInfo(), ClusterPlacer::setClusterNetsAdjMat(), and WirelengthOptimizer::WirelengthOptimizer().
getGlobalMinY()
float PlacementInfo::getGlobalMinY () inline
Get the Global Min Y (bottom boundary of the device)
Returns
float
Definition at line 2871 of file PlacementInfo.h.
Referenced by ClusterPlacer::ClusterPlacement(), GeneralSpreader::makeCellInLegalArea(), ClusterPlacer::placeClusters(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), WirelengthOptimizer::reloadPlacementInfo(), and WirelengthOptimizer::WirelengthOptimizer().
getGridXY()
void PlacementInfo::getGridXY (float cellX, float cellY, int & binIdX, int & binIdY) inline
Get the Grid row/column based on given location X,Y.
Parameters
cellX input X
cellY input Y
binIdX output target column of grid
binIdY output target row of grid
Definition at line 3333 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity(), adjustLUTFFUtilization_Routability(), findNeiborLUTFFsFromBinGrid(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), findNeiborSiteFromBinGrid(), ParallelCLBPacker::findNeiborSitesFromBinGrid(), PlacementTimingOptimizer::stretchClockRegionColumns(), transferCellBinInfo(), and updateElementBinGrid().
getHighFanOutThr()
int PlacementInfo::getHighFanOutThr () inline
Definition at line 4388 of file PlacementInfo.h.
getInflateRatio()
float PlacementInfo::getInflateRatio (DesignInfo::DesignCell * cell) inline
Get the inflate ratio of a cell.
Parameters
cell
Returns
float
Definition at line 2957 of file PlacementInfo.h.
getLongPaths()
std::vector<std::vector<PlacementUnit *> >& PlacementInfo::getLongPaths () inline
Get the Long Paths in the net list for later optimization.
Returns
std::vector<std::vector<PlacementUnit *>>&
Definition at line 4305 of file PlacementInfo.h.
getLongPathThresholdLevel()
int PlacementInfo::getLongPathThresholdLevel () inline
Definition at line 4347 of file PlacementInfo.h.
Referenced by ClusterPlacer::createLongPathClusterUnits(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), and AMFPlacer::run().
getMacroLegalizationWeight()
float PlacementInfo::getMacroLegalizationWeight () inline
Get the Macro Legalization Weight.
it is the legalization pseudo nets for macros.
Returns
float
Definition at line 4049 of file PlacementInfo.h.
Referenced by dumpPlacementUnitInformation().
getMacroPseudoNetEnhanceCnt()
int PlacementInfo::getMacroPseudoNetEnhanceCnt () inline
Get the Macro Pseudo Net Enhance Counter.
The legalization pseudo nets for macros are strengthened as this counter is increased, so we can force the macros get closer and closer to their legal location.
Returns
int
Definition at line 4029 of file PlacementInfo.h.
Referenced by dumpPlacementUnitInformation().
getMacroRatio()
float PlacementInfo::getMacroRatio () inline
Definition at line 4407 of file PlacementInfo.h.
getMaxXFromSites()
float PlacementInfo::getMaxXFromSites (std::vector< DeviceInfo::DeviceSite * > & sites)
Get the Max X of sites to identify the boundary of the device.
Parameters
sites
Returns
float
Definition at line 254 of file PlacementInfo.cc.
Referenced by PlacementInfo().
getMaxYFromSites()
float PlacementInfo::getMaxYFromSites (std::vector< DeviceInfo::DeviceSite * > & sites)
Get the Max Y of sites to identify the boundary of the device.
Parameters
sites
Returns
float
Definition at line 265 of file PlacementInfo.cc.
Referenced by PlacementInfo().
getMediumPathThresholdLevel()
int PlacementInfo::getMediumPathThresholdLevel () inline
Definition at line 4352 of file PlacementInfo.h.
Referenced by ClusterPlacer::setClusterNetsAdjMat().
getMinHPWL()
float PlacementInfo::getMinHPWL () inline
Definition at line 4199 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacer().
getMinXFromSites()
float PlacementInfo::getMinXFromSites (std::vector< DeviceInfo::DeviceSite * > & sites)
Get the Min X of sites to identify the boundary of the device.
Parameters
sites
Returns
float
Definition at line 232 of file PlacementInfo.cc.
Referenced by PlacementInfo().
getMinYFromSites()
float PlacementInfo::getMinYFromSites (std::vector< DeviceInfo::DeviceSite * > & sites)
Get the Min Y of sites to identify the boundary of the device.
Parameters
sites
Returns
float
Definition at line 243 of file PlacementInfo.cc.
Referenced by PlacementInfo().
getNetDistributionByDensity()
int PlacementInfo::getNetDistributionByDensity (int density) inline
Definition at line 4393 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), and PlacementTimingOptimizer::conductStaticTimingAnalysis().
getNumCells()
int PlacementInfo::getNumCells () inline
Definition at line 2831 of file PlacementInfo.h.
Referenced by ClusterPlacer::hypergraphPartitioning().
getOccupation()
float PlacementInfo::getOccupation (DesignInfo::DesignCellType cellType) inline
Get the theoratical occupation of a specific cell type.
Parameters
cellType
Returns
float
Definition at line 2973 of file PlacementInfo.h.
getPairPinNum()
unsigned int PlacementInfo::getPairPinNum (DesignInfo::DesignCell * LUTA, DesignInfo::DesignCell * LUTB) inline
Get the Pair Pin Num of two LUTs.
Two LUTs can share the input pins of a BEL in CLB. However, device architecture might have requirements on their demands of the number of input pins. This function will return the total number of input pins for the two LUTs.
Parameters
LUTA LUT Cell A
LUTB LUT Cell A
Returns
unsigned int
Definition at line 4116 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity().
getPinId2location()
std::vector<Location>& PlacementInfo::getPinId2location () inline
Definition at line 3594 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::conductStaticTimingAnalysis(), PlacementTimingOptimizer::incrementalStaticTimingAnalysis_forPUWithLocation(), and PlacementTimingOptimizer::setPinsLocation().
getPlacementMacros()
std::vector<PlacementMacro *>& PlacementInfo::getPlacementMacros () inline
Definition at line 2803 of file PlacementInfo.h.
Referenced by InitialPacker::dumpMacroHighLight().
getPlacementNetByDesignNetId()
PlacementNet* PlacementInfo::getPlacementNetByDesignNetId (int netId) inline
Definition at line 3123 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::LUTLUTPairing_TimingDriven().
getPlacementNets()
std::vector<PlacementNet *>& PlacementInfo::getPlacementNets () inline
Definition at line 2811 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), ClusterPlacer::basicPartitioning(), ClusterPlacer::creaeClusterNets(), InitialPacker::enhanceIONets(), PlacementTimingOptimizer::getSlackThr(), WirelengthOptimizer::reloadPlacementInfo(), ClusterPlacer::setClusterNetsAdjMat(), WirelengthOptimizer::updateB2BNetWeight(), and WirelengthOptimizer::updateB2BNetWeightWorker().
getPlacementUnitByCell()
PlacementUnit* PlacementInfo::getPlacementUnitByCell (DesignInfo::DesignCell * curCell) inline
Definition at line 3109 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::checkPackedPUsAndUnpackedPUs(), ClusterPlacer::createClockBasedClusterUnits(), ClusterPlacer::createLongPathClusterUnits(), ClusterPlacer::createUserDefinedClusterBasedClusterUnits(), ParallelCLBPacker::dumpCLBPlacementTcl(), ParallelCLBPacker::dumpFinalPacking(), MacroLegalizer::dumpMatching(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), MacroLegalizer::getHPWLChange(), MacroLegalizer::getMacrosToLegalize(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::isCarryMacro(), ParallelCLBPacker::PackingCLBSite::isCarryMacro(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::isMuxMacro(), ParallelCLBPacker::PackingCLBSite::isMuxMacro(), ParallelCLBPacker::PackingCLBSite::mapCarryRelatedCellsToSlots(), ClusterPlacer::refineClustersWithPredefinedClusters(), GeneralSpreader::spreadPlacementUnits(), WirelengthOptimizer::updatePseudoNetForUserDefinedClusters(), and MacroLegalizer::updatePUMatchingLocation().
getPlacementUnitByCellId()
PlacementUnit* PlacementInfo::getPlacementUnitByCellId (int cellId) inline
Definition at line 3116 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ClusterPlacer::createLongPathClusterUnits(), PlacementTimingOptimizer::findCriticalPaths(), findNeiborSiteFromBinGrid(), MacroLegalizer::findPossibleLegalLocation(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), ParallelCLBPacker::packCLBs(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations().
getPlacementUnitId2Nets()
std::vector<std::vector<PlacementNet *> >& PlacementInfo::getPlacementUnitId2Nets () inline
Definition at line 3892 of file PlacementInfo.h.
Referenced by CLBLegalizer::getHPWLChange(), and MacroLegalizer::getHPWLChange().
getPlacementUnits()
std::vector<PlacementUnit *>& PlacementInfo::getPlacementUnits () inline
Definition at line 2799 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet2LoctionForAllPUs(), ClusterPlacer::basicPartitioning(), AMFPlacer::clearSomeAttributesCannotRecord(), ClusterPlacer::clockBasedPartitioning(), ClusterPlacer::ClusterPlacement(), ClusterPlacer::createLongPathClusterUnits(), ClusterPlacer::createSinglePUClusterUnits(), ClusterPlacer::createUserDefinedClusterBasedClusterUnits(), GlobalPlacer::dumpAllCellsCoordinate(), ParallelCLBPacker::dumpAllCellsCoordinate(), GlobalPlacer::dumpBRAMCoordinate(), GlobalPlacer::dumpCARRYCoordinate(), PlacementTimingOptimizer::dumpClockRegionClusters(), ClusterPlacer::dumpClusters(), GlobalPlacer::dumpDSPCoordinate(), GlobalPlacer::dumpFFCoordinate(), ParallelCLBPacker::dumpFinalPacking(), GlobalPlacer::dumpLUTCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), dumpPlacementUnitInformation(), PlacementTimingOptimizer::getPUId2Slack(), CLBLegalizer::getPUsToLegalize(), ClusterPlacer::isClustersToLarges(), ParallelCLBPacker::packCLBs(), ParallelCLBPacker::packCLBsIteration(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), GlobalPlacer::printPlacedUnits(), GeneralSpreader::recordSpreadedCellLocations(), WirelengthOptimizer::reloadPlacementInfo(), ClusterPlacer::resetClusterInfo(), ClusterPlacer::setClusterNetsAdjMat(), WirelengthOptimizer::solverLoadData(), WirelengthOptimizer::solverLoadFixedData(), WirelengthOptimizer::solverWriteBackData(), PlacementTimingOptimizer::stretchClockRegionColumns(), WirelengthOptimizer::updateB2BNetWeightWorker(), ClusterPlacer::userDefinedClusterBasedPartitioning(), and WirelengthOptimizer::WirelengthOptimizer().
getPlacementUnpackedCells()
std::vector<PlacementUnpackedCell *>& PlacementInfo::getPlacementUnpackedCells () inline
Definition at line 2827 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::addNonCLBPackingSites().
getPotentialBELTypeIDs() [1/2]
std::vector<int>& PlacementInfo::getPotentialBELTypeIDs (DesignInfo::DesignCell * cell) inline
Definition at line 2921 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), adjustLUTFFUtilization_Routability(), adjustLUTFFUtilization_Routability_Reset(), MacroLegalizer::findMacroType2AvailableSites(), ParallelCLBPacker::PackingCLBSite::findNeiborPUsFromBinGrid(), findNeiborSiteFromBinGrid(), ParallelCLBPacker::findNeiborSitesFromBinGrid(), and updateElementBinGrid().
getPotentialBELTypeIDs() [2/2]
std::vector<int>& PlacementInfo::getPotentialBELTypeIDs (DesignInfo::DesignCellType cellType) inline
Definition at line 2926 of file PlacementInfo.h.
getProgress()
float PlacementInfo::getProgress () inline
Get the Progress ratio of the placement.
Returns
float
Definition at line 3958 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet2LoctionForAllPUs(), WirelengthOptimizer::addPseudoNetForMacros(), adjustLUTFFUtilization(), adjustLUTFFUtilization_Packablity(), and GlobalPlacer::GlobalPlacement_CLBElements().
getPseudoNetWeight()
float PlacementInfo::getPseudoNetWeight () inline
Get the Pseudo Net Weight object.
usually it is used to set the configuration of placer or dump placement information
Returns
float
Definition at line 4015 of file PlacementInfo.h.
Referenced by dumpPlacementUnitInformation(), and ParallelCLBPacker::packCLBs().
getPU2ClockRegionCenters()
std::map<PlacementUnit *, std::pair<float, float> >& PlacementInfo::getPU2ClockRegionCenters () inline
get the PlacementUnit Mapping to clock region centers for timing optimzation
Returns
std::map<PlacementUnit *, std::pair<float, float>>&
Definition at line 4332 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ParallelCLBPacker::packCLBs(), AMFPlacer::run(), and WirelengthOptimizer::updatePseudoNetForClockRegion().
getPU2ClockRegionColumn()
std::map<PlacementUnit *, int>& PlacementInfo::getPU2ClockRegionColumn () inline
get the PlacementUnit Mapping to clock region column for timing optimzation
Returns
std::map<PlacementUnit *, int>&
Definition at line 4342 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementTimingOptimizer::stretchClockRegionColumns(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and WirelengthOptimizer::updatePseudoNetForClockRegion().
getPULegalSite()
std::map<PlacementInfo::PlacementUnit *, std::vector<DeviceInfo::DeviceSite *> >& PlacementInfo::getPULegalSite () inline
get the sites occupied by the legalized PlacementUnit objects
Returns
std::map<PlacementInfo::PlacementUnit *, std::vector<DeviceInfo::DeviceSite *>>&
Definition at line 3670 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::addNonCLBPackingSites(), ParallelCLBPacker::dumpDSPBRAMPlacementTcl(), and ParallelCLBPacker::prePackLegalizedMacros().
getPULegalXY()
std::pair<std::map<PlacementInfo::PlacementUnit *, float>, std::map<PlacementInfo::PlacementUnit *, float> >& PlacementInfo::getPULegalXY () inline
get the locations (pair of X,Y) of the legalized PlacementUnit objects
Returns
std::pair<std::map<PlacementInfo::PlacementUnit *, float>, std::map<PlacementInfo::PlacementUnit *, float>>&
Definition at line 3682 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNetForMacros(), AMFPlacer::clearSomeAttributesCannotRecord(), MacroLegalizer::dumpMatching(), and GlobalPlacer::macroLegalize().
getPULocationByCellLocation()
void PlacementInfo::getPULocationByCellLocation (DesignInfo::DesignCell * curCell, float targetX, float targetY, float & PUX, float & PUY) inline
Definition at line 3535 of file PlacementInfo.h.
Referenced by MacroLegalizer::updatePUMatchingLocation().
getPUWithManyNetsRatio()
float PlacementInfo::getPUWithManyNetsRatio () inline
get the proportion of the PlacementUnit objects with high interconnection density
Returns
float
Definition at line 4183 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacer().
getSharedBELTypeId()
int PlacementInfo::getSharedBELTypeId (std::string tmpStr) inline
Definition at line 2931 of file PlacementInfo.h.
Referenced by GeneralSpreader::dumpSiteGridDensity().
getSiteBinGrid()
std::vector<std::vector<PlacementSiteBinInfo *> >& PlacementInfo::getSiteBinGrid () inline
Definition at line 3104 of file PlacementInfo.h.
getTimingInfo()
PlacementTimingInfo* PlacementInfo::getTimingInfo () inline
Definition at line 3302 of file PlacementInfo.h.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), ParallelCLBPacker::PackingCLBSite::checkDirectLUTFFConnect_slack(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ClusterPlacer::createLongPathClusterUnits(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCarrySite(), ParallelCLBPacker::PackingCLBSite::finalMapToSlotsForCommonLUTFFInSite(), ClusterPlacer::getPlacementUnitMaxPathLen(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathLen(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::getPlacementUnitMaxPathNegativeSlack(), PlacementTimingOptimizer::getPUId2Slack(), PlacementTimingOptimizer::getSlackThr(), PlacementTimingOptimizer::getWorstSlackOfCell(), ParallelCLBPacker::PackingCLBSite::greedyMapMuxForCommonLUTFFInSite(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), and AMFPlacer::run().
getTotalHPWL()
double PlacementInfo::getTotalHPWL () inline
get the total HPWL of all the nets in the design without updating the B2B net model for the placement
Returns
double
Definition at line 3928 of file PlacementInfo.h.
isClockLegalizationRisky()
bool PlacementInfo::isClockLegalizationRisky () inline
Definition at line 4383 of file PlacementInfo.h.
Referenced by GlobalPlacer::updatePseudoNetWeight().
isDensePlacement()
bool PlacementInfo::isDensePlacement () inline
Definition at line 4377 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ParallelCLBPacker::exceptionHandling(), and GlobalPlacer::updatePseudoNetWeight().
isLegalLocation() [1/2]
bool PlacementInfo::isLegalLocation (DesignInfo::DesignCell * curCell, float targetX, float targetY) inline
check whether the PlacementUnit is legalized in the device area when a cell in it is placed at target location
Parameters
curCell
targetX
targetY
Returns
true the PlacementUnit is legalized in the device area when a cell in it is placed at target location
false the PlacementUnit cannot be legalized in the device area when a cell in it is placed at target location
Definition at line 3441 of file PlacementInfo.h.
Referenced by CLBLegalizer::findPossibleLegalLocation(), and MacroLegalizer::findPossibleLegalLocation().
isLegalLocation() [2/2]
bool PlacementInfo::isLegalLocation (PlacementUnit * curPU, float targetX, float targetY) inline
check whether the PlacementUnit is legalized in the device area when it is placed at target location
Parameters
curPU
targetX
targetY
Returns
true the PlacementUnit is legalized in the device area when a cell in it is placed at target location
false the PlacementUnit cannot be legalized in the device area when a cell in it is placed at target location
Definition at line 3495 of file PlacementInfo.h.
legalizeXYInArea()
void PlacementInfo::legalizeXYInArea (PlacementUnit * curPU, float & fX, float & fY) inline
move the PlacementUnit to ensure the cells in it are within the device area.
Parameters
curPU target PlacementUnit
fX output X of PlacementUnit that can ensure the cells in it are within the device area.
fY output Y of PlacementUnit that can ensure the cells in it are within the device area.
Definition at line 3353 of file PlacementInfo.h.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ClusterPlacer::ClusterPlacement(), IncrementalBELPacker::FFPairing(), IncrementalBELPacker::LUTFFPairing(), ClusterPlacer::placeUnitBaseOnClusterPlacement(), WirelengthOptimizer::solverWriteBackData(), PlacementTimingOptimizer::stretchClockRegionColumns(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocationsWorker(), and WirelengthOptimizer::updatePseudoNetForUserDefinedClusters().
loadCompatiblePlacementTable()
CompatiblePlacementTable* PlacementInfo::loadCompatiblePlacementTable (std::string cellType2fixedAmoFileName, std::string cellType2sharedCellTypeFileName, std::string sharedCellType2BELtypeFileName) inline
describes the type mapping from design to device, where a cell can be placed (which BEL in which site)
Since different cell types can be mapped to a group of resource BEL types, we handle the mapping in the following way, with a intermediate Shared BEL Type:
cell type A => A => BEL type 1
cell type B => Shared => BEL type 2
cell type C => BEL => BEL type 3
cell type D => Type => BEL type 4
Parameters
cellType2fixedAmoFileName a file indicates how many slot will a cell of specific type cost
cellType2sharedCellTypeFileName a file indicates the mapping from cell types to shared BEL types
sharedCellType2BELtypeFileName a file indicates the mapping from shared BEL types to resource BEL types
Returns
CompatiblePlacementTable*
Definition at line 2721 of file PlacementInfo.h.
Referenced by PlacementInfo().
loadPlacementUnitInformation()
void PlacementInfo::loadPlacementUnitInformation (std::string locationFile)
load the data of the PlacementUnit objects and some placement parameters from a checkpoint file
Parameters
locationFile
Definition at line 1758 of file PlacementInfo.cc.
optimizeLongPaths()
void PlacementInfo::optimizeLongPaths ()
make the PlacementUnits in the long path closer to each other
Definition at line 705 of file PlacementInfo.cc.
printOutClockColumnLegalization()
void PlacementInfo::printOutClockColumnLegalization (PlacementInfo::PlacementUnit * curPU, DeviceInfo::DeviceSite * curSite) inline
Definition at line 4267 of file PlacementInfo.h.
printStat()
void PlacementInfo::printStat (bool verbose = false)
Definition at line 276 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
reloadNets()
void PlacementInfo::reloadNets ()
update PlacementNet objects when there are some updates of PlacementUnit objects (e.g., some cells are packed)
Definition at line 489 of file PlacementInfo.cc.
Referenced by IncrementalBELPacker::FFPairing(), loadPlacementUnitInformation(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::pack(), and ParallelCLBPacker::updatePackedMacro().
resetElementBinGrid()
void PlacementInfo::resetElementBinGrid ()
clean the information in bin grid
Definition at line 881 of file PlacementInfo.cc.
Referenced by updateElementBinGrid().
resetLUTFFDeterminedOccupation()
void PlacementInfo::resetLUTFFDeterminedOccupation () inline
reset the LUTFFDeterminedOccupation object
LUTFFDeterminedOccupation is used to record the final resource demand of a LUT/FF after final packing
Definition at line 4076 of file PlacementInfo.h.
Referenced by AMFPlacer::run().
resetPULegalInformation()
void PlacementInfo::resetPULegalInformation () inline
forget all the legalization information
Definition at line 3691 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacer().
resetSiteBinGrid()
void PlacementInfo::resetSiteBinGrid ()
Definition at line 1656 of file PlacementInfo.cc.
setBELTypeForCells()
void PlacementInfo::setBELTypeForCells (DesignInfo * designInfo) inline
Definition at line 2734 of file PlacementInfo.h.
setCellBinInfo()
void PlacementInfo::setCellBinInfo (int cellId, int sharedTypeId, int X, int Y, float occupation) inline
Set the cell bin Information of a design cell.
Parameters
cellId the Id of the design cell
sharedTypeId which BEL type the design cell is
X the column in the grid of the bin which the cell is located in
Y the row in the grid of the bin which the cell is located in
occupation how much resource is cost by the design cell
Definition at line 3722 of file PlacementInfo.h.
Referenced by updateElementBinGrid().
setClusterNum()
void PlacementInfo::setClusterNum (int _clusterNum) inline
Definition at line 4367 of file PlacementInfo.h.
Referenced by ClusterPlacer::clusterPlacementUnits().
setDeterminedOccupation()
void PlacementInfo::setDeterminedOccupation (int cellId, int occupation) inline
Set the Determined Occupation of a specific cell.
LUTFFDeterminedOccupation is used to record the final resource demand of a LUT/FF after final packing
Parameters
cellId target cell
occupation resource demand of the cell after packing
Definition at line 4101 of file PlacementInfo.h.
Referenced by ParallelCLBPacker::updatePackedMacro().
setMacroLegalizationParameters()
void PlacementInfo::setMacroLegalizationParameters (int cnt, float _macroLegalizationWeight) inline
Set the Macro Legalization Parameters.
We have specific pseudo net parameters for macro legalizations. We need to set them if loading a check point or re-configuring the placement.
Parameters
cnt MacroPseudoNetEnhanceCnt
_macroLegalizationWeight MacroPseudoNetEnhanceCnt
Definition at line 4064 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
setMinHPWL()
void PlacementInfo::setMinHPWL (float val) inline
record the minimum HPWL during placement procedure
Parameters
val
Definition at line 4194 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
setPaintDataBase()
void PlacementInfo::setPaintDataBase (PaintDataBase * _paintData) inline
Definition at line 4412 of file PlacementInfo.h.
Referenced by AMFPlacer::run().
setProgress()
void PlacementInfo::setProgress (float p) inline
Set the progress ratio, indicating the progress of the placement convergence,.
the progress ratio is usually HPWL_lower / HPWL_upper
Parameters
p
Definition at line 3948 of file PlacementInfo.h.
Referenced by loadPlacementUnitInformation(), and GlobalPlacer::updatePseudoNetWeight().
setPseudoNetWeight()
void PlacementInfo::setPseudoNetWeight (float weight) inline
Set the Pseudo Net Weight according to a given value.
This pseudo net weight will be used in the global placement iteration
Parameters
weight
Definition at line 4003 of file PlacementInfo.h.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
setPULegalSite()
void PlacementInfo::setPULegalSite (std::map< PlacementInfo::PlacementUnit *, std::vector< DeviceInfo::DeviceSite * >> & PU2Sites) inline
set the sites occupied by the PlacementUnit objects
Parameters
PU2Sites a mapping from PlaceuementUnit objects to device sites
Definition at line 3657 of file PlacementInfo.h.
Referenced by CLBLegalizer::finalLegalizeBasedOnDP(), MacroLegalizer::finalLegalizeBasedOnDP(), and ParallelCLBPacker::updatePackedMacro().
setPULegalXY()
void PlacementInfo::setPULegalXY (std::map< PlacementInfo::PlacementUnit *, float > & PU2X, std::map< PlacementInfo::PlacementUnit *, float > & PU2Y) inline
set the legalization of some PlacementUnit objects
Parameters
PU2X X of PlacementUnits
PU2Y Y of PlacementUnits
Definition at line 3637 of file PlacementInfo.h.
Referenced by CLBLegalizer::finalLegalizeBasedOnDP(), MacroLegalizer::finalLegalizeBasedOnDP(), ParallelCLBPacker::updatePackedMacro(), CLBLegalizer::updatePUMatchingLocation(), and MacroLegalizer::updatePUMatchingLocation().
transferCellBinInfo()
void PlacementInfo::transferCellBinInfo (int cellId, float fX, int fY) inline
update the bin information of a design cell when it is moved to a new location
When a cell is moved to a new location, corresponding bins should be updated accordingly.
Parameters
cellId the Id of the design cell
fX the X coordinate the cell is moved to
fY the Y coordinate the cell is moved to
Definition at line 3740 of file PlacementInfo.h.
Referenced by GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocations(), and GeneralSpreader::updatePlacementUnitsWithSpreadedCellLocationsWorker().
updateB2BAndGetTotalHPWL()
double PlacementInfo::updateB2BAndGetTotalHPWL () inline
update the B2B net model for the placement and get the total HPWL of all the nets in the design
Returns
double
Definition at line 3902 of file PlacementInfo.h.
Referenced by ClusterPlacer::ClusterPlacement(), GlobalPlacer::clusterPlacement(), GlobalPlacer::GlobalPlacement_CLBElements(), GlobalPlacer::GlobalPlacement_fixedCLB(), ParallelCLBPacker::packCLBs(), AMFPlacer::run(), ParallelCLBPacker::setPULocationToPackedSite(), and ParallelCLBPacker::updatePackedMacro().
updateCells2PlacementUnits()
void PlacementInfo::updateCells2PlacementUnits ()
update the mapping from Cells to PlacementUnits, since sometime, PlacementUnits might change
Definition at line 1689 of file PlacementInfo.cc.
Referenced by IncrementalBELPacker::FFPairing(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::pack(), and ParallelCLBPacker::updatePackedMacro().
updateElementBinGrid()
void PlacementInfo::updateElementBinGrid ()
map design cells to the bins in the bin grid.
Definition at line 889 of file PlacementInfo.cc.
Referenced by PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), ParallelCLBPacker::exceptionHandling(), IncrementalBELPacker::FFPairing(), GlobalPlacer::GlobalPlacement_CLBElements(), GlobalPlacer::GlobalPlacement_fixedCLB(), loadPlacementUnitInformation(), IncrementalBELPacker::LUTFFPairing(), GlobalPlacer::macroLegalize(), ParallelCLBPacker::packCLBs(), ClusterPlacer::placeClusters(), ParallelCLBPacker::setPULocationToPackedSite(), GlobalPlacer::spreading(), PlacementTimingOptimizer::stretchClockRegionColumns(), and GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate().
updateLongPaths()
void PlacementInfo::updateLongPaths ()
update the long path in the design and enhance their net weights
Definition at line 617 of file PlacementInfo.cc.
updateSiteBinGrid()
void PlacementInfo::updateSiteBinGrid ()
Definition at line 1663 of file PlacementInfo.cc.
verifyDeviceForDesign()
void PlacementInfo::verifyDeviceForDesign ()
verify that each cells in the design can be mapped on the resource elements on the device.
Definition at line 773 of file PlacementInfo.cc.
Referenced by AMFPlacer::run().
Member Data Documentation
binHeight
float PlacementInfo::binHeight private
Definition at line 4509 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Routability(), createGridBins(), createSiteBinGrid(), getBinGridH(), and getGridXY().
binWidth
float PlacementInfo::binWidth private
Definition at line 4508 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Routability(), createGridBins(), createSiteBinGrid(), getBinGridW(), and getGridXY().
cellId2CellBinInfo
std::vector<CellBinInfo> PlacementInfo::cellId2CellBinInfo private
Definition at line 4427 of file PlacementInfo.h.
Referenced by findNeiborSiteFromBinGrid(), getCellId2CellBinInfo(), setCellBinInfo(), transferCellBinInfo(), and updateCells2PlacementUnits().
cellId2location
std::vector<Location> PlacementInfo::cellId2location private
Definition at line 4428 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity(), checkClockUtilization(), dumpOverflowClockUtilization(), findNeiborLUTFFsFromBinGrid(), getCellId2location(), and updateElementBinGrid().
cellId2PlacementUnit
std::map<int, PlacementUnit *> PlacementInfo::cellId2PlacementUnit private
Definition at line 4425 of file PlacementInfo.h.
Referenced by getCellId2PlacementUnit(), getPULocationByCellLocation(), isLegalLocation(), loadPlacementUnitInformation(), PlacementInfo(), reloadNets(), and updateCells2PlacementUnits().
cellId2PlacementUnitVec
std::vector<PlacementUnit *> PlacementInfo::cellId2PlacementUnitVec private
Definition at line 4426 of file PlacementInfo.h.
Referenced by getCellId2PlacementUnitVec(), getPlacementUnitByCell(), getPlacementUnitByCellId(), loadPlacementUnitInformation(), PlacementInfo::PlacementNet::PlacementNet(), reloadNets(), and updateCells2PlacementUnits().
cellInMacros
std::set<DesignInfo::DesignCell *> PlacementInfo::cellInMacros private
Definition at line 4424 of file PlacementInfo.h.
Referenced by getCellInMacros(), loadPlacementUnitInformation(), PlacementInfo(), printStat(), and updateCells2PlacementUnits().
cellType2fixedAmoFileName
std::string PlacementInfo::cellType2fixedAmoFileName private
Definition at line 4573 of file PlacementInfo.h.
Referenced by PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), loadCompatiblePlacementTable(), and PlacementInfo().
cellType2sharedCellTypeFileName
std::string PlacementInfo::cellType2sharedCellTypeFileName private
Definition at line 4574 of file PlacementInfo.h.
Referenced by PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), loadCompatiblePlacementTable(), and PlacementInfo().
clockCol2ClockNets
std::map<DeviceInfo::ClockColumn *, std::set<DesignInfo::DesignNet *> > PlacementInfo::clockCol2ClockNets private
Definition at line 4524 of file PlacementInfo.h.
Referenced by addPUIntoClockColumn(), checkClockColumnLegalization(), dumpOverflowClockUtilization(), getClockCol2ClockNets(), getClockColumnUtilizationIncrease(), PlacementInfo(), and printOutClockColumnLegalization().
clockLegalizationRisky
bool PlacementInfo::clockLegalizationRisky = false private
Definition at line 4600 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), and isClockLegalizationRisky().
clockNetCoverages
std::vector<ClockNetCoverage> PlacementInfo::clockNetCoverages private
Definition at line 4563 of file PlacementInfo.h.
Referenced by checkClockUtilization().
clockNets
std::vector<PlacementNet *> PlacementInfo::clockNets private
Definition at line 4515 of file PlacementInfo.h.
Referenced by checkClockUtilization(), dumpOverflowClockUtilization(), enhanceRiskyClockNet(), and reloadNets().
clockRegionUtilization
std::vector<std::vector<int> > PlacementInfo::clockRegionUtilization private
Definition at line 4516 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), checkClockUtilization(), and enhanceRiskyClockNet().
clusterNum
int PlacementInfo::clusterNum = 1 private
Definition at line 4599 of file PlacementInfo.h.
Referenced by getClusterNum(), and setClusterNum().
compatiblePlacementTable
CompatiblePlacementTable* PlacementInfo::compatiblePlacementTable = nullptr private
Definition at line 4419 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementBinInfo::addSiteIntoBin(), adjustLUTFFUtilization(), adjustLUTFFUtilization_Clocking(), adjustLUTFFUtilization_Packablity(), adjustLUTFFUtilization_Routability(), adjustLUTFFUtilization_Routability_Reset(), createGridBins(), getActualOccupation(), getActualOccupationByCellId(), getcellId2Occupation(), getCompatiblePlacementTable(), getInflateRatio(), getOccupation(), getPotentialBELTypeIDs(), getSharedBELTypeId(), PlacementInfo(), setBELTypeForCells(), verifyDeviceForDesign(), and ~PlacementInfo().
designInfo
DesignInfo* PlacementInfo::designInfo private
Definition at line 4430 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementMacro::addVirtualCell(), getCells(), getDesignInfo(), getDeterminedOccupation(), getNumCells(), loadCompatiblePlacementTable(), PlacementInfo(), printStat(), reloadNets(), resetLUTFFDeterminedOccupation(), PlacementInfo::CompatiblePlacementTable::setBELTypeForCells(), setBELTypeForCells(), setDeterminedOccupation(), transferCellBinInfo(), updateCells2PlacementUnits(), updateElementBinGrid(), and verifyDeviceForDesign().
designNetId2PlacementNet
std::vector<PlacementNet *> PlacementInfo::designNetId2PlacementNet private
Definition at line 4513 of file PlacementInfo.h.
Referenced by getPlacementNetByDesignNetId(), and reloadNets().
deviceInfo
DeviceInfo* PlacementInfo::deviceInfo private
Definition at line 4431 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Clocking(), checkClockUtilization(), createGridBins(), createSiteBinGrid(), dumpOverflowClockUtilization(), enhanceRiskyClockNet(), getBELType2FalseBELType(), getDeviceInfo(), loadCompatiblePlacementTable(), loadPlacementUnitInformation(), PlacementInfo(), PlacementInfo::CompatiblePlacementTable::setBELTypeForCells(), and PlacementInfo::PlacementUnpackedCell::setLockedAt().
dumpPlacementUnitLocationCnt
int PlacementInfo::dumpPlacementUnitLocationCnt = 0 private
Definition at line 4597 of file PlacementInfo.h.
Referenced by dumpPlacementUnitInformation(), and dumpVivadoPlacementTclWithPULegalizationInfo().
endX
float PlacementInfo::endX private
right boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 4484 of file PlacementInfo.h.
Referenced by createGridBins(), createSiteBinGrid(), getDeviceMaxEdgeLength(), and getGlobalBinMaxLocX().
endY
float PlacementInfo::endY private
bottom boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 4491 of file PlacementInfo.h.
Referenced by createGridBins(), createSiteBinGrid(), getDeviceMaxEdgeLength(), and getGlobalBinMaxLocY().
eps
float PlacementInfo::eps = 1e-5 private
Definition at line 4493 of file PlacementInfo.h.
Referenced by addB2BNetInPlacementInfo(), adjustLUTFFUtilization_Routability(), createGridBins(), createSiteBinGrid(), enforceLegalizeXYInArea(), getPULocationByCellLocation(), isLegalLocation(), and legalizeXYInArea().
fixedPlacementUnits
std::vector<PlacementUnit *> PlacementInfo::fixedPlacementUnits private
Definition at line 4423 of file PlacementInfo.h.
Referenced by getFixedPlacementUnits(), and loadPlacementUnitInformation().
globalBinGrid
std::vector<std::vector<PlacementBinInfo *> > PlacementInfo::globalBinGrid private
Bin Grid includes all types of sites, mainly for congestion evalution.
Definition at line 4506 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Routability(), createGridBins(), dumpCongestion(), getGlobalBinGrid(), and updateElementBinGrid().
globalMaxX
float PlacementInfo::globalMaxX private
right boundary of the device
Definition at line 4458 of file PlacementInfo.h.
Referenced by createGridBins(), enforceLegalizeXYInArea(), getGlobalMaxX(), getPULocationByCellLocation(), isLegalLocation(), legalizeXYInArea(), PlacementInfo(), and printStat().
globalMaxY
float PlacementInfo::globalMaxY private
top boundary of the device
Definition at line 4463 of file PlacementInfo.h.
Referenced by createGridBins(), enforceLegalizeXYInArea(), getGlobalMaxY(), getPULocationByCellLocation(), isLegalLocation(), legalizeXYInArea(), PlacementInfo(), and printStat().
globalMinX
float PlacementInfo::globalMinX private
left boundary of the device
Definition at line 4448 of file PlacementInfo.h.
Referenced by createGridBins(), enforceLegalizeXYInArea(), getGlobalMinX(), getPULocationByCellLocation(), isLegalLocation(), legalizeXYInArea(), PlacementInfo(), and printStat().
globalMinY
float PlacementInfo::globalMinY private
bottom boundary of the device
Definition at line 4453 of file PlacementInfo.h.
Referenced by createGridBins(), enforceLegalizeXYInArea(), getGlobalMinY(), getPULocationByCellLocation(), isLegalLocation(), legalizeXYInArea(), PlacementInfo(), and printStat().
highFanOutThr
int PlacementInfo::highFanOutThr = 10000000 private
Definition at line 4611 of file PlacementInfo.h.
Referenced by enhanceHighFanoutNet(), getHighFanOutThr(), and reloadNets().
JSONCfg
std::map<std::string, std::string>& PlacementInfo::JSONCfg private
Definition at line 4572 of file PlacementInfo.h.
Referenced by getMacroPseudoNetEnhanceCnt(), and PlacementInfo().
lastProgressWhenLUTFFUtilAdjust
float PlacementInfo::lastProgressWhenLUTFFUtilAdjust = -1.0 private
Definition at line 4606 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity().
longPaths
std::vector<std::vector<PlacementUnit *> > PlacementInfo::longPaths private
Definition at line 4520 of file PlacementInfo.h.
Referenced by getLongPaths(), optimizeLongPaths(), and updateLongPaths().
longPathThresholdLevel
int PlacementInfo::longPathThresholdLevel = 10 private
the long path threshold for timing optimization
Definition at line 4589 of file PlacementInfo.h.
Referenced by buildSimpleTimingGraph(), and getLongPathThresholdLevel().
LUTFFBinGrid
std::vector<std::vector<PlacementBinInfo *> > PlacementInfo::LUTFFBinGrid private
Bin Grid for LUTs and FFs, mainly for searching neighbor elements during packing.
Definition at line 4500 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity(), createGridBins(), and findNeiborLUTFFsFromBinGrid().
LUTFFUtilizationAdjusted
bool PlacementInfo::LUTFFUtilizationAdjusted = false private
Definition at line 4609 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization(), adjustLUTFFUtilization_Packablity(), and loadPlacementUnitInformation().
macroLegalizationWeight
float PlacementInfo::macroLegalizationWeight = -1 private
Definition at line 4604 of file PlacementInfo.h.
Referenced by getMacroLegalizationWeight(), loadPlacementUnitInformation(), and setMacroLegalizationParameters().
macroPseudoNetEnhanceCnt
int PlacementInfo::macroPseudoNetEnhanceCnt = -1 private
Definition at line 4603 of file PlacementInfo.h.
Referenced by getMacroPseudoNetEnhanceCnt(), loadPlacementUnitInformation(), and setMacroLegalizationParameters().
macroRatio
float PlacementInfo::macroRatio = 0.0 private
Definition at line 4613 of file PlacementInfo.h.
Referenced by getMacroRatio(), and updateCells2PlacementUnits().
mediumPathThresholdLevel
int PlacementInfo::mediumPathThresholdLevel = 5 private
the medium path threshold for timing optimization
Definition at line 4595 of file PlacementInfo.h.
Referenced by buildSimpleTimingGraph(), and getMediumPathThresholdLevel().
minHPWL
float PlacementInfo::minHPWL = 1e8 private
Definition at line 4608 of file PlacementInfo.h.
Referenced by getMinHPWL(), and setMinHPWL().
netDistribution
int PlacementInfo::netDistribution[8] = {0, 0, 0, 0, 0, 0, 0, 0} private
Definition at line 4577 of file PlacementInfo.h.
Referenced by getNetDistributionByDensity(), and reloadNets().
netPinNumDistribution
int PlacementInfo::netPinNumDistribution[8] = {8, 16, 24, 32, 64, 256, 512, 1000000} private
Definition at line 4576 of file PlacementInfo.h.
Referenced by getNetDistributionByDensity(), and reloadNets().
oriPseudoNetWeight
float PlacementInfo::oriPseudoNetWeight = -1 private
Definition at line 4602 of file PlacementInfo.h.
Referenced by getPseudoNetWeight(), loadPlacementUnitInformation(), and setPseudoNetWeight().
paintData
PaintDataBase* PlacementInfo::paintData = nullptr private
Definition at line 4525 of file PlacementInfo.h.
Referenced by setPaintDataBase(), and updateElementBinGrid().
PaintTypes
std::vector<int> PlacementInfo::PaintTypes private
Definition at line 4529 of file PlacementInfo.h.
Referenced by updateElementBinGrid().
PaintXs
std::vector<float> PlacementInfo::PaintXs private
Definition at line 4527 of file PlacementInfo.h.
Referenced by updateElementBinGrid().
PaintYs
std::vector<float> PlacementInfo::PaintYs private
Definition at line 4528 of file PlacementInfo.h.
Referenced by updateElementBinGrid().
pinId2location
std::vector<Location> PlacementInfo::pinId2location private
Definition at line 4429 of file PlacementInfo.h.
Referenced by getPinId2location().
placementMacros
std::vector<PlacementMacro *> PlacementInfo::placementMacros private
Definition at line 4422 of file PlacementInfo.h.
Referenced by getPlacementMacros(), loadPlacementUnitInformation(), and PlacementInfo().
placementNets
std::vector<PlacementNet *> PlacementInfo::placementNets private
Definition at line 4511 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Routability(), enhanceDDRNet(), enhanceHighFanoutNet(), getPlacementNets(), getTotalHPWL(), PlacementInfo(), reloadNets(), updateB2BAndGetTotalHPWL(), and ~PlacementInfo().
placementProressRatio
float PlacementInfo::placementProressRatio = 0.01 private
the progress ratio, indicating the progress of the placement convergence.
the progress ratio is usually HPWL_lower / HPWL_upper
Definition at line 4570 of file PlacementInfo.h.
Referenced by getProgress(), and setProgress().
placementUnitId2Nets
std::vector<std::vector<PlacementNet *> > PlacementInfo::placementUnitId2Nets private
Definition at line 4512 of file PlacementInfo.h.
Referenced by getPlacementUnitId2Nets(), and reloadNets().
placementUnits
std::vector<PlacementUnit *> PlacementInfo::placementUnits private
Definition at line 4420 of file PlacementInfo.h.
Referenced by adjustLUTFFUtilization_Packablity(), calculateNetNumDistributionOfPUs(), getPlacementUnits(), loadPlacementUnitInformation(), PlacementInfo(), printStat(), reloadNets(), and updateElementBinGrid().
placementUnpackedCells
std::vector<PlacementUnpackedCell *> PlacementInfo::placementUnpackedCells private
Definition at line 4421 of file PlacementInfo.h.
Referenced by getPlacementUnpackedCells(), loadPlacementUnitInformation(), and PlacementInfo().
PU2ClockRegionCenters
std::map<PlacementUnit *, std::pair<float, float> > PlacementInfo::PU2ClockRegionCenters private
Definition at line 4522 of file PlacementInfo.h.
Referenced by getPU2ClockRegionCenters().
PU2ClockRegionColumn
std::map<PlacementUnit *, int> PlacementInfo::PU2ClockRegionColumn private
Definition at line 4523 of file PlacementInfo.h.
Referenced by findNeiborSiteFromBinGrid(), and getPU2ClockRegionColumn().
PU2LegalSites
std::map<PlacementInfo::PlacementUnit *, std::vector<DeviceInfo::DeviceSite *> > PlacementInfo::PU2LegalSites private
a mapping from PlaceuementUnit objects to device sites
Definition at line 4443 of file PlacementInfo.h.
Referenced by deleteLegalizationInfoFor(), dumpPlacementUnitInformation(), getPULegalSite(), loadPlacementUnitInformation(), resetPULegalInformation(), and setPULegalSite().
PULegalXY
std::pair<std::map<PlacementInfo::PlacementUnit *, float>, std::map<PlacementInfo::PlacementUnit *, float> > PlacementInfo::PULegalXY private
a mapping from PlaceuementUnit objects to legalized locations
Definition at line 4438 of file PlacementInfo.h.
Referenced by deleteLegalizationInfoFor(), getPULegalXY(), loadPlacementUnitInformation(), resetPULegalInformation(), and setPULegalXY().
PUsContainingFF
std::vector<PlacementUnit *> PlacementInfo::PUsContainingFF private
Definition at line 4519 of file PlacementInfo.h.
Referenced by reloadNets(), and updateLongPaths().
PUSetContainingFF
std::set<PlacementUnit *> PlacementInfo::PUSetContainingFF private
Definition at line 4518 of file PlacementInfo.h.
Referenced by reloadNets().
PUWithManyNetsRatio
float PlacementInfo::PUWithManyNetsRatio = -1 private
Definition at line 4607 of file PlacementInfo.h.
Referenced by calculateNetNumDistributionOfPUs(), and getPUWithManyNetsRatio().
SharedBELTypeBinGrid
std::vector<std::vector<std::vector<PlacementBinInfo *> > > PlacementInfo::SharedBELTypeBinGrid private
Definition at line 4494 of file PlacementInfo.h.
Referenced by createGridBins(), findNeiborSiteFromBinGrid(), getBinGrid(), resetElementBinGrid(), transferCellBinInfo(), and ~PlacementInfo().
sharedCellType2BELtypeFileName
std::string PlacementInfo::sharedCellType2BELtypeFileName private
Definition at line 4575 of file PlacementInfo.h.
Referenced by PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), loadCompatiblePlacementTable(), and PlacementInfo().
simplePlacementTimingInfo
PlacementTimingInfo* PlacementInfo::simplePlacementTimingInfo = nullptr private
Definition at line 4432 of file PlacementInfo.h.
Referenced by buildSimpleTimingGraph(), getTimingInfo(), PlacementInfo(), and reloadNets().
siteGridForMacros
std::vector<std::vector<PlacementSiteBinInfo *> > PlacementInfo::siteGridForMacros private
Definition at line 4507 of file PlacementInfo.h.
Referenced by createSiteBinGrid(), getSiteBinGrid(), resetSiteBinGrid(), and ~PlacementInfo().
startX
float PlacementInfo::startX private
left boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 4470 of file PlacementInfo.h.
Referenced by createGridBins(), createSiteBinGrid(), getDeviceMaxEdgeLength(), getGlobalBinMinLocX(), and getGridXY().
startY
float PlacementInfo::startY private
bottom boundary of the bin grid
the coverage of bin grid is a bit larger than the device.
Definition at line 4477 of file PlacementInfo.h.
Referenced by createGridBins(), createSiteBinGrid(), getDeviceMaxEdgeLength(), getGlobalBinMinLocY(), and getGridXY().
y2xRatio
float PlacementInfo::y2xRatio = 1.0 private
a factor to tune the weights of the net spanning in Y-coordinate relative to the net spanning in X-coordinate
Definition at line 4583 of file PlacementInfo.h.
Referenced by PlacementInfo::PlacementNet::addPseudoNet_enhancePin2Pin(), addPseudoNetsInPlacementInfo(), adjustLUTFFUtilization_Routability(), findNeiborLUTFFsFromBinGrid(), getDisplacement(), PlacementInfo::PlacementNet::getHPWL(), PlacementInfo::PlacementNet::getNewHPWLByTrying(), getTotalHPWL(), PlacementInfo(), updateB2BAndGetTotalHPWL(), and PlacementInfo::PlacementNet::updateBound2BoundNetWeight().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.h
src/lib/HiFPlacer/placement/placementInfo/PlacementInfo.cc