AMF-Placer: DeviceInfo::DeviceSite Class Reference
DeviceInfo::DeviceSite Class Reference
Site class for site on device.
#include <DeviceInfo.h>
Classes
class DeviceSitePinInfos
a class record the pin on the site boundary
Public Member Functions
DeviceSite (std::string &name, std::string &siteType, DeviceElement *parentPtr, float locX, float locY, int clockRegionX, int clockRegionY, int id)
Construct a new Device Site object.
~DeviceSite ()
void setTile (DeviceElement *parentTilePtr)
DeviceTile * getTile ()
void setParentSite (DeviceElement *parentSitePtr)
Set the Parent Site object.
DeviceSite * getParentSite ()
void addChildSite (DeviceElement *parentSitePtr)
Set the Parent Site object.
std::vector< DeviceSite * > & getChildrenSites ()
void setSiteLocation (float x, float y)
std::string & getSiteType ()
void addChildBEL (DeviceBEL *child)
std::vector< DeviceBEL * > & getChildrenBELs ()
float X ()
float Y ()
DeviceSitePinInfos * getSitePinInfos ()
void setSitePinInfos (DeviceSitePinInfos *_sitePins)
bool isOccupied ()
check whether this site is occupied by fixed element
void setOccupied ()
bool isMapped ()
check whether this site is mapped to an design element (might be movable elements)
void setMapped ()
void resetMapped ()
int getSiteY ()
int getSiteX ()
int getClockRegionX ()
int getClockRegionY ()
void setClockRegion (ClockRegion *_clockRegion)
ClockRegion * getClockRegion ()
void setClockHalfColumn (ClockColumn *_clockHalfColumn)
ClockColumn * getClockHalfColumn ()
Public Member Functions inherited from DeviceInfo::DeviceElement
DeviceElement (std::string &name, DeviceElement *parentPtr, DeviceElementType type, int id)
DeviceElement (std::string &name, DeviceElementType type, int id)
virtual ~DeviceElement ()
std::string & getName ()
DeviceElement * getParentPtr ()
DeviceElementType getElementType ()
int getElementIdInParent ()
Private Attributes
std::string siteType
ClockRegion * clockRegion = nullptr
ClockColumn * clockHalfColumn = nullptr
std::vector< DeviceBEL * > childrenBELs
DeviceSite * parentSite
std::vector< DeviceSite * > childrenSites
DeviceTile * parentTile = nullptr
DeviceSitePinInfos * sitePins = nullptr
float locX
float locY
int clockRegionX = -1
int clockRegionY = -1
int siteY
int siteX
bool occupied = false
a flag that this site is occupied by fixed element
bool mapped = false
a flag that this site is mapped to an design element (might be movable elements)
Detailed Description
Site class for site on device.
A site contains a combination of BEL. This class record the name/type/location/clockRegion of the site
Definition at line 150 of file DeviceInfo.h.
Constructor & Destructor Documentation
DeviceSite()
DeviceInfo::DeviceSite::DeviceSite (std::string & name, std::string & siteType, DeviceElement * parentPtr, float locX, float locY, int clockRegionX, int clockRegionY, int id) inline
Construct a new Device Site object.
Parameters
name the name of the site
siteType a string for the type of the site
parentPtr the tile that contains this site
locX
locY
clockRegionX
clockRegionY
id
Definition at line 165 of file DeviceInfo.h.
~DeviceSite()
DeviceInfo::DeviceSite::~DeviceSite () inline
Definition at line 195 of file DeviceInfo.h.
Member Function Documentation
addChildBEL()
void DeviceInfo::DeviceSite::addChildBEL (DeviceBEL * child) inline
Definition at line 266 of file DeviceInfo.h.
Referenced by DeviceInfo::addBEL().
addChildSite()
void DeviceInfo::DeviceSite::addChildSite (DeviceElement * parentSitePtr)
Set the Parent Site object.
it seems that some sites on FPGA might contain children site?
Parameters
parentSitePtr
Definition at line 443 of file DeviceInfo.cc.
getChildrenBELs()
std::vector<DeviceBEL *>& DeviceInfo::DeviceSite::getChildrenBELs () inline
Definition at line 271 of file DeviceInfo.h.
getChildrenSites()
std::vector<DeviceSite *>& DeviceInfo::DeviceSite::getChildrenSites () inline
Definition at line 250 of file DeviceInfo.h.
Referenced by DeviceInfo::addBEL().
getClockHalfColumn()
ClockColumn* DeviceInfo::DeviceSite::getClockHalfColumn () inline
Definition at line 365 of file DeviceInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPUFailReason(), PlacementInfo::addPUIntoClockColumn(), PlacementInfo::checkClockColumnLegalization(), PlacementInfo::getClockColumnUtilizationIncrease(), and PlacementInfo::printOutClockColumnLegalization().
getClockRegion()
ClockRegion* DeviceInfo::DeviceSite::getClockRegion () inline
Definition at line 355 of file DeviceInfo.h.
getClockRegionX()
int DeviceInfo::DeviceSite::getClockRegionX () inline
Definition at line 340 of file DeviceInfo.h.
Referenced by PlacementInfo::PlacementBinInfo::addSiteIntoBin(), and DeviceInfo::ClockRegion::ClockRegion().
getClockRegionY()
int DeviceInfo::DeviceSite::getClockRegionY () inline
Definition at line 345 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::ClockRegion().
getParentSite()
DeviceSite* DeviceInfo::DeviceSite::getParentSite () inline
Definition at line 237 of file DeviceInfo.h.
getSitePinInfos()
DeviceSitePinInfos* DeviceInfo::DeviceSite::getSitePinInfos () inline
Definition at line 285 of file DeviceInfo.h.
getSiteType()
std::string& DeviceInfo::DeviceSite::getSiteType () inline
Definition at line 261 of file DeviceInfo.h.
Referenced by ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::addPU().
getSiteX()
int DeviceInfo::DeviceSite::getSiteX () inline
Definition at line 334 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::mapSiteToClockColumns().
getSiteY()
int DeviceInfo::DeviceSite::getSiteY () inline
Definition at line 328 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::mapSiteToClockColumns().
getTile()
DeviceTile* DeviceInfo::DeviceSite::getTile () inline
Definition at line 223 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::addSite(), and DeviceInfo::ClockRegion::ClockRegion().
isMapped()
bool DeviceInfo::DeviceSite::isMapped () inline
check whether this site is mapped to an design element (might be movable elements)
Returns
true
false
Definition at line 315 of file DeviceInfo.h.
isOccupied()
bool DeviceInfo::DeviceSite::isOccupied () inline
check whether this site is occupied by fixed element
Returns
true
false
Definition at line 300 of file DeviceInfo.h.
resetMapped()
void DeviceInfo::DeviceSite::resetMapped () inline
Definition at line 323 of file DeviceInfo.h.
setClockHalfColumn()
void DeviceInfo::DeviceSite::setClockHalfColumn (ClockColumn * _clockHalfColumn) inline
Definition at line 360 of file DeviceInfo.h.
setClockRegion()
void DeviceInfo::DeviceSite::setClockRegion (ClockRegion * _clockRegion) inline
Definition at line 350 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockRegion::addSite(), and DeviceInfo::ClockRegion::ClockRegion().
setMapped()
void DeviceInfo::DeviceSite::setMapped () inline
Definition at line 319 of file DeviceInfo.h.
Referenced by PlacementInfo::loadPlacementUnitInformation().
setOccupied()
void DeviceInfo::DeviceSite::setOccupied () inline
Definition at line 304 of file DeviceInfo.h.
Referenced by InitialPacker::loadFixedPlacementUnits(), and PlacementInfo::PlacementUnpackedCell::setLockedAt().
setParentSite()
void DeviceInfo::DeviceSite::setParentSite (DeviceElement * parentSitePtr)
Set the Parent Site object.
it seems that some sites on FPGA might contain children site?
Parameters
parentSitePtr
Definition at line 439 of file DeviceInfo.cc.
setSiteLocation()
void DeviceInfo::DeviceSite::setSiteLocation (float x, float y) inline
Definition at line 255 of file DeviceInfo.h.
setSitePinInfos()
void DeviceInfo::DeviceSite::setSitePinInfos (DeviceSitePinInfos * _sitePins) inline
Definition at line 289 of file DeviceInfo.h.
setTile()
void DeviceInfo::DeviceSite::setTile (DeviceElement * parentTilePtr)
Definition at line 432 of file DeviceInfo.cc.
X()
float DeviceInfo::DeviceSite::X () inline
Definition at line 276 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockColumn::addSite(), DeviceInfo::ClockRegion::addSite(), PlacementInfo::PlacementBinInfo::addSiteIntoBin(), PlacementInfo::PlacementSiteBinInfo::addSiteIntoBin(), DeviceInfo::ClockRegion::ClockRegion(), CLBLegalizer::getDisplacement(), MacroLegalizer::getDisplacement(), PlacementInfo::getDisplacement(), CLBLegalizer::getHPWLChange(), MacroLegalizer::getHPWLChange(), InitialPacker::loadFixedPlacementUnits(), operator<<(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself(), ParallelCLBPacker::ripUpAndLegalizae(), siteSortCmp(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ParallelCLBPacker::PackingCLBSite::updateStep().
Y()
float DeviceInfo::DeviceSite::Y () inline
Definition at line 280 of file DeviceInfo.h.
Referenced by DeviceInfo::ClockColumn::addSite(), DeviceInfo::ClockRegion::addSite(), PlacementInfo::PlacementBinInfo::addSiteIntoBin(), PlacementInfo::PlacementSiteBinInfo::addSiteIntoBin(), DeviceInfo::ClockRegion::ClockRegion(), CLBLegalizer::getDisplacement(), MacroLegalizer::getDisplacement(), PlacementInfo::getDisplacement(), CLBLegalizer::getHPWLChange(), MacroLegalizer::getHPWLChange(), InitialPacker::loadFixedPlacementUnits(), operator<<(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster::printMyself(), ParallelCLBPacker::ripUpAndLegalizae(), siteSortCmp(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), and ParallelCLBPacker::PackingCLBSite::updateStep().
Member Data Documentation
childrenBELs
std::vector<DeviceBEL *> DeviceInfo::DeviceSite::childrenBELs private
Definition at line 374 of file DeviceInfo.h.
childrenSites
std::vector<DeviceSite *> DeviceInfo::DeviceSite::childrenSites private
Definition at line 376 of file DeviceInfo.h.
clockHalfColumn
ClockColumn* DeviceInfo::DeviceSite::clockHalfColumn = nullptr private
Definition at line 373 of file DeviceInfo.h.
clockRegion
ClockRegion* DeviceInfo::DeviceSite::clockRegion = nullptr private
Definition at line 372 of file DeviceInfo.h.
clockRegionX
int DeviceInfo::DeviceSite::clockRegionX = -1 private
Definition at line 381 of file DeviceInfo.h.
clockRegionY
int DeviceInfo::DeviceSite::clockRegionY = -1 private
Definition at line 382 of file DeviceInfo.h.
locX
float DeviceInfo::DeviceSite::locX private
Definition at line 379 of file DeviceInfo.h.
locY
float DeviceInfo::DeviceSite::locY private
Definition at line 380 of file DeviceInfo.h.
mapped
bool DeviceInfo::DeviceSite::mapped = false private
a flag that this site is mapped to an design element (might be movable elements)
Definition at line 396 of file DeviceInfo.h.
occupied
bool DeviceInfo::DeviceSite::occupied = false private
a flag that this site is occupied by fixed element
Definition at line 390 of file DeviceInfo.h.
parentSite
DeviceSite* DeviceInfo::DeviceSite::parentSite private
Definition at line 375 of file DeviceInfo.h.
parentTile
DeviceTile* DeviceInfo::DeviceSite::parentTile = nullptr private
Definition at line 377 of file DeviceInfo.h.
sitePins
DeviceSitePinInfos* DeviceInfo::DeviceSite::sitePins = nullptr private
Definition at line 378 of file DeviceInfo.h.
siteType
std::string DeviceInfo::DeviceSite::siteType private
Definition at line 371 of file DeviceInfo.h.
siteX
int DeviceInfo::DeviceSite::siteX private
Definition at line 384 of file DeviceInfo.h.
siteY
int DeviceInfo::DeviceSite::siteY private
Definition at line 383 of file DeviceInfo.h.
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/deviceInfo/DeviceInfo.h
src/lib/HiFPlacer/deviceInfo/DeviceInfo.cc