AMF-Placer: DesignInfo::DesignPin Class Reference
DesignInfo::DesignPin Class Reference
A design pin on a design cell connected to a net.
#include <DesignInfo.h>
Public Member Functions
DesignPin (std::string &name, std::string &refpinname, DesignPinType pinType, bool inputOrNot, DesignElement *parentPtr, int id)
Construct a new Design Pin object.
~DesignPin ()
DesignPinType getPinType ()
Get the Pin Type of the pin.
std::string & getNetName ()
Get the name of the net which the pin connects to.
void connectToNetName (std::string &_netName)
bind the pin to the net by the net name
void connectToNetVariable (DesignNet *_netPtr)
bind the pin to the net's pointer for later processing
bool isOutputPort ()
bool isInputPort ()
void setDriverPinName (std::string &_driverPinName)
Set the driver Pin Name of the pin.
void setDriverPin (DesignPin *_driverPinPtr)
Set the Driver Pin object.
DesignPin * getDriverPin ()
Get the driver pin of the pin (nullptr indicates that the pin connects to some global signal like VGG/GND)
void updateParentCellNetInfo ()
let the parent cell know that one of its pin connects to a specific net
DesignNet * getNet ()
DesignCell * getCell ()
Get the Cell object of the pin.
std::string & getRefPinName ()
Get the reference pin name of the pin.
void setUnconnected ()
Set the attribute unconnected to be true, indicating the pin connect to no net.
bool isUnconnected ()
check if the attribute unconnected is true
void setOffsetInCell (float x, float y)
Set the Offset of the pin relative to the cell.
float getOffsetXInCell ()
Get the offset X of the pin In the cell.
float getOffsetYInCell ()
Get the offset Y of the pin In the cell.
Public Member Functions inherited from DesignInfo::DesignElement
DesignElement (const std::string &name, DesignElement *parentPtr, DesignElementType type, int id)
DesignElement (const std::string &name, DesignElementType type, int id)
DesignElement (bool isVirtual, DesignElementType type, int id)
DesignElement (bool isVirtual, const std::string &_name, DesignElementType type, int id)
virtual ~DesignElement ()
const std::string & getName () const
DesignElement * getParentPtr ()
DesignElementType getElementType ()
int getElementIdInType ()
Static Public Member Functions
static DesignPinType checkPinType (DesignCell *cell, std::string &refpinname, bool isInput)
get the pin type based on its reference name
Private Attributes
DesignPinType pinType
pin type could be:
std::string netName
std::string refpinname
DesignNet * netPtr = nullptr
bool inputOrNot
bool unconnected = false
std::string driverPinName
DesignPin * driverPin = nullptr
float offsetXInCell = 0.0
float offsetYInCell = 0.0
Detailed Description
A design pin on a design cell connected to a net.
Definition at line 262 of file DesignInfo.h.
Constructor & Destructor Documentation
DesignPin()
DesignInfo::DesignPin::DesignPin (std::string & name, std::string & refpinname, DesignPinType pinType, bool inputOrNot, DesignElement * parentPtr, int id) inline
Construct a new Design Pin object.
Parameters
name the actual/unique name of design pin
refpinname the reference name of the pin on the cell, indicating which device pin shoud be used on the device BEL
pinType some pins can be classified into specific type (clk, reset...)
inputOrNot
parentPtr the cell of the pin
id the id of the pin in the pin list
Definition at line 276 of file DesignInfo.h.
~DesignPin()
DesignInfo::DesignPin::~DesignPin () inline
Definition at line 283 of file DesignInfo.h.
Member Function Documentation
checkPinType()
DesignInfo::DesignPinType DesignInfo::DesignPin::checkPinType (DesignCell * cell, std::string & refpinname, bool isInput) static
get the pin type based on its reference name
Parameters
cell the cell of the pin
refpinname the reference name of the pin on the cell, indicating which device pin shoud be used on the device BEL
isInput
Returns
DesignPinType
Definition at line 25 of file DesignInfo.cc.
Referenced by DesignInfo::DesignInfo().
connectToNetName()
void DesignInfo::DesignPin::connectToNetName (std::string & _netName) inline
bind the pin to the net by the net name
Parameters
_netName
Definition at line 323 of file DesignInfo.h.
Referenced by DesignInfo::DesignInfo().
connectToNetVariable()
void DesignInfo::DesignPin::connectToNetVariable (DesignNet * _netPtr) inline
bind the pin to the net's pointer for later processing
Parameters
_netPtr
Definition at line 333 of file DesignInfo.h.
Referenced by DesignInfo::DesignInfo().
getCell()
DesignCell * DesignInfo::DesignPin::getCell () inline
Get the Cell object of the pin.
Returns
DesignCell*
Definition at line 394 of file DesignInfo.h.
Referenced by operator<<(), and updateParentCellNetInfo().
getDriverPin()
DesignPin * DesignInfo::DesignPin::getDriverPin () inline
Get the driver pin of the pin (nullptr indicates that the pin connects to some global signal like VGG/GND)
Returns
DesignPin*
Definition at line 374 of file DesignInfo.h.
getNet()
DesignNet * DesignInfo::DesignPin::getNet () inline
Definition at line 384 of file DesignInfo.h.
Referenced by DesignInfo::loadUserDefinedClusterNets().
getNetName()
std::string & DesignInfo::DesignPin::getNetName () inline
Get the name of the net which the pin connects to.
Returns
std::string&
Definition at line 313 of file DesignInfo.h.
Referenced by DesignInfo::addPinToNet().
getOffsetXInCell()
float DesignInfo::DesignPin::getOffsetXInCell () inline
Get the offset X of the pin In the cell.
Returns
float
Definition at line 450 of file DesignInfo.h.
getOffsetYInCell()
float DesignInfo::DesignPin::getOffsetYInCell () inline
Get the offset Y of the pin In the cell.
Returns
float
Definition at line 460 of file DesignInfo.h.
getPinType()
DesignPinType DesignInfo::DesignPin::getPinType () inline
Get the Pin Type of the pin.
Returns
DesignPinType
Definition at line 303 of file DesignInfo.h.
getRefPinName()
std::string & DesignInfo::DesignPin::getRefPinName () inline
Get the reference pin name of the pin.
Returns
std::string&
Definition at line 407 of file DesignInfo.h.
Referenced by operator<<().
isInputPort()
bool DesignInfo::DesignPin::isInputPort () inline
Definition at line 343 of file DesignInfo.h.
isOutputPort()
bool DesignInfo::DesignPin::isOutputPort () inline
Definition at line 338 of file DesignInfo.h.
Referenced by DesignInfo::DesignCell::addNetForPin(), DesignInfo::DesignCell::addPin(), and DesignInfo::DesignNet::connectToPinVariable().
isUnconnected()
bool DesignInfo::DesignPin::isUnconnected () inline
check if the attribute unconnected is true
Returns
true indicating the pin connect to no net
false indicating the pin connect to a net, but note that the net could be nullptr(not design net but a global signal)
Definition at line 428 of file DesignInfo.h.
setDriverPin()
void DesignInfo::DesignPin::setDriverPin (DesignPin * _driverPinPtr) inline
Set the Driver Pin object.
Parameters
_driverPinPtr
Definition at line 363 of file DesignInfo.h.
setDriverPinName()
void DesignInfo::DesignPin::setDriverPinName (std::string & _driverPinName) inline
Set the driver Pin Name of the pin.
Parameters
_driverPinName
Definition at line 353 of file DesignInfo.h.
Referenced by DesignInfo::DesignInfo().
setOffsetInCell()
void DesignInfo::DesignPin::setOffsetInCell (float x, float y) inline
Set the Offset of the pin relative to the cell.
Parameters
x
y
Definition at line 439 of file DesignInfo.h.
setUnconnected()
void DesignInfo::DesignPin::setUnconnected () inline
Set the attribute unconnected to be true, indicating the pin connect to no net.
Definition at line 416 of file DesignInfo.h.
Referenced by DesignInfo::DesignInfo().
updateParentCellNetInfo()
void DesignInfo::DesignPin::updateParentCellNetInfo ()
let the parent cell know that one of its pin connects to a specific net
Definition at line 19 of file DesignInfo.cc.
Referenced by DesignInfo::DesignInfo().
Member Data Documentation
driverPin
DesignPin* DesignInfo::DesignPin::driverPin = nullptr private
Definition at line 479 of file DesignInfo.h.
Referenced by getDriverPin(), and setDriverPin().
driverPinName
std::string DesignInfo::DesignPin::driverPinName private
Definition at line 478 of file DesignInfo.h.
Referenced by setDriverPinName().
inputOrNot
bool DesignInfo::DesignPin::inputOrNot private
Definition at line 476 of file DesignInfo.h.
Referenced by isInputPort(), and isOutputPort().
netName
std::string DesignInfo::DesignPin::netName private
Definition at line 473 of file DesignInfo.h.
Referenced by connectToNetName(), and getNetName().
netPtr
DesignNet* DesignInfo::DesignPin::netPtr = nullptr private
Definition at line 475 of file DesignInfo.h.
Referenced by connectToNetVariable(), getNet(), and updateParentCellNetInfo().
offsetXInCell
float DesignInfo::DesignPin::offsetXInCell = 0.0 private
Definition at line 480 of file DesignInfo.h.
Referenced by getOffsetXInCell(), and setOffsetInCell().
offsetYInCell
float DesignInfo::DesignPin::offsetYInCell = 0.0 private
Definition at line 481 of file DesignInfo.h.
Referenced by getOffsetYInCell(), and setOffsetInCell().
pinType
DesignPinType DesignInfo::DesignPin::pinType private
pin type could be:
PinType_LUTInput, PinType_LUTOutput, PinType_CLK, PinType_Q,PinType_D, PinType_E, PinType_SR
Definition at line 472 of file DesignInfo.h.
Referenced by getPinType().
refpinname
std::string DesignInfo::DesignPin::refpinname private
Definition at line 474 of file DesignInfo.h.
Referenced by getRefPinName().
unconnected
bool DesignInfo::DesignPin::unconnected = false private
Definition at line 477 of file DesignInfo.h.
Referenced by isUnconnected(), and setUnconnected().
The documentation for this class was generated from the following files:
src/lib/HiFPlacer/designInfo/DesignInfo.h
src/lib/HiFPlacer/designInfo/DesignInfo.cc