AMF-Placer: src/lib/utils/dumpZip.h File Reference
dumpZip.h File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <zlib.h>
Functions
void writeStrToGZip (std::string fileName, std::stringstream &data)
bool fileExists (const std::string &filename)
Detailed Description
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Definition in file dumpZip.h.
Function Documentation
fileExists()
bool fileExists (const std::string & filename)
Definition at line 33 of file dumpZip.cc.
Referenced by AMFPlacer::AMFPlacer(), and DesignInfo::loadUserDefinedClusterNets().
writeStrToGZip()
void writeStrToGZip (std::string fileName, std::stringstream & data)
Definition at line 17 of file dumpZip.cc.
Referenced by GlobalPlacer::dumpAllCellsCoordinate(), ParallelCLBPacker::dumpAllCellsCoordinate(), GlobalPlacer::dumpBRAMCoordinate(), GlobalPlacer::dumpCARRYCoordinate(), GeneralSpreader::DumpCellsCoordinate(), GlobalPlacer::dumpDSPCoordinate(), GlobalPlacer::dumpFFCoordinate(), ParallelCLBPacker::dumpFinalPacking(), GlobalPlacer::dumpLUTCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), MacroLegalizer::dumpMatching(), CLBLegalizer::dumpMatching(), IncrementalBELPacker::dumpPairedLUTFF(), PlacementInfo::dumpPlacementUnitInformation(), and GeneralSpreader::DumpPUCoordinate().