AMF-Placer: VivadoGraphUtil Namespace Reference
VivadoGraphUtil Namespace Reference
Classes
class VivadoCell
class VivadoCoreCluster
class VivadoNet
class VivadoPatternCluster
class VivadoPatternClusterSeq
class VivadoPin
Functions
def loadCellInfoFromFile (textFile)
def VivadoGraphExctractionAndInitialPatternDetect (VivadoCells)
def getInitalSingleCorePatterns (VivadoGraph, careTypeList, coreType="CARRY", checkDirection="both", allowOverlap=True, onlyRecordInput=False)
def chainBFS (VivadoGraph, nodeId)
def clusterNodeChain (VivadoGraph, coreType="CARRY8")
def clusterNodeWithCommonFanin (VivadoGraph, VivadoCells, targetType="RAM32M16")
def clusterExtendPatterns (VivadoGraph, chains, largeCluserIntoPattern=False, allowOverlap=False, largeCluserThredhold=2)
def printOutSimplePatterns (VivadoGraph, singleCorePattern)
def printOutChainPatterns (VivadoGraph, patternStr2Chains)
def instantiatePatternClusters (VivadoGraph, sortedSingleCorePattern, lastClusterId)
def accumulateClusterForce (Patterns)
def printOutPatterns (patterns)
def BFSCheckEdgeAttributes (VivadoGraph, VivadoCells, curCell)
def loadClusters (name2id, clusterFileName)
def loadClocks (clockFileName)
def loadFixedBlocks (fixedUnitFileName)
Function Documentation
accumulateClusterForce()
def VivadoGraphUtil.accumulateClusterForce (Patterns)
Definition at line 720 of file VivadoGraphUtil.py.
Referenced by accumulateClusterForce().
BFSCheckEdgeAttributes()
def VivadoGraphUtil.BFSCheckEdgeAttributes (VivadoGraph, VivadoCells, curCell)
Definition at line 738 of file VivadoGraphUtil.py.
Referenced by BFSCheckEdgeAttributes().
chainBFS()
def VivadoGraphUtil.chainBFS (VivadoGraph, nodeId)
Definition at line 318 of file VivadoGraphUtil.py.
Referenced by chainBFS(), and clusterNodeChain().
clusterExtendPatterns()
def VivadoGraphUtil.clusterExtendPatterns (VivadoGraph, chains, largeCluserIntoPattern = False, allowOverlap = False, largeCluserThredhold = 2)
Definition at line 453 of file VivadoGraphUtil.py.
Referenced by clusterExtendPatterns().
clusterNodeChain()
def VivadoGraphUtil.clusterNodeChain (VivadoGraph, coreType = "CARRY8")
Definition at line 342 of file VivadoGraphUtil.py.
Referenced by clusterNodeChain().
clusterNodeWithCommonFanin()
def VivadoGraphUtil.clusterNodeWithCommonFanin (VivadoGraph, VivadoCells, targetType = "RAM32M16")
Definition at line 359 of file VivadoGraphUtil.py.
Referenced by clusterNodeWithCommonFanin().
getInitalSingleCorePatterns()
def VivadoGraphUtil.getInitalSingleCorePatterns (VivadoGraph, careTypeList, coreType = "CARRY", checkDirection = "both", allowOverlap = True, onlyRecordInput = False)
Definition at line 217 of file VivadoGraphUtil.py.
Referenced by getInitalSingleCorePatterns().
instantiatePatternClusters()
def VivadoGraphUtil.instantiatePatternClusters (VivadoGraph, sortedSingleCorePattern, lastClusterId)
Definition at line 676 of file VivadoGraphUtil.py.
Referenced by instantiatePatternClusters().
loadCellInfoFromFile()
def VivadoGraphUtil.loadCellInfoFromFile (textFile)
Definition at line 73 of file VivadoGraphUtil.py.
Referenced by loadCellInfoFromFile().
loadClocks()
def VivadoGraphUtil.loadClocks (clockFileName)
Definition at line 808 of file VivadoGraphUtil.py.
Referenced by loadClocks().
loadClusters()
def VivadoGraphUtil.loadClusters (name2id, clusterFileName)
Definition at line 789 of file VivadoGraphUtil.py.
Referenced by loadClusters().
loadFixedBlocks()
def VivadoGraphUtil.loadFixedBlocks (fixedUnitFileName)
Definition at line 816 of file VivadoGraphUtil.py.
Referenced by loadFixedBlocks().
printOutChainPatterns()
def VivadoGraphUtil.printOutChainPatterns (VivadoGraph, patternStr2Chains)
Definition at line 626 of file VivadoGraphUtil.py.
Referenced by printOutChainPatterns().
printOutPatterns()
def VivadoGraphUtil.printOutPatterns (patterns)
Definition at line 727 of file VivadoGraphUtil.py.
printOutSimplePatterns()
def VivadoGraphUtil.printOutSimplePatterns (VivadoGraph, singleCorePattern)
Definition at line 583 of file VivadoGraphUtil.py.
Referenced by printOutSimplePatterns().
VivadoGraphExctractionAndInitialPatternDetect()
def VivadoGraphUtil.VivadoGraphExctractionAndInitialPatternDetect (VivadoCells)
Definition at line 149 of file VivadoGraphUtil.py.
Referenced by VivadoGraphExctractionAndInitialPatternDetect().