AMF-Placer: getPinOffset Namespace Reference
getPinOffset Namespace Reference
Variables
float gw = 0.3
targetPath = sys.argv[1]
deviceName = sys.argv[2]
deviceInfoFile
refpinnamefile
lines = deviceInfoFile.readlines()
exportfile
devicePinNames = set()
pin_SW
pinName = pin_SW[0]
lastWord = pinName[pinName.rfind("_")+1:]
prevWord = pinName[:pinName.rfind("_")]
tmploc = re.search("[0-9]+", lastWord)
SWName = pin_SW[1]
int X = 0
Y = int(SWName[SWName.rfind("Y")+1:])
file
designRefPinNames = set(lines[0].replace("\n", "").split(" "))
Variable Documentation
designRefPinNames
getPinOffset.designRefPinNames = set(lines[0].replace("\n", "").split(" "))
Definition at line 67 of file getPinOffset.py.
deviceInfoFile
getPinOffset.deviceInfoFile
Initial value:
=  open(targetPath+"/"+deviceName +
                      "/"+deviceName+"_PCIEPin2Sw", "r")
Definition at line 20 of file getPinOffset.py.
deviceName
getPinOffset.deviceName = sys.argv[2]
Definition at line 18 of file getPinOffset.py.
devicePinNames
getPinOffset.devicePinNames = set()
Definition at line 30 of file getPinOffset.py.
exportfile
getPinOffset.exportfile
Initial value:
=  open(targetPath+"/"+deviceName +
                  "/"+deviceName+"_PCIEPin2SwXY", "w")
Definition at line 27 of file getPinOffset.py.
file
getPinOffset.file
Definition at line 61 of file getPinOffset.py.
gw
float getPinOffset.gw = 0.3
Definition at line 13 of file getPinOffset.py.
lastWord
string getPinOffset.lastWord = pinName[pinName.rfind("_")+1:]
Definition at line 41 of file getPinOffset.py.
lines
getPinOffset.lines = deviceInfoFile.readlines()
Definition at line 26 of file getPinOffset.py.
pin_SW
getPinOffset.pin_SW
Initial value:
=  line.replace("\n", "").replace(
        "pin=> ", "").replace(" swtile=> ", ";").split(";")
Definition at line 34 of file getPinOffset.py.
pinName
string getPinOffset.pinName = pin_SW[0]
Definition at line 37 of file getPinOffset.py.
prevWord
getPinOffset.prevWord = pinName[:pinName.rfind("_")]
Definition at line 42 of file getPinOffset.py.
refpinnamefile
getPinOffset.refpinnamefile
Initial value:
=  open(
    str(pathlib.Path(__file__).parent.absolute())+"/pcierefpinname", "r")
Definition at line 22 of file getPinOffset.py.
SWName
getPinOffset.SWName = pin_SW[1]
Definition at line 54 of file getPinOffset.py.
targetPath
getPinOffset.targetPath = sys.argv[1]
Definition at line 17 of file getPinOffset.py.
tmploc
getPinOffset.tmploc = re.search("[0-9]+", lastWord)
Definition at line 43 of file getPinOffset.py.
Referenced by PlacementInfo::PlacementSiteTypeInfo.PlacementSiteTypeInfo().
X
int getPinOffset.X = 0
Definition at line 56 of file getPinOffset.py.
Referenced by GeneralSpreader::SpreadRegion.addBinRegion(), PlacementInfo::PlacementNet.addPseudoNet_enhancePin2Pin(), PlacementInfo.createGridBins(), PlacementInfo.createSiteBinGrid(), ParallelCLBPacker.exceptionHandling(), PlacementInfo.loadPlacementUnitInformation(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster.printMyself(), PlacementInfo.setCellBinInfo(), CLBLegalizer.sortPartition(), MacroLegalizer.sortPartition(), GeneralSpreader::SpreadRegion::SubBox.spreadCellsH(), and PlacementInfo.transferCellBinInfo().
Y
getPinOffset.Y = int(SWName[SWName.rfind("Y")+1:])
Definition at line 57 of file getPinOffset.py.
Referenced by GeneralSpreader::SpreadRegion.addBinRegion(), PlacementInfo::PlacementNet.addPseudoNet_enhancePin2Pin(), PlacementInfo.createGridBins(), PlacementInfo.createSiteBinGrid(), PlacementInfo.loadPlacementUnitInformation(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster.printMyself(), PlacementInfo.setCellBinInfo(), and PlacementInfo.transferCellBinInfo().