AMF-Placer: delayVisualization Namespace Reference
delayVisualization Namespace Reference
Functions
def Average (lst)
Variables
parser = argparse.ArgumentParser()
help
required
args = parser.parse_args()
inputFile = open(args.Input, 'r')
lines = inputFile.readlines()
int lineId = 0
disXY2delay = dict()
list XList = []
list YList = []
list delayList = []
pinDrivenLine = lines[lineId]
pinDriverLine = lines[lineId+1]
delayLine = lines[lineId+2]
drivenDrivenSiteName = pinDrivenLine.replace("\n", "").split(" ")[3]
drivenSiteX
drivenSiteY
drivenDriverSiteName = pinDriverLine.replace("\n", "").split(" ")[3]
driverSiteX
driverSiteY
disX = abs(drivenSiteX-driverSiteX)
disY = abs(drivenSiteY-driverSiteY)
tuple tupleXY = (disX, disY)
delay = int(delayLine.split(" ")[1])
z = np.array(delayList)
x = np.array(XList)
y = np.array(YList)
data = np.vstack((x, y, z))
X
Y
XX = X.flatten()
YY = Y.flatten()
A = np.c_[np.ones(data.shape[0]), (data[:, :2])**0.3, data[:, :2]**0.5]
C
_
Z
fig = plt.figure()
ax = fig.gca(projection='3d')
rstride
cstride
alpha
c
s
Function Documentation
Average()
def delayVisualization.Average (lst)
Definition at line 13 of file delayVisualization.py.
Variable Documentation
_
delayVisualization._ private
Definition at line 86 of file delayVisualization.py.
A
delayVisualization.A = np.c_[np.ones(data.shape[0]), (data[:, :2])**0.3, data[:, :2]**0.5]
Definition at line 85 of file delayVisualization.py.
Referenced by WirelengthOptimizer.getCellDistance(), IncrementalBELPacker.getCellDistance(), ClusterPlacer.setClusterNetsAdjMat(), CLBLegalizer.swapPU(), and MacroLegalizer.swapPU().
alpha
delayVisualization.alpha
Definition at line 98 of file delayVisualization.py.
Referenced by PlacementInfo.adjustLUTFFUtilization_Packablity().
args
delayVisualization.args = parser.parse_args()
Definition at line 24 of file delayVisualization.py.
ax
delayVisualization.ax = fig.gca(projection='3d')
Definition at line 97 of file delayVisualization.py.
C
delayVisualization.C
Definition at line 86 of file delayVisualization.py.
Referenced by CLBLegalizer.swapPU(), and MacroLegalizer.swapPU().
c
delayVisualization.c
Definition at line 99 of file delayVisualization.py.
Referenced by CLBLegalizer.DPForMinHPWL(), MacroLegalizer.DPForMinHPWL(), MacroLegalizer.macroCanBeFitIn(), and swapVectors().
cstride
delayVisualization.cstride
Definition at line 98 of file delayVisualization.py.
data
delayVisualization.data = np.vstack((x, y, z))
Definition at line 76 of file delayVisualization.py.
Referenced by writeStrToGZip().
delay
delayVisualization.delay = int(delayLine.split(" ")[1])
Definition at line 55 of file delayVisualization.py.
Referenced by PlacementTimingInfo::TimingGraph< nodeType >.addEdgeBetween(), PlacementTimingOptimizer.getDelayByModel(), PlacementTimingOptimizer.getDelayByModel_conservative(), ParallelCLBPacker.timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath_intermediate(), and GlobalPlacer.timingDrivenDetailedPlacement_shortestPath_intermediate().
delayLine
delayVisualization.delayLine = lines[lineId+2]
Definition at line 38 of file delayVisualization.py.
delayList
list delayVisualization.delayList = []
Definition at line 33 of file delayVisualization.py.
disX
delayVisualization.disX = abs(drivenSiteX-driverSiteX)
Definition at line 51 of file delayVisualization.py.
Referenced by PlacementInfo::PlacementUnit.setSpreadLocation_WithLimitDisplacement(), and WirelengthOptimizer.solverWriteBackData().
disXY2delay
delayVisualization.disXY2delay = dict()
Definition at line 29 of file delayVisualization.py.
disY
delayVisualization.disY = abs(drivenSiteY-driverSiteY)
Definition at line 52 of file delayVisualization.py.
Referenced by PlacementInfo::PlacementUnit.setSpreadLocation_WithLimitDisplacement(), and WirelengthOptimizer.solverWriteBackData().
drivenDrivenSiteName
delayVisualization.drivenDrivenSiteName = pinDrivenLine.replace("\n", "").split(" ")[3]
Definition at line 40 of file delayVisualization.py.
drivenDriverSiteName
delayVisualization.drivenDriverSiteName = pinDriverLine.replace("\n", "").split(" ")[3]
Definition at line 45 of file delayVisualization.py.
drivenSiteX
delayVisualization.drivenSiteX
Initial value:
=  int(drivenDrivenSiteName[drivenDrivenSiteName.rfind(
            "_X")+2:drivenDrivenSiteName.rfind("Y")])
Definition at line 41 of file delayVisualization.py.
drivenSiteY
delayVisualization.drivenSiteY
Initial value:
=  int(
            drivenDrivenSiteName[drivenDrivenSiteName.rfind("Y")+1:])
Definition at line 43 of file delayVisualization.py.
driverSiteX
delayVisualization.driverSiteX
Initial value:
=  int(drivenDriverSiteName[drivenDriverSiteName.rfind(
            "_X")+2:drivenDriverSiteName.rfind("Y")])
Definition at line 46 of file delayVisualization.py.
driverSiteY
delayVisualization.driverSiteY
Initial value:
=  int(
            drivenDriverSiteName[drivenDriverSiteName.rfind("Y")+1:])
Definition at line 48 of file delayVisualization.py.
fig
delayVisualization.fig = plt.figure()
Definition at line 96 of file delayVisualization.py.
help
delayVisualization.help
Definition at line 22 of file delayVisualization.py.
inputFile
delayVisualization.inputFile = open(args.Input, 'r')
Definition at line 25 of file delayVisualization.py.
lineId
int delayVisualization.lineId = 0
Definition at line 27 of file delayVisualization.py.
lines
delayVisualization.lines = inputFile.readlines()
Definition at line 26 of file delayVisualization.py.
Referenced by ClusterPlacer.drawClusters(), and PlacementInfo::PlacementNet.drawNet().
parser
delayVisualization.parser = argparse.ArgumentParser()
Definition at line 17 of file delayVisualization.py.
pinDrivenLine
delayVisualization.pinDrivenLine = lines[lineId]
Definition at line 36 of file delayVisualization.py.
pinDriverLine
delayVisualization.pinDriverLine = lines[lineId+1]
Definition at line 37 of file delayVisualization.py.
required
delayVisualization.required
Definition at line 22 of file delayVisualization.py.
rstride
delayVisualization.rstride
Definition at line 98 of file delayVisualization.py.
s
delayVisualization.s
Definition at line 99 of file delayVisualization.py.
Referenced by strSplit().
tupleXY
tuple delayVisualization.tupleXY = (disX, disY)
Definition at line 54 of file delayVisualization.py.
x
delayVisualization.x = np.array(XList)
Definition at line 73 of file delayVisualization.py.
X
delayVisualization.X
Definition at line 80 of file delayVisualization.py.
Referenced by GeneralSpreader::SpreadRegion.addBinRegion(), PlacementInfo::PlacementNet.addPseudoNet_enhancePin2Pin(), PlacementInfo.createGridBins(), PlacementInfo.createSiteBinGrid(), ParallelCLBPacker.exceptionHandling(), PlacementTimingOptimizer.getDelayByModel_conservative(), ParallelCLBPacker::PackingCLBSite.getHPWLChangeForPU(), PlacementInfo.loadPlacementUnitInformation(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster.printMyself(), PlacementInfo.setCellBinInfo(), CLBLegalizer.sortPartition(), MacroLegalizer.sortPartition(), GeneralSpreader::SpreadRegion::SubBox.spreadCellsH(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath_intermediate(), GlobalPlacer.timingDrivenDetailedPlacement_shortestPath_intermediate(), and PlacementInfo.transferCellBinInfo().
XList
list delayVisualization.XList = []
Definition at line 31 of file delayVisualization.py.
XX
delayVisualization.XX = X.flatten()
Definition at line 81 of file delayVisualization.py.
y
delayVisualization.y = np.array(YList)
Definition at line 74 of file delayVisualization.py.
Y
delayVisualization.Y
Definition at line 80 of file delayVisualization.py.
Referenced by GeneralSpreader::SpreadRegion.addBinRegion(), PlacementInfo::PlacementNet.addPseudoNet_enhancePin2Pin(), PlacementInfo.createGridBins(), PlacementInfo.createSiteBinGrid(), PlacementTimingOptimizer.getDelayByModel_conservative(), ParallelCLBPacker::PackingCLBSite.getHPWLChangeForPU(), PlacementInfo.loadPlacementUnitInformation(), ParallelCLBPacker::PackingCLBSite::PackingCLBCluster.printMyself(), PlacementInfo.setCellBinInfo(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath(), ParallelCLBPacker.timingDrivenDetailedPlacement_shortestPath_intermediate(), GlobalPlacer.timingDrivenDetailedPlacement_shortestPath_intermediate(), and PlacementInfo.transferCellBinInfo().
YList
list delayVisualization.YList = []
Definition at line 32 of file delayVisualization.py.
YY
delayVisualization.YY = Y.flatten()
Definition at line 82 of file delayVisualization.py.
z
delayVisualization.z = np.array(delayList)
Definition at line 72 of file delayVisualization.py.
Z
delayVisualization.Z
Initial value:
=  np.dot(np.c_[np.ones(XX.shape), (XX)**0.3, (YY)**0.3,
                 XX**0.5, YY**0.5], C).reshape(X.shape)
Definition at line 92 of file delayVisualization.py.