AMF-Placer: src/lib/utils/strPrint.cc File Reference
strPrint.cc File Reference
#include "strPrint.h"
#include <chrono>
#include <ios>
#include <stdio.h>
#include <stdlib.h>
#include <string>
Macros
#define PBSTR "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"
#define PBWIDTH 60
Functions
void print_cmd (std::string tmp_string)
void print_info (std::string tmp_string)
void print_status (std::string tmp_string)
void print_error (std::string tmp_string)
void print_warning (std::string tmp_string)
std::string to_string_align3 (int __val)
void printProgress (double percentage)
Variables
std::chrono::time_point< std::chrono::steady_clock > oriTime
Detailed Description
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Definition in file strPrint.cc.
Macro Definition Documentation
PBSTR
#define PBSTR "||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||"
Definition at line 55 of file strPrint.cc.
Referenced by printProgress().
PBWIDTH
#define PBWIDTH 60
Definition at line 56 of file strPrint.cc.
Referenced by printProgress().
Function Documentation
print_cmd()
void print_cmd (std::string tmp_string)
Definition at line 22 of file strPrint.cc.
Referenced by ExternalProcessFunc::execute().
print_error()
void print_error (std::string tmp_string)
Definition at line 40 of file strPrint.cc.
Referenced by PlacementInfo::PlacementBinInfo::addSiteIntoBin(), PlacementInfo::PlacementSiteBinInfo::addSiteIntoBin(), DesignInfo::DesignPin::checkPinType(), PlacementInfo::createGridBins(), DesignInfo::fromStringToCellType(), and InitialPacker::pack().
print_info()
void print_info (std::string tmp_string)
Definition at line 27 of file strPrint.cc.
Referenced by WirelengthOptimizer::addPseudoNet2LoctionForAllPUs(), WirelengthOptimizer::addPseudoNetForMacros(), PlacementInfo::checkClockUtilization(), ClusterPlacer::clockBasedPartitioning(), GlobalPlacer::clusterPlacement(), PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), ClusterPlacer::creaeClusterNets(), ClusterPlacer::createClockBasedClusterUnits(), ClusterPlacer::createLongPathClusterUnits(), ClusterPlacer::createUserDefinedClusterBasedClusterUnits(), DesignInfo::DesignInfo(), DeviceInfo::DeviceInfo(), ParallelCLBPacker::dumpFinalPacking(), ParallelCLBPacker::exceptionHandling(), IncrementalBELPacker::FFPairing(), CLBLegalizer::finalLegalizeBasedOnDP(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findLUTRAMMacros(), InitialPacker::findMuxMacros(), PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::forwardLevelization(), PlacementTimingOptimizer::getSlackThr(), GlobalPlacer::GlobalPlacement_CLBElements(), GlobalPlacer::GlobalPlacement_fixedCLB(), ClusterPlacer::isClustersToLarges(), DeviceInfo::loadBELType2FalseBELType(), DesignInfo::loadClocks(), InitialPacker::loadOtherCLBMacros(), DesignInfo::loadUserDefinedClusterNets(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::LUTFFPairing(), GlobalPlacer::macroLegalize(), MinCostBipartiteMatcher::MinCostBipartiteMatcher(), GraphPartitioner< std::vector< PlacementInfo::PlacementUnit *>, std::vector< PlacementInfo::PlacementNet *> >::minCutBipartition(), InitialPacker::pack(), GlobalPlacer::printPlacedUnits(), DeviceInfo::printStat(), DesignInfo::printStat(), PlacementInfo::printStat(), ClusterPlacer::refineClustersWithPredefinedClusters(), PlacementInfo::reloadNets(), AMFPlacer::run(), SAPlacer::solve(), GeneralSpreader::spreadPlacementUnits(), DesignInfo::updateFFControlSets(), GlobalPlacer::updatePseudoNetWeight(), CLBLegalizer::updatePUMatchingLocation(), and MacroLegalizer::updatePUMatchingLocation().
print_status()
void print_status (std::string tmp_string)
Definition at line 32 of file strPrint.cc.
Referenced by WirelengthOptimizer::addPseudoNet_SlackBased(), PlacementInfo::adjustLUTFFUtilization(), PlacementInfo::adjustLUTFFUtilization_Clocking(), PlacementInfo::adjustLUTFFUtilization_Packablity(), PlacementInfo::adjustLUTFFUtilization_Routability(), PlacementInfo::adjustLUTFFUtilization_Routability_Reset(), PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::backwardLevelization(), PlacementTimingInfo::buildSimpleTimingGraph(), ClusterPlacer::ClusterPlacement(), ClusterPlacer::clusterPlacementUnits(), PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), PlacementTimingOptimizer::conductStaticTimingAnalysis(), PlacementInfo::createGridBins(), ClusterPlacer::createLongPathClusterUnits(), DesignInfo::DesignInfo(), DeviceInfo::DeviceInfo(), GlobalPlacer::dumpAllCellsCoordinate(), ParallelCLBPacker::dumpAllCellsCoordinate(), GlobalPlacer::dumpBRAMCoordinate(), GlobalPlacer::dumpCARRYCoordinate(), PlacementTimingOptimizer::dumpClockRegionClusters(), ClusterPlacer::dumpClusters(), PlacementInfo::dumpCongestion(), GlobalPlacer::dumpDSPCoordinate(), GlobalPlacer::dumpFFCoordinate(), ParallelCLBPacker::dumpFinalPacking(), GlobalPlacer::dumpLUTCoordinate(), GeneralSpreader::dumpLUTFFCoordinate(), GlobalPlacer::dumpLUTFFCoordinate(), MacroLegalizer::dumpMatching(), CLBLegalizer::dumpMatching(), IncrementalBELPacker::dumpPairedLUTFF(), PlacementInfo::dumpPlacementUnitInformation(), GeneralSpreader::dumpSiteGridDensity(), PlacementInfo::dumpVivadoPlacementTclWithPULegalizationInfo(), ParallelCLBPacker::exceptionHandling(), IncrementalBELPacker::FFPairing(), MacroLegalizer::finalLegalizeBasedOnDP(), InitialPacker::findBRAMMacros(), InitialPacker::findCARRYMacros(), InitialPacker::findDSPMacros(), InitialPacker::findLUTRAMMacros(), InitialPacker::findMuxMacros(), MacroLegalizer::findPossibleLegalLocation(), PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::forwardLevelization(), GlobalPlacer::GlobalPlacement_CLBElements(), GlobalPlacer::GlobalPlacement_fixedCLB(), WirelengthOptimizer::GlobalPlacementQPSolve(), PlacementTimingOptimizer::incrementalStaticTimingAnalysis_forPUWithLocation(), MacroLegalizer::legalize(), CLBLegalizer::legalize(), InitialPacker::loadOtherCLBMacros(), PlacementInfo::loadPlacementUnitInformation(), DesignInfo::loadUserDefinedClusterNets(), IncrementalBELPacker::LUTFFPairing(), InitialPacker::LUTFFPairing(), WirelengthOptimizer::LUTLUTPairing_TimingDriven(), GlobalPlacer::macroLegalize(), InitialPacker::pack(), ParallelCLBPacker::packCLBs(), ParallelCLBPacker::ParallelCLBPacker(), ClusterPlacer::placeClusters(), PlacementInfo::PlacementInfo(), QPSolverWrapper::QPSolve(), PlacementInfo::reloadNets(), AMFPlacer::run(), PlacementInfo::CompatiblePlacementTable::setBELTypeForCells(), PlacementTimingInfo::setDSPInnerDelay(), GeneralSpreader::spreadPlacementUnits(), ParallelCLBPacker::timingDrivenDetailedPlacement_LUTFFPairReloacationAfterSlotMapping(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath(), GlobalPlacer::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_shortestPath_intermediate(), ParallelCLBPacker::timingDrivenDetailedPlacement_swap(), WirelengthOptimizer::updateB2BNetWeight(), PlacementInfo::updateLongPaths(), ParallelCLBPacker::updatePackedMacro(), GlobalPlacer::updatePseudoNetWeight(), and PlacementInfo::verifyDeviceForDesign().
print_warning()
void print_warning (std::string tmp_string)
Definition at line 45 of file strPrint.cc.
Referenced by DesignInfo::addCell(), WirelengthOptimizer::addPseudoNet_SlackBased(), PlacementTimingOptimizer::clusterLongPathInOneClockRegion(), PlacementTimingOptimizer::conductStaticTimingAnalysis(), PlacementInfo::createGridBins(), DesignInfo::DesignInfo(), PlacementTimingInfo::TimingGraph< DesignInfo::DesignCell >::forwardLevelization(), GlobalPlacer::GlobalPlacement_CLBElements(), GlobalPlacer::GlobalPlacer(), ClusterPlacer::isClustersToLarges(), CLBLegalizer::legalize(), MacroLegalizer::legalize(), DesignInfo::loadClocks(), PlacementInfo::loadPlacementUnitInformation(), GlobalPlacer::macroLegalize(), GraphPartitioner< std::vector< PlacementInfo::PlacementUnit *>, std::vector< PlacementInfo::PlacementNet *> >::minCutBipartition(), PlacementInfo::optimizeLongPaths(), parseJSONFile(), PlacementInfo::reloadNets(), InitialPacker::setDSPRegs(), MacroLegalizer::spreadMacros(), PlacementTimingOptimizer::stretchClockRegionColumns(), WirelengthOptimizer::updateB2BNetWeight(), WirelengthOptimizer::updatePseudoNetForClockRegion(), WirelengthOptimizer::updatePseudoNetForUserDefinedClusters(), GlobalPlacer::updatePseudoNetWeight(), and WirelengthOptimizer::WirelengthOptimizer().
printProgress()
void printProgress (double percentage)
Definition at line 58 of file strPrint.cc.
Referenced by SAPlacer::solve().
to_string_align3()
std::string to_string_align3 (int __val)
Definition at line 50 of file strPrint.cc.
Referenced by GlobalPlacer::GlobalPlacement_CLBElements().
Variable Documentation
oriTime
std::chrono::time_point<std::chrono::steady_clock> oriTime
Definition at line 20 of file strPrint.cc.
Referenced by AMFPlacer::AMFPlacer(), and print_status().