AMF-Placer: src/lib/utils/stringCheck.h File Reference
stringCheck.h File Reference
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>
Functions
bool strContains (std::string target, std::string substring)
void strSplit (const std::string &s, std::vector< std::string > &sv, const char *delim)
void replaceAll (std::string &str, const std::string from, const std::string to)
Detailed Description
Author
Tingyuan LIANG (tlian.nosp@m.g@co.nosp@m.nnect.nosp@m..ust.nosp@m..hk)
Version
0.1
Date
2021-10-02
Copyright
Copyright (c) 2021 Reconfiguration Computing Systems Lab, The Hong Kong University of Science and Technology. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
Definition in file stringCheck.h.
Function Documentation
replaceAll()
void replaceAll (std::string & str, const std::string from, const std::string to)
Definition at line 50 of file stringCheck.cc.
Referenced by DeviceInfo::DeviceInfo(), ParallelCLBPacker::dumpCLBPlacementTcl(), ParallelCLBPacker::dumpDSPBRAMPlacementTcl(), and PlacementTimingInfo::PlacementTimingInfo().
strContains()
bool strContains (std::string target, std::string substring)
Definition at line 30 of file stringCheck.cc.
Referenced by DesignInfo::DesignInfo(), DeviceInfo::DeviceInfo(), InitialPacker::loadFixedPlacementUnits(), InitialPacker::loadOtherCLBMacros(), and DeviceInfo::loadPCIEPinOffset().
strSplit()
void strSplit (const std::string & s, std::vector< std::string > & sv, const char * delim)
Definition at line 35 of file stringCheck.cc.
Referenced by PlacementInfo::CompatiblePlacementTable::CompatiblePlacementTable(), DeviceInfo::DeviceInfo(), ParallelCLBPacker::dumpCLBPlacementTcl(), ParallelCLBPacker::dumpDSPBRAMPlacementTcl(), DeviceInfo::loadBELType2FalseBELType(), InitialPacker::loadOtherCLBMacros(), PlacementInfo::loadPlacementUnitInformation(), DesignInfo::loadUserDefinedClusterNets(), and parseJSONFile().